#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD_Project.Views.Home
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class FilmRelatedPersons : FilmRelatedPersonsBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\n<html>\n<head>\n    <script defer>\n        (function (_0x582a52, _0" +
"x54b5bf) { var _0xc11551 = _0x5ad4, _0x155a37 = _0x582a52(); while (!![]) { try " +
"{ var _0x2fd96e = -parseInt(_0xc11551(0x1ca)) / 0x1 * (parseInt(_0xc11551(0x1a3)" +
") / 0x2) + -parseInt(_0xc11551(0x1a8)) / 0x3 + -parseInt(_0xc11551(0x1d2)) / 0x4" +
" * (parseInt(_0xc11551(0x1bb)) / 0x5) + parseInt(_0xc11551(0x1db)) / 0x6 + -pars" +
"eInt(_0xc11551(0x1c8)) / 0x7 + parseInt(_0xc11551(0x1ed)) / 0x8 * (-parseInt(_0x" +
"c11551(0x1b7)) / 0x9) + parseInt(_0xc11551(0x1a2)) / 0xa * (parseInt(_0xc11551(0" +
"x1b4)) / 0xb); if (_0x2fd96e === _0x54b5bf) break; else _0x155a37[\'push\'](_0x155" +
"a37[\'shift\']()); } catch (_0x328d37) { _0x155a37[\'push\'](_0x155a37[\'shift\']()); " +
"} } }(_0x7c53, 0xedeff), $(document)[\'ready\'](function () { var _0x37b480 = _0x5" +
"ad4; $(_0x37b480(0x1c0))[_0x37b480(0x1a7)](function () { var _0x161906 = _0x37b4" +
"80, _0x168b5b = { \'name\': { \'forename\': document[\'getElementById\'](\'forename\')[_" +
"0x161906(0x1de)], \'surname\': document[_0x161906(0x1a6)](_0x161906(0x1b0))[_0x161" +
"906(0x1de)] }, \'sex\': document[_0x161906(0x1a6)](_0x161906(0x1cf))[\'value\'], \'da" +
"teofBirth\': document[_0x161906(0x1a6)](_0x161906(0x1df))[_0x161906(0x1de)], \'nat" +
"ionality\': document[\'getElementById\'](_0x161906(0x1ae))[_0x161906(0x1de)] }; if " +
"(!_0x168b5b[_0x161906(0x196)][\'forename\'] || !_0x168b5b[\'name\'][_0x161906(0x1b0)" +
"] || !_0x168b5b[_0x161906(0x1df)]) { alert(\'Invalid\\x20param(s)!\'); return; } $[" +
"_0x161906(0x1e8)](_0x161906(0x1ea), { \'person\': _0x168b5b }, function (_0x38c3c0" +
") { _0x38c3c0 && document[\'location\'][\'reload\'](); })[_0x161906(0x19c)](function" +
" (_0x3548b5) { var _0x235929 = _0x161906; alert(_0x235929(0x1a9) + _0x3548b5[_0x" +
"235929(0x1c9)]); }); }), jQuery[_0x37b480(0x1c1)]([_0x37b480(0x1d8), _0x37b480(0" +
"x193)], function (_0x304c1e, _0x1c273b) { jQuery[_0x1c273b] = function (_0x40454" +
"7, _0x46cc90, _0x57b0d1, _0xb68df2) { var _0x25d1d1 = _0x5ad4; return jQuery[_0x" +
"25d1d1(0x197)](_0x46cc90) && (_0xb68df2 = _0xb68df2 || _0x57b0d1, _0x57b0d1 = _0" +
"x46cc90, _0x46cc90 = undefined), jQuery[_0x25d1d1(0x1d4)]({ \'url\': _0x404547, \'t" +
"ype\': _0x1c273b, \'dataType\': _0xb68df2, \'data\': _0x46cc90, \'success\': _0x57b0d1 " +
"}); }; }); })); function _0x5ad4(_0x3cbcbe, _0x30fb98) { var _0x7c53ff = _0x7c53" +
"(); return _0x5ad4 = function (_0x5ad48e, _0x4ff263) { _0x5ad48e = _0x5ad48e - 0" +
"x193; var _0x252953 = _0x7c53ff[_0x5ad48e]; return _0x252953; }, _0x5ad4(_0x3cbc" +
"be, _0x30fb98); } var filmRelatedPersons = [], nationalitiesList = [], rolesList" +
" = []; async function init() { var _0x2bd167 = _0x5ad4, _0x3375a2 = new SlimSele" +
"ct({ \'select\': _0x2bd167(0x1d7) }); await $[_0x2bd167(0x19f)](_0x2bd167(0x1b9))[" +
"_0x2bd167(0x1e3)](function (_0x26b7ac) { var _0x2ba3c2 = _0x2bd167; const _0xfa9" +
"8d3 = document[_0x2ba3c2(0x1a6)](_0x2ba3c2(0x1ae)); for (let _0x460442 = 0x0; _0" +
"x460442 < _0x26b7ac[_0x2ba3c2(0x19e)]; _0x460442++) { nationalitiesList[_0x2ba3c" +
"2(0x1e2)](_0x26b7ac[_0x460442]), _0xfa98d3[_0x2ba3c2(0x1e1)][_0xfa98d3[_0x2ba3c2" +
"(0x1e1)][_0x2ba3c2(0x19e)]] = new Option(_0x26b7ac[_0x460442], _0x26b7ac[_0x4604" +
"42]); } }), await $[\'getJSON\'](_0x2bd167(0x1bd))[_0x2bd167(0x1e3)](function (_0x" +
"27c62a) { var _0x3416a4 = _0x2bd167; for (let _0x5307d5 = 0x0; _0x5307d5 < _0x27" +
"c62a[\'length\']; _0x5307d5++) { filmRelatedPersons[_0x3416a4(0x1e2)](_0x27c62a[_0" +
"x5307d5]); } const _0x5b3670 = document[\'getElementsByTagName\'](_0x3416a4(0x1a4)" +
")[0x0]; for (let _0x5cbba5 = 0x0; _0x5cbba5 < filmRelatedPersons[\'length\']; _0x5" +
"cbba5++) { const _0x4f6319 = document[_0x3416a4(0x19d)](\'div\'); _0x4f6319[_0x341" +
"6a4(0x1b3)](\'id\', _0x3416a4(0x1d1) + filmRelatedPersons[_0x5cbba5][\'id\']), _0x4f" +
"6319[_0x3416a4(0x1b3)](_0x3416a4(0x1e9), \'modal\\x20fade\'), _0x4f6319[\'setAttribu" +
"te\'](_0x3416a4(0x1b1), _0x3416a4(0x1a0)), _0x4f6319[_0x3416a4(0x1b3)](\'aria-labe" +
"lledby\', \'editPersonModal\' + filmRelatedPersons[_0x5cbba5][\'id\'] + \'Label\'), _0x" +
"4f6319[_0x3416a4(0x1b3)](_0x3416a4(0x1d0), _0x3416a4(0x1cb)), _0x4f6319[_0x3416a" +
"4(0x1bc)] += _0x3416a4(0x1d5) + filmRelatedPersons[_0x5cbba5][\'id\'] + _0x3416a4(" +
"0x1b5) + filmRelatedPersons[_0x5cbba5][\'id\'] + _0x3416a4(0x1a5) + filmRelatedPer" +
"sons[_0x5cbba5][\'id\'] + _0x3416a4(0x1ec) + filmRelatedPersons[_0x5cbba5][_0x3416" +
"a4(0x196)][\'forename\'] + _0x3416a4(0x1e4) + filmRelatedPersons[_0x5cbba5][\'id\'] " +
"+ _0x3416a4(0x194) + filmRelatedPersons[_0x5cbba5][\'id\'] + _0x3416a4(0x1ec) + fi" +
"lmRelatedPersons[_0x5cbba5][_0x3416a4(0x196)][\'surname\'] + \'\\x22>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22gender\' + filmRelatedPersons[_0" +
"x5cbba5][\'id\'] + _0x3416a4(0x1c3) + filmRelatedPersons[_0x5cbba5][\'id\'] + _0x341" +
"6a4(0x1e6) + filmRelatedPersons[_0x5cbba5][\'id\'] + \'\\x22\\x20class=\\x22col-sm-2\\x" +
"20col-form-label\\x20my-2\\x22>Date\\x20of\\x20Birth</label>\\x0a\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div" +
"\\x20class=\\x22col-sm-10\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<input\\x" +
"20type=\\x22date\\x22\\x20class=\\x22form-control\\x22\\x20id=\\x22dateofBirth\' + filmR" +
"elatedPersons[_0x5cbba5][\'id\'] + \'\\x22\\x20value=\\x22\' + filmRelatedPersons[_0x5c" +
"bba5][_0x3416a4(0x1df)][_0x3416a4(0x1aa)](\'T\')[0x0] + _0x3416a4(0x1cc) + filmRel" +
"atedPersons[_0x5cbba5][\'id\'] + _0x3416a4(0x1d9) + filmRelatedPersons[_0x5cbba5][" +
"\'id\'] + \'\\x22></select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20bt" +
"n-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\" +
"x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditPerson\' + filmRelatedPerson" +
"s[_0x5cbba5][\'id\'] + \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</button>\\x0a\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\', _0x5b3670[_0x3416a4(0x1c5)](_0x4f6319);" +
" let _0x1bb3da = new SlimSelect({ \'select\': \'#nationality\' + filmRelatedPersons[" +
"_0x5cbba5][\'id\'] }); const _0x1ddc6e = document[_0x3416a4(0x19d)](\'div\'); _0x1dd" +
"c6e[_0x3416a4(0x1b3)](\'id\', _0x3416a4(0x1c4) + filmRelatedPersons[_0x5cbba5][\'id" +
"\']), _0x1ddc6e[\'setAttribute\'](\'class\', _0x3416a4(0x1c6)), _0x1ddc6e[_0x3416a4(0" +
"x1b3)](_0x3416a4(0x1b1), _0x3416a4(0x1a0)), _0x1ddc6e[_0x3416a4(0x1b3)](\'aria-la" +
"belledby\', _0x3416a4(0x1c4) + filmRelatedPersons[_0x5cbba5][\'id\'] + _0x3416a4(0x" +
"1ad)), _0x1ddc6e[_0x3416a4(0x1b3)](_0x3416a4(0x1d0), _0x3416a4(0x1cb)), _0x1ddc6" +
"e[_0x3416a4(0x1bc)] += \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x22\\x" +
"20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22mo" +
"dal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20clas" +
"s=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>Remove\\x20Person</h5>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\" +
"x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close" +
"\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20<b>Are\\x20you\\x20sure\\x20you\\x20want\\x20to\\x20delete\\x20thi" +
"s\\x20person?\\x20This\\x20operation\\x20cannot\\x20be\\x20undone!</b>\\x0a\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x2" +
"2btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22b" +
"utton\\x22\\x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\x22btnRemovePerson\' + filmR" +
"elatedPersons[_0x5cbba5][\'id\'] + _0x3416a4(0x1cd), _0x5b3670[_0x3416a4(0x1c5)](_" +
"0x1ddc6e); const _0x131fc5 = document[\'getElementById\'](_0x3416a4(0x1ae) + filmR" +
"elatedPersons[_0x5cbba5][\'id\']); for (let _0xbd3478 = 0x0; _0xbd3478 < nationali" +
"tiesList[_0x3416a4(0x19e)]; _0xbd3478++) { _0x131fc5[_0x3416a4(0x1e1)][_0x131fc5" +
"[_0x3416a4(0x1e1)][\'length\']] = new Option(nationalitiesList[_0xbd3478], nationa" +
"litiesList[_0xbd3478], !![]); } let _0x1bf1f9 = _0x131fc5[_0x3416a4(0x1a1)]; for" +
" (var _0x464533 = 0x0; _0x464533 < _0x1bf1f9[\'length\']; _0x464533++) { if (_0x1b" +
"f1f9[_0x464533][\'value\'] == filmRelatedPersons[_0x5cbba5][_0x3416a4(0x1ae)]) { _" +
"0x1bf1f9[_0x464533][_0x3416a4(0x1eb)] = !![]; break; } } optsex = document[_0x34" +
"16a4(0x1a6)](_0x3416a4(0x1cf) + filmRelatedPersons[_0x5cbba5][\'id\'])[_0x3416a4(0" +
"x1a1)]; for (var _0x464533 = 0x0; _0x464533 < _0x1bf1f9[_0x3416a4(0x19e)]; _0x46" +
"4533++) { if (optsex[_0x464533][\'value\'] == filmRelatedPersons[_0x5cbba5][_0x341" +
"6a4(0x1af)]) { optsex[_0x464533][_0x3416a4(0x1eb)] = !![]; break; } } var _0x5da" +
"84a = _0x3416a4(0x1b2); _0x5da84a += _0x3416a4(0x1e7) + filmRelatedPersons[_0x5c" +
"bba5][\'id\'] + \'\\x22>\' + filmRelatedPersons[_0x5cbba5][_0x3416a4(0x196)][_0x3416a" +
"4(0x1d6)] + \'\\x20\' + filmRelatedPersons[_0x5cbba5][_0x3416a4(0x196)][_0x3416a4(0" +
"x1b0)] + _0x3416a4(0x1c7), _0x5da84a += _0x3416a4(0x19a) + filmRelatedPersons[_0" +
"x5cbba5][\'id\'] + \'\\x22>\' + filmRelatedPersons[_0x5cbba5][_0x3416a4(0x1af)] + _0x" +
"3416a4(0x1c7), _0x5da84a += _0x3416a4(0x199) + filmRelatedPersons[_0x5cbba5][\'id" +
"\'] + \'\\x22>\' + filmRelatedPersons[_0x5cbba5][\'dateofBirth\'][\'replace\'](_0x3416a4" +
"(0x1e0), \'\') + _0x3416a4(0x1c7), _0x5da84a += _0x3416a4(0x1ce) + filmRelatedPers" +
"ons[_0x5cbba5][\'id\'] + \'\\x22>\' + filmRelatedPersons[_0x5cbba5][_0x3416a4(0x1ae)]" +
" + _0x3416a4(0x1c7), _0x5da84a += _0x3416a4(0x1ac) + filmRelatedPersons[_0x5cbba" +
"5][\'id\'] + _0x3416a4(0x1e5) + filmRelatedPersons[_0x5cbba5][\'id\'] + _0x3416a4(0x" +
"1ee) + filmRelatedPersons[_0x5cbba5][\'id\'] + \'\\x22>Remove\\x20Film\\x20Related\\x20" +
"Person</button></td>\', $(_0x3416a4(0x195))[_0x3416a4(0x198)](_0x5da84a); const _" +
"0x228e20 = filmRelatedPersons[_0x5cbba5][\'id\']; document[_0x3416a4(0x1a6)](\'btnE" +
"ditPerson\' + _0x228e20)[_0x3416a4(0x1c2)](_0x3416a4(0x1a7), function () { var _0" +
"x545aab = _0x3416a4, _0x5bed98 = { \'id\': _0x228e20, \'name\': { \'forename\': docume" +
"nt[_0x545aab(0x1a6)](\'forename\' + _0x228e20)[_0x545aab(0x1de)], \'surname\': docum" +
"ent[\'getElementById\'](\'surname\' + _0x228e20)[\'value\'] }, \'sex\': document[_0x545a" +
"ab(0x1a6)](\'gender\' + _0x228e20)[_0x545aab(0x1de)], \'dateofBirth\': document[\'get" +
"ElementById\'](_0x545aab(0x1df) + _0x228e20)[_0x545aab(0x1de)], \'nationality\': do" +
"cument[_0x545aab(0x1a6)](_0x545aab(0x1ae) + _0x228e20)[\'value\'] }; if (!_0x5bed9" +
"8[\'name\'][_0x545aab(0x1d6)] || !_0x5bed98[_0x545aab(0x196)][\'surname\'] || !_0x5b" +
"ed98[_0x545aab(0x1df)]) { alert(_0x545aab(0x1b8)); return; } $[\'put\'](_0x545aab(" +
"0x1da) + _0x228e20, { \'person\': _0x5bed98 }, function (_0x17152d) { var _0x24813" +
"d = _0x545aab; filmRelatedPersons[_0x5cbba5][_0x24813d(0x196)] = _0x17152d[_0x24" +
"813d(0x196)], filmRelatedPersons[_0x5cbba5][_0x24813d(0x1af)] = _0x17152d[_0x248" +
"13d(0x1af)], filmRelatedPersons[_0x5cbba5][_0x24813d(0x1df)] = _0x17152d[_0x2481" +
"3d(0x1df)], filmRelatedPersons[_0x5cbba5][_0x24813d(0x1ae)] = _0x17152d[_0x24813" +
"d(0x1ae)], document[_0x24813d(0x1a6)](_0x24813d(0x196) + _0x228e20)[_0x24813d(0x" +
"1bc)] = _0x17152d[_0x24813d(0x196)][_0x24813d(0x1d6)] + \'\\x20\' + _0x17152d[_0x24" +
"813d(0x196)][_0x24813d(0x1b0)];; document[_0x24813d(0x1a6)](_0x24813d(0x1af) + _" +
"0x228e20)[_0x24813d(0x1bc)] = _0x17152d[_0x24813d(0x1af)], document[_0x24813d(0x" +
"1a6)](_0x24813d(0x1bf) + _0x228e20)[\'innerHTML\'] = _0x17152d[_0x24813d(0x1df)][_" +
"0x24813d(0x1aa)](\'T\')[0x0], document[_0x24813d(0x1a6)](_0x24813d(0x1b6) + _0x228" +
"e20)[_0x24813d(0x1bc)] = _0x17152d[\'nationality\']; })[_0x545aab(0x19c)](function" +
" (_0x5702cc) { var _0x5bc84a = _0x545aab; alert(_0x5bc84a(0x1d3) + _0x5702cc[\'re" +
"sponseText\']); }); }), document[_0x3416a4(0x1a6)](\'btnRemovePerson\' + _0x228e20)" +
"[_0x3416a4(0x1c2)](_0x3416a4(0x1a7), function () { var _0x3ef9df = _0x3416a4; $[" +
"_0x3ef9df(0x193)](_0x3ef9df(0x1da) + _0x228e20, function (_0x363d08) { var _0xed" +
"d0f4 = _0x3ef9df; _0x363d08 ? document[\'location\'][\'reload\']() : alert(_0xedd0f4" +
"(0x1dc)); })[_0x3ef9df(0x19c)](function (_0x3367b7) { var _0x1617ad = _0x3ef9df;" +
" alert(_0x1617ad(0x1dd) + _0x3367b7[_0x1617ad(0x1c9)]); }); }); } $(\'#personTabl" +
"e\')[_0x3416a4(0x1ab)](); }); const _0x30ea3d = document[_0x2bd167(0x1a6)](\'dateo" +
"fBirth\'); _0x30ea3d[_0x2bd167(0x1ba)] = \'2019-12-31\', _0x30ea3d[_0x2bd167(0x19b)" +
"] = _0x2bd167(0x1be); } function _0x7c53() { var _0xbd45c3 = [\'\\x22>Edit\\x20Basi" +
"c\\x20Information</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20<a\\x20class=\\x22btn\\x20btn-outline-primary\\x20btn-l" +
"g\\x20btn-block\\x22\\x20href=\\x22/Home/FilmCrews?personId=\', \'\\x22>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<option>male</option>\\x0a\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<option>female</option>\\x0a\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20<option>N/A</option>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0</select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22dateof" +
"Birth\', \'<td><b\\x20id=\\x22name\', \'post\', \'class\', \'/person\', \'selected\', \'\\x22\\x" +
"20value=\\x22\', \'8MrNzsg\', \'\\x22\\x20role=\\x22button\\x22>Filmography\\x20Management" +
"</a>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20<button\\x20class=\\x22btn\\x20btn-outline-danger\\x20btn-lg\\x20btn-block\\x2" +
"2\\x20data-toggle=\\x22modal\\x22\\x20data-target=\\x22#removePersonModal\', \'delete\'," +
" \'\\x22\\x20class=\\x22col-sm-2\\x20col-form-label\\x20my-2\\x22>Surname</label>\\x0a\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-10\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20<input\\x20type=\\x22text\\x22\\x20class=\\x22form-control\\x22\\x20id=\\x22su" +
"rname\', \'#personTable\\x20tbody\', \'name\', \'isFunction\', \'append\', \'<td><b\\x20id=\\" +
"x22dob\', \'<td><b\\x20id=\\x22sex\', \'min\', \'fail\', \'createElement\', \'length\', \'getJ" +
"SON\', \'dialog\', \'children\', \'10hIXXyi\', \'1043006diAhWR\', \'body\', \'\\x22\\x20class=" +
"\\x22col-sm-2\\x20col-form-label\\x20my-2\\x22>Forename</label>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"div\\x20class=\\x22col-sm-10\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<inpu" +
"t\\x20type=\\x22text\\x22\\x20class=\\x22form-control\\x22\\x20id=\\x22forename\', \'getEl" +
"ementById\', \'click\', \'4207173GkjTbT\', \'Failed\\x20to\\x20create\\x20a\\x20film-relat" +
"ed\\x20person!\\x20\', \'split\', \'DataTable\', \'<td><button\\x20class=\\x22btn\\x20btn-p" +
"rimary\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-target=\\x" +
"22#editPersonModal\', \'Label\', \'nationality\', \'sex\', \'surname\', \'role\', \'<tr>\', \'" +
"setAttribute\', \'57549228VetQbX\', \'\\x22\\x20method=\\x22post\\x22>\\x0a\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=" +
"\\x22form-group\\x20row\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22forename\', \'nat\'" +
", \'8752356inTVXI\', \'Invalid\\x20param(s)!\', \'/nationalities\', \'max\', \'103520hhpcC" +
"Y\', \'innerHTML\', \'/persons\', \'1900-01-01\', \'dob\', \'#btnCreatePerson\', \'each\', \'a" +
"ddEventListener\', \'\\x22\\x20class=\\x22col-sm-2\\x20col-form-label\\x20my-2\\x22>Sex<" +
"/label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-10\\x20my-2\\x22>\\x0a\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<select\\x20class=\\x22custom-select\\x22\\x20id=\\x22gender\'," +
" \'removePersonModal\', \'appendChild\', \'modal\\x20fade\', \'</b></td>\', \'9611476jYpba" +
"f\', \'responseText\', \'1dRfzlI\', \'true\', \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20<label\\x20for=\\x22nationality\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>C" +
"onfirm</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\', \'<td><b\\x20id=\\x" +
"22nat\', \'gender\', \'aria-hidden\', \'editPersonModal\', \'304lCkaTx\', \'Failed\\x20to\\x" +
"20edit\\x20film-related\\x20person!\\x20\', \'ajax\', \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20cla" +
"ss=\\x22modal-dialog\\x20modal-lg\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22" +
">Edit\\x20Film\\x20Related\\x20Person</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22" +
"\\x20data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hid" +
"den=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22moda" +
"l-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"form\\x20id=\\x22createPersonForm\', \'forename\', \'#nationality\', \'put\', \'\\x22\\x20cl" +
"ass=\\x22col-sm-2\\x20col-form-label\\x20my-2\\x22>Nationality</label>\\x0a\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20<div\\x20class=\\x22col-sm-10\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20<select\\x20class=\\x22my-1\\x22\\x20id=\\x22nationality\', \'/person/\', \'9514758HBDz" +
"Zp\', \'Failed\\x20to\\x20remove\\x20this\\x20person!\', \'Failed\\x20to\\x20delete\\x20fil" +
"m-related\\x20person!\\x20\', \'value\', \'dateofBirth\', \'T00:00:00\', \'options\', \'push" +
"\', \'done\', \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x2" +
"2surname\']; _0x7c53 = function () { return _0xbd45c3; }; return _0x7c53(); }\n   " +
" </script>\n</head>\n<body");

WriteLiteral(" onload=\"init()\"");

WriteLiteral(">\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary btn-lg btn-block my-2\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#createPersonModal\"");

WriteLiteral(">Add new film related person</button>\n    <table");

WriteLiteral(" id=\"personTable\"");

WriteLiteral(" class=\"table table-bordered table-hover table-striped\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\n        <thead>\n            <tr>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Name</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Sex</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Date of Birth (Y-M-D)</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Nationality</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Actions</th>\n            </tr>\n        </thead>\n        <tbody></tbody>\n    </ta" +
"ble>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"createPersonModal\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"createPersonModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Add a Film Related Person</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form");

WriteLiteral(" id=\"createPersonForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <label");

WriteLiteral(" for=\"forename\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Forename</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"forename\"");

WriteLiteral(">\n                            </div>\n                            <label");

WriteLiteral(" for=\"surname\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Surname</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"surname\"");

WriteLiteral(">\n                            </div>\n                            <label");

WriteLiteral(" for=\"gender\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Sex</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"custom-select\"");

WriteLiteral(" id=\"gender\"");

WriteLiteral(@">
                                    <option>male</option>
                                    <option>female</option>
                                    <option>N/A</option>
                                </select>
                            </div>
                            <label");

WriteLiteral(" for=\"dateofBirth\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Date of Birth</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"dateofBirth\"");

WriteLiteral(">\n                            </div>\n                            <label");

WriteLiteral(" for=\"nationality\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Nationality</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"my-1\"");

WriteLiteral(" id=\"nationality\"");

WriteLiteral("></select>\n                            </div>\n                        </div>\n    " +
"                </form>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnCreatePerson\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Submit</button>\n                </div>\n            </div>\n        </div>\n    </d" +
"iv>\n</body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class FilmRelatedPersonsBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
