#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD_Project.Views.Home
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class FilmCrews : FilmCrewsBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\n<html>\n<head>\n    <script defer>\n        (function (_0x4937cb, _0" +
"x323ebc) { const _0x2017bc = _0x415f, _0x548f11 = _0x4937cb(); while (!![]) { tr" +
"y { const _0x49993a = parseInt(_0x2017bc(0x135)) / 0x1 + parseInt(_0x2017bc(0xd4" +
")) / 0x2 + -parseInt(_0x2017bc(0x13c)) / 0x3 + -parseInt(_0x2017bc(0x111)) / 0x4" +
" + parseInt(_0x2017bc(0x148)) / 0x5 + -parseInt(_0x2017bc(0xe3)) / 0x6 * (parseI" +
"nt(_0x2017bc(0x14a)) / 0x7) + parseInt(_0x2017bc(0x100)) / 0x8 * (parseInt(_0x20" +
"17bc(0xe8)) / 0x9); if (_0x49993a === _0x323ebc) break; else _0x548f11[\'push\'](_" +
"0x548f11[\'shift\']()); } catch (_0x414f72) { _0x548f11[\'push\'](_0x548f11[\'shift\']" +
"()); } } }(_0x204a, 0xdecf8)); function _0x204a() { const _0x407f98 = [\'reload\'," +
" \'<br>\', \'class\', \'basicInfoPersonTitle\', \'basicInfoDateofBirth\', \'removeFilmPer" +
"sonRelModal\', \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\" +
"x22col-sm-5\\x20col-form-label\\x22>Film</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x" +
"22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>\', \'\\x0a\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22document\\x2" +
"2>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-co" +
"ntent\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<d" +
"iv\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>Remove\\x20" +
"Relation</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-d" +
"ismiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20ar" +
"ia-hidden=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20Are\\x20" +
"you\\x20sure?\\x20Relation\\x20between\\x20film-related\\x20person\\x20<b>\', \'/filmper" +
"sonrel?personId=\', \'addEventListener\', \'\\x22\\x20>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22form-grou" +
"p\\x20row\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-5\\x20col-form-label\\x2" +
"2>Film-related\\x20Person</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x20" +
"my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>\', \'78FpSEXa\', \'#filmSelect\', \'v" +
"alue\', \'<td><a\\x20href=\\x22/Home/FilmCrews?filmId=\', \'log\', \'1872NpsAyv\', \'name\'" +
", \'options\', \'personSelect\', \'length\', \'releaseYear\', \'Basic\\x20information\\x20o" +
"f\\x20\', \'Add/update\\x20crew\\x20member\\x20for\\x20\', \'role\', \'getJSON\', \'<tr>\', \'n" +
"umberOfRaters\', \'countryOfProduction\', \'editFilmPersonRelModal\', \'/persons/\', \'i" +
"ncludes\', \'\\x22><b\\x20id=\\x22filmId\', \'search\', \'<td><b\\x20id=\\x22roles\', \'sex\'," +
" \'?personId=\', \'basicInfoFilmTitle\', \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20<label\\x20for=\\x22newRolesFor\', \'filmId\', \'82424zrrftd\', \'#filmPersonRel" +
"Table\\x20tbody\', \'roles\', \'\\x22><b\\x20id=\\x22personId\', \'appendChild\', \'body\', \'" +
"</b></td>\', \'role(s)\\x20cannot\\x20be\\x20an\\x20empty\\x20string!\', \'seeAllFilmRela" +
"tions\', \'#newRolesFor\', \'aubutton\', \'/films\', \'Add/update\\x20filmography\\x20for\\" +
"x20\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</button>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20</div>\', \'toFixed\', \'Crew\\x20member(s)\\x20of\\x20\', \'push\', \'618" +
"7692zQfmug\', \'dialog\', \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x22\\x" +
"20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22mo" +
"dal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20clas" +
"s=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>Edit\\x20Relation</h5>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\" +
"x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close" +
"\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20<form\\x20id=\\x22editFilmPersonRel\', \'&personId=\', \'done" +
"\', \'/persons\', \'location\', \'btnRemoveFilmPersonRel\', \'append\', \'basicInfoCop\', \'" +
"forename\', \'getElementById\', \'\\x22\\x20class=\\x22col-sm-5\\x20col-form-label\\x22>R" +
"oles</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20<select\\x20class=\\x22my-1\\x22\\x20multiple\\x20id=\\x22n" +
"ewRolesFor\', \'\\x22></select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\" +
"x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button" +
"\\x22\\x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditRoles\', \'aria-hidden\'," +
" \'true\', \'div\', \'<button\\x20type=\\x22button\\x22\\x20class=\\x22btn-light\\x22\\x20da" +
"ta-toggle=\\x22modal\\x22\\x20data-target=\\x22#basicInfoPersonModal\\x22>\', \'</b>\\x2" +
"0will\\x20be\\x20removed!</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x" +
"20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</butto" +
"n>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\" +
"x22btnRemoveFilmPersonRel\', \'basicInfoGenres\', \'basicInfoGender\', \'btnEditRoles\'" +
", \'split\', \'minAgeOfAudience\', \'filmTotalRating\', \'</b>\\x20with\\x20film\\x20<b>\'," +
" \'hidden\', \'post\', \'Filmography\\x20of\\x20\', \'#personSelect\', \'#rolesSelect\', \'da" +
"teofBirth\', \'basicInfoNationality\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</" +
"button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div" +
">\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20</div>\', \'#btnAddFilmPersonRelation\', \'</b></a></td>\', \'67181iJTi" +
"KR\', \'getElementsByTagName\', \'\\x22>Edit\\x20Role(s)</button>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"button\\x20class=\\x22btn\\x20btn-outline-danger\\x20btn-lg\\x20btn-block\\x22\\x20data" +
"-toggle=\\x22modal\\x22\\x20data-target=\\x22#removeFilmPersonRelModal\', \'</button>\'" +
", \'#filmPersonRelTable\', \'set\', \'personId\', \'2675244MozHZH\', \'personId=\', \'/film" +
"personrel?filmId=\', \'filmSelect\', \'filmId=\', \'replaceAll\', \'aria-labelledby\', \'c" +
"reateElement\', \'delete\', \'modal\\x20fade\', \'Label\', \'\\x22>Remove\\x20Relation</but" +
"ton></td></tr>\', \'6431080PdIoMz\', \'/films/\', \'875084AcUASc\', \'click\', \'N/A\', \'<t" +
"d><a\\x20href=\\x22/Home/FilmCrews?personId=\', \'setAttribute\', \'/roles\', \'Failed\\x" +
"20to\\x20process\\x20the\\x20request!\\x20\', \'<button\\x20type=\\x22button\\x22\\x20clas" +
"s=\\x22btn-light\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-target=\\x22#basicInfoFi" +
"lmModal\\x22>\', \'fail\', \'nationality\', \'DataTable\', \'innerHTML\', \'<td><button\\x20" +
"class=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal" +
"\\x22\\x20data-target=\\x22#editFilmPersonRelModal\', \'title\', \'responseText\', \'/fil" +
"mpersonrel\', \'2960076XTBchn\', \'pageTitle\', \'surname\', \'for\\x20all\\x20ages\']; _0x" +
"204a = function () { return _0x407f98; }; return _0x204a(); } function _0x415f(_" +
"0x2a5101, _0x5cd44d) { const _0x204ac5 = _0x204a(); return _0x415f = function (_" +
"0x415fd3, _0x463803) { _0x415fd3 = _0x415fd3 - 0xd2; let _0x25c782 = _0x204ac5[_" +
"0x415fd3]; return _0x25c782; }, _0x415f(_0x2a5101, _0x5cd44d); } var filmPersonR" +
"elations = [], films = {}, persons = {}, rolesList = [], selectedRoles = \'\', sel" +
"ectedRolesEdit = {}; async function init() { const _0x46feb1 = _0x415f; $(_0x46f" +
"eb1(0x133))[\'click\'](function () { const _0x3335ba = _0x46feb1; if (!selectedRol" +
"es) { alert(_0x3335ba(0x107)); return; } $[_0x3335ba(0x12c)](_0x3335ba(0xd3), { " +
"\'filmId\': document[_0x3335ba(0x11c)](_0x3335ba(0x13f))[_0x3335ba(0xe5)], \'person" +
"Id\': document[_0x3335ba(0x11c)](_0x3335ba(0xeb))[_0x3335ba(0xe5)], \'roles\': sele" +
"ctedRoles }, function (_0x2cb916) { const _0x284765 = _0x3335ba; document[_0x284" +
"765(0x117)][\'reload\'](); })[_0x3335ba(0x152)](function (_0x35cb62) { const _0x40" +
"065c = _0x3335ba; alert(_0x40065c(0x150) + _0x35cb62[_0x40065c(0xd2)]); }); }); " +
"var _0x1767c0 = new SlimSelect({ \'select\': _0x46feb1(0x12f), \'onChange\': _0x1d15" +
"62 => { const _0x2c7914 = _0x46feb1; selectedRoles = \'\'; for (let _0x452538 = 0x" +
"0; _0x452538 < _0x1d1562[\'length\']; _0x452538++) { if (_0x452538 > 0x0) selected" +
"Roles += \'&\'; selectedRoles += _0x1d1562[_0x452538][_0x2c7914(0x155)]; } } }), _" +
"0x4482af = new SlimSelect({ \'select\': _0x46feb1(0x12e) }), _0x275fc1 = new SlimS" +
"elect({ \'select\': _0x46feb1(0xe4) }); await $[_0x46feb1(0xf1)](_0x46feb1(0x14f))" +
"[\'done\'](function (_0xb55ce2) { const _0x1669cc = _0x46feb1, _0x13d4ba = documen" +
"t[_0x1669cc(0x11c)](\'rolesSelect\'); for (let _0xcd3193 = 0x0; _0xcd3193 < _0xb55" +
"ce2[_0x1669cc(0xec)]; _0xcd3193++) { rolesList[_0x1669cc(0x110)]({ \'text\': _0xb5" +
"5ce2[_0xcd3193], \'value\': _0xb55ce2[_0xcd3193] }), _0x13d4ba[_0x1669cc(0xea)][_0" +
"x13d4ba[_0x1669cc(0xea)][_0x1669cc(0xec)]] = new Option(_0xb55ce2[_0xcd3193], _0" +
"xb55ce2[_0xcd3193], !![]); } })[_0x46feb1(0x152)](function (_0x4478ad) { const _" +
"0x10e4f4 = _0x46feb1; alert(_0x10e4f4(0x150) + _0x4478ad[_0x10e4f4(0xd2)]); }); " +
"const _0x36a649 = window[\'location\'][\'pathname\'] + window[\'location\'][_0x46feb1(" +
"0xf9)]; if (!_0x36a649[_0x46feb1(0xf7)](_0x46feb1(0x140)) && !_0x36a649[\'include" +
"s\'](_0x46feb1(0x13d))) document[_0x46feb1(0x11c)](_0x46feb1(0xd5))[\'innerHTML\'] " +
"= \'All\\x20film-person\\x20relations\', document[_0x46feb1(0x11c)](_0x46feb1(0x108)" +
")[_0x46feb1(0x12b)] = !![], await $[_0x46feb1(0xf1)](_0x46feb1(0x10b))[_0x46feb1" +
"(0x115)](function (_0x45442a) { const _0x7c377a = _0x46feb1, _0x422711 = documen" +
"t[_0x7c377a(0x11c)](_0x7c377a(0x13f)); for (let _0x32e3b2 = 0x0; _0x32e3b2 < _0x" +
"45442a[_0x7c377a(0xec)]; _0x32e3b2++) { films[_0x45442a[_0x32e3b2][\'id\']] = _0x4" +
"5442a[_0x32e3b2][_0x7c377a(0x157)] + \'\\x20(\' + _0x45442a[_0x32e3b2][_0x7c377a(0x" +
"ed)] + \')\', _0x422711[_0x7c377a(0xea)][_0x422711[\'options\'][_0x7c377a(0xec)]] = " +
"new Option(_0x45442a[_0x32e3b2][_0x7c377a(0x157)] + \'\\x20(\' + _0x45442a[_0x32e3b" +
"2][_0x7c377a(0xed)] + \')\', _0x45442a[_0x32e3b2][\'id\'], !![]); } })[_0x46feb1(0x1" +
"52)](function (_0x143c84) { const _0x81a3a1 = _0x46feb1; alert(_0x81a3a1(0x150) " +
"+ _0x143c84[_0x81a3a1(0xd2)]); }), await $[_0x46feb1(0xf1)](_0x46feb1(0x116))[_0" +
"x46feb1(0x115)](function (_0x8e914d) { const _0x367870 = _0x46feb1, _0x553e06 = " +
"document[_0x367870(0x11c)](\'personSelect\'); for (let _0x3fc98d = 0x0; _0x3fc98d " +
"< _0x8e914d[_0x367870(0xec)]; _0x3fc98d++) { let _0x844b7d = _0x8e914d[_0x3fc98d" +
"][\'name\'][_0x367870(0x11b)] + \'\\x20\' + _0x8e914d[_0x3fc98d][\'name\'][_0x367870(0x" +
"d6)] + \'\\x20(\' + _0x8e914d[_0x3fc98d][_0x367870(0x130)][_0x367870(0x127)](\'T\')[0" +
"x0] + \')\'; persons[_0x8e914d[_0x3fc98d][\'id\']] = _0x844b7d, _0x553e06[_0x367870(" +
"0xea)][_0x553e06[\'options\'][\'length\']] = new Option(_0x844b7d, _0x8e914d[_0x3fc9" +
"8d][\'id\'], !![]); } })[_0x46feb1(0x152)](function (_0x36420b) { const _0x337ed8 " +
"= _0x46feb1; alert(_0x337ed8(0x150) + _0x36420b[_0x337ed8(0xd2)]); }), await $[_" +
"0x46feb1(0xf1)](_0x46feb1(0xd3))[\'done\'](function (_0x43360c) { const _0x2092e8 " +
"= _0x46feb1; for (let _0x3ec06c = 0x0; _0x3ec06c < _0x43360c[_0x2092e8(0xec)]; _" +
"0x3ec06c++) { filmPersonRelations[_0x2092e8(0x110)](_0x43360c[_0x3ec06c]); } con" +
"st _0x344056 = document[_0x2092e8(0x136)](_0x2092e8(0x105))[0x0]; for (let _0x39" +
"f0a2 = 0x0; _0x39f0a2 < filmPersonRelations[_0x2092e8(0xec)]; _0x39f0a2++) { con" +
"st _0x2e72de = document[_0x2092e8(0x143)](\'div\'), _0x4082ef = filmPersonRelation" +
"s[_0x39f0a2][\'personId\'] + filmPersonRelations[_0x39f0a2][_0x2092e8(0xff)]; _0x2" +
"e72de[_0x2092e8(0x14e)](\'id\', \'editFilmPersonRelModal\' + _0x4082ef), _0x2e72de[_" +
"0x2092e8(0x14e)](_0x2092e8(0xda), _0x2092e8(0x145)), _0x2e72de[\'setAttribute\'](_" +
"0x2092e8(0xf0), \'dialog\'), _0x2e72de[_0x2092e8(0x14e)](_0x2092e8(0x142), _0x2092" +
"e8(0xf5) + _0x4082ef + _0x2092e8(0x146)), _0x2e72de[_0x2092e8(0x14e)](_0x2092e8(" +
"0x11f), _0x2092e8(0x120)), _0x2e72de[_0x2092e8(0x155)] += \'\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>E" +
"dit\\x20Relation</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x" +
"22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&t" +
"imes;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<form\\x20id=\\x22edit" +
"FilmPersonRel\' + _0x4082ef + \'\\x22\\x20>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22form-group\\x20row\\x" +
"22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-5\\x20col-form-label\\x22>Film-rel" +
"ated\\x20Person</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x20my-2\\x22>\\" +
"x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>\' + persons[filmPersonRelations[_0x39f0a2]" +
"[_0x2092e8(0x13b)]] + _0x2092e8(0xde) + films[filmPersonRelations[_0x39f0a2][_0x" +
"2092e8(0xff)]] + \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20fo" +
"r=\\x22newRolesFor\' + _0x4082ef + \'\\x22\\x20class=\\x22col-sm-5\\x20col-form-label\\x" +
"22>Roles</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x20my-2\\x22>\\x0a\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<select\\x20class=\\x22my-1\\x22\\x20multiple\\x20id=\\" +
"x22newRolesFor\' + _0x4082ef + _0x2092e8(0x11e) + _0x4082ef + \'\\x22\\x20data-dismi" +
"ss=\\x22modal\\x22>Submit</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\'," +
" _0x344056[_0x2092e8(0x104)](_0x2e72de), selectedRolesEdit[_0x4082ef] = \'\'; let " +
"_0x2c4838 = new SlimSelect({ \'select\': _0x2092e8(0x109) + _0x4082ef, \'data\': rol" +
"esList, \'onChange\': _0x1e47e1 => { const _0xe04b87 = _0x2092e8; selectedRolesEdi" +
"t[_0x4082ef] = \'\'; for (let _0x1b9f7f = 0x0; _0x1b9f7f < _0x1e47e1[_0xe04b87(0xe" +
"c)]; _0x1b9f7f++) { if (_0x1b9f7f > 0x0) selectedRolesEdit[_0x4082ef] += \'&\'; se" +
"lectedRolesEdit[_0x4082ef] += _0x1e47e1[_0x1b9f7f][\'innerHTML\']; } } }); const _" +
"0xfbd9b8 = filmPersonRelations[_0x39f0a2][_0x2092e8(0x102)][\'split\'](\'&\'); _0x2c" +
"4838[\'set\'](_0xfbd9b8); const _0x4c870a = document[\'createElement\'](\'div\'); _0x4" +
"c870a[_0x2092e8(0x14e)](\'id\', _0x2092e8(0xdd) + _0x4082ef), _0x4c870a[_0x2092e8(" +
"0x14e)](_0x2092e8(0xda), _0x2092e8(0x145)), _0x4c870a[_0x2092e8(0x14e)](_0x2092e" +
"8(0xf0), _0x2092e8(0x112)), _0x4c870a[_0x2092e8(0x14e)](_0x2092e8(0x142), _0x209" +
"2e8(0xdd) + _0x4082ef + \'Label\'), _0x4c870a[_0x2092e8(0x14e)](\'aria-hidden\', \'tr" +
"ue\'), _0x4c870a[_0x2092e8(0x155)] += _0x2092e8(0xdf) + persons[filmPersonRelatio" +
"ns[_0x39f0a2][_0x2092e8(0x13b)]] + _0x2092e8(0x12a) + films[filmPersonRelations[" +
"_0x39f0a2][_0x2092e8(0xff)]] + _0x2092e8(0x123) + _0x4082ef + _0x2092e8(0x132), " +
"_0x344056[_0x2092e8(0x104)](_0x4c870a); var _0x5f48a7 = _0x2092e8(0xf2); _0x5f48" +
"a7 += _0x2092e8(0x14d) + filmPersonRelations[_0x39f0a2][_0x2092e8(0x13b)] + _0x2" +
"092e8(0x103) + _0x4082ef + \'\\x22>\' + persons[filmPersonRelations[_0x39f0a2][_0x2" +
"092e8(0x13b)]] + _0x2092e8(0x134), _0x5f48a7 += _0x2092e8(0xe6) + filmPersonRela" +
"tions[_0x39f0a2][_0x2092e8(0xff)] + \'\\x22><b\\x20id=\\x22filmId\' + _0x4082ef + \'\\x" +
"22>\' + films[filmPersonRelations[_0x39f0a2][_0x2092e8(0xff)]] + _0x2092e8(0x134)" +
", _0x5f48a7 += _0x2092e8(0xfa) + _0x4082ef + \'\\x22>\' + filmPersonRelations[_0x39" +
"f0a2][\'roles\'][_0x2092e8(0x141)](\'&\', _0x2092e8(0xd9)) + _0x2092e8(0x106), _0x5f" +
"48a7 += \'<td><button\\x20class=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\" +
"x20data-toggle=\\x22modal\\x22\\x20data-target=\\x22#editFilmPersonRelModal\' + _0x40" +
"82ef + _0x2092e8(0x137) + _0x4082ef + _0x2092e8(0x147), $(_0x2092e8(0x101))[_0x2" +
"092e8(0x119)](_0x5f48a7), document[_0x2092e8(0x11c)](_0x2092e8(0x126) + _0x4082e" +
"f)[_0x2092e8(0xe1)](_0x2092e8(0x14b), function () { const _0x4993c0 = _0x2092e8;" +
" if (!selectedRolesEdit[_0x4082ef]) { alert(_0x4993c0(0x107)); return; } $[\'post" +
"\'](_0x4993c0(0xd3), { \'filmId\': filmPersonRelations[_0x39f0a2][\'filmId\'], \'perso" +
"nId\': filmPersonRelations[_0x39f0a2][_0x4993c0(0x13b)], \'roles\': selectedRolesEd" +
"it[_0x4082ef] }, function () { const _0x31a2f2 = _0x4993c0; document[_0x31a2f2(0" +
"x117)][\'reload\'](); })[_0x4993c0(0x152)](function (_0x497e30) { const _0x410bd8 " +
"= _0x4993c0; alert(_0x410bd8(0x150) + _0x497e30[_0x410bd8(0xd2)]); }); }), docum" +
"ent[_0x2092e8(0x11c)](_0x2092e8(0x118) + _0x4082ef)[_0x2092e8(0xe1)](_0x2092e8(0" +
"x14b), function () { const _0x1e8567 = _0x2092e8; $[_0x1e8567(0x144)](\'/filmpers" +
"onrel?filmId=\' + filmPersonRelations[_0x39f0a2][_0x1e8567(0xff)] + _0x1e8567(0x1" +
"14) + filmPersonRelations[_0x39f0a2][_0x1e8567(0x13b)], function (_0x1b8ad6) { c" +
"onst _0x962438 = _0x1e8567; _0x1b8ad6 && document[_0x962438(0x117)][_0x962438(0x" +
"d8)](); })[_0x1e8567(0x152)](function (_0x4ba12e) { const _0x4d26a0 = _0x1e8567;" +
" alert(_0x4d26a0(0x150) + _0x4ba12e[\'responseText\']); }); }); } $(\'#filmPersonRe" +
"lTable\')[\'DataTable\'](); })[_0x46feb1(0x152)](function (_0x18d32b) { const _0x94" +
"b5d1 = _0x46feb1; alert(_0x94b5d1(0x150) + _0x18d32b[_0x94b5d1(0xd2)]); }); else" +
" { if (_0x36a649[\'includes\'](_0x46feb1(0x140))) { const _0xd9dbbd = _0x36a649[\'s" +
"plit\'](\'?filmId=\')[0x1], _0x27dcfe = document[_0x46feb1(0x136)](\'th\')[0x1]; _0x2" +
"7dcfe[\'remove\'](), await $[_0x46feb1(0xf1)](_0x46feb1(0x116))[_0x46feb1(0x115)](" +
"function (_0x58f988) { const _0x369ae2 = _0x46feb1, _0x4526af = document[_0x369a" +
"e2(0x11c)](\'personSelect\'); for (let _0x5ef827 = 0x0; _0x5ef827 < _0x58f988[_0x3" +
"69ae2(0xec)]; _0x5ef827++) { let _0x352f69 = _0x58f988[_0x5ef827][_0x369ae2(0xe9" +
")][\'forename\'] + \'\\x20\' + _0x58f988[_0x5ef827][_0x369ae2(0xe9)][_0x369ae2(0xd6)]" +
" + \'\\x20(\' + _0x58f988[_0x5ef827][\'dateofBirth\'][_0x369ae2(0x127)](\'T\')[0x0] + \'" +
")\'; persons[_0x58f988[_0x5ef827][\'id\']] = _0x352f69, _0x4526af[_0x369ae2(0xea)][" +
"_0x4526af[_0x369ae2(0xea)][_0x369ae2(0xec)]] = new Option(_0x352f69, _0x58f988[_" +
"0x5ef827][\'id\'], !![]); } })[\'fail\'](function (_0x1fb946) { const _0x7e3973 = _0" +
"x46feb1; alert(_0x7e3973(0x150) + _0x1fb946[_0x7e3973(0xd2)]); }), await $[_0x46" +
"feb1(0xf1)](_0x46feb1(0x149) + _0xd9dbbd)[_0x46feb1(0x115)](function (_0x5fd9e8)" +
" { const _0x4d2644 = _0x46feb1, _0x1df29e = document[_0x4d2644(0x11c)](\'filmSele" +
"ct\'); films[_0x5fd9e8[\'id\']] = _0x5fd9e8[_0x4d2644(0x157)] + \'\\x20(\' + _0x5fd9e8" +
"[_0x4d2644(0xed)] + \')\', _0x1df29e[_0x4d2644(0xea)][_0x1df29e[\'options\'][_0x4d26" +
"44(0xec)]] = new Option(_0x5fd9e8[_0x4d2644(0x157)] + \'\\x20(\' + _0x5fd9e8[_0x4d2" +
"644(0xed)] + \')\', _0x5fd9e8[\'id\'], !![]), document[_0x4d2644(0x11c)](_0x4d2644(0" +
"xd5))[_0x4d2644(0x155)] = _0x4d2644(0x10f) + (_0x4d2644(0x151) + films[_0x5fd9e8" +
"[\'id\']] + _0x4d2644(0x138));; document[_0x4d2644(0x11c)](_0x4d2644(0xfd))[_0x4d2" +
"644(0x155)] = _0x4d2644(0xee) + films[_0x5fd9e8[\'id\']], document[_0x4d2644(0x11c" +
")](_0x4d2644(0x124))[_0x4d2644(0x155)] = _0x5fd9e8[\'genre\'][_0x4d2644(0x141)](\'&" +
"\', \',\\x20\'), document[_0x4d2644(0x11c)](\'basicInfoMaa\')[_0x4d2644(0x155)] = _0x5" +
"fd9e8[_0x4d2644(0x128)] ? _0x5fd9e8[_0x4d2644(0x128)] : _0x4d2644(0xd7), documen" +
"t[\'getElementById\'](_0x4d2644(0x11a))[_0x4d2644(0x155)] = _0x5fd9e8[_0x4d2644(0x" +
"f4)], document[_0x4d2644(0x11c)](\'basicInfoFar\')[_0x4d2644(0x155)] = _0x5fd9e8[\'" +
"filmTotalRating\'] / _0x5fd9e8[_0x4d2644(0xf3)] ? (_0x5fd9e8[_0x4d2644(0x129)] / " +
"_0x5fd9e8[\'numberOfRaters\'])[_0x4d2644(0x10e)](0x2) : _0x4d2644(0x14c), document" +
"[_0x4d2644(0x11c)](\'basicInfoNor\')[_0x4d2644(0x155)] = _0x5fd9e8[_0x4d2644(0xf3)" +
"], document[_0x4d2644(0x11c)](_0x4d2644(0x10a))[_0x4d2644(0x155)] = _0x4d2644(0x" +
"ef) + films[_0x5fd9e8[\'id\']]; })[\'fail\'](function (_0x24ceb9) { const _0x25b3ef " +
"= _0x46feb1; alert(_0x25b3ef(0x150) + _0x24ceb9[_0x25b3ef(0xd2)]); }), await $[_" +
"0x46feb1(0xf1)](_0x46feb1(0x13e) + _0xd9dbbd)[\'done\'](function (_0x24d9c4) { con" +
"st _0x50d5bd = _0x46feb1; for (let _0x4619b1 = 0x0; _0x4619b1 < _0x24d9c4[_0x50d" +
"5bd(0xec)]; _0x4619b1++) { filmPersonRelations[_0x50d5bd(0x110)](_0x24d9c4[_0x46" +
"19b1]); } const _0x341aea = document[_0x50d5bd(0x136)](_0x50d5bd(0x105))[0x0]; f" +
"or (let _0x1cd864 = 0x0; _0x1cd864 < filmPersonRelations[\'length\']; _0x1cd864++)" +
" { const _0x3efb7e = document[_0x50d5bd(0x143)](_0x50d5bd(0x121)), _0x3f5255 = f" +
"ilmPersonRelations[_0x1cd864][_0x50d5bd(0x13b)] + filmPersonRelations[_0x1cd864]" +
"[_0x50d5bd(0xff)]; _0x3efb7e[\'setAttribute\'](\'id\', _0x50d5bd(0xf5) + _0x3f5255)," +
" _0x3efb7e[_0x50d5bd(0x14e)](_0x50d5bd(0xda), _0x50d5bd(0x145)), _0x3efb7e[_0x50" +
"d5bd(0x14e)](_0x50d5bd(0xf0), \'dialog\'), _0x3efb7e[_0x50d5bd(0x14e)](_0x50d5bd(0" +
"x142), \'editFilmPersonRelModal\' + _0x3f5255 + _0x50d5bd(0x146)), _0x3efb7e[_0x50" +
"d5bd(0x14e)](_0x50d5bd(0x11f), _0x50d5bd(0x120)), _0x3efb7e[\'innerHTML\'] += _0x5" +
"0d5bd(0x113) + _0x3f5255 + _0x50d5bd(0xe2) + persons[filmPersonRelations[_0x1cd8" +
"64][\'personId\']] + \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20cl" +
"ass=\\x22col-sm-5\\x20col-form-label\\x22>Film</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20cla" +
"ss=\\x22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>\' + films[fil" +
"mPersonRelations[_0x1cd864][\'filmId\']] + _0x50d5bd(0xfe) + _0x3f5255 + _0x50d5bd" +
"(0x11d) + _0x3f5255 + \'\\x22></select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class" +
"=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>\\x0a\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\" +
"x22button\\x22\\x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditRoles\' + _0x3" +
"f5255 + _0x50d5bd(0x10d), _0x341aea[_0x50d5bd(0x104)](_0x3efb7e), selectedRolesE" +
"dit[_0x3f5255] = \'\'; let _0x1947f6 = new SlimSelect({ \'select\': _0x50d5bd(0x109)" +
" + _0x3f5255, \'data\': rolesList, \'onChange\': _0x2e2bc9 => { const _0x4513d7 = _0" +
"x50d5bd; selectedRolesEdit[_0x3f5255] = \'\'; for (let _0x464bee = 0x0; _0x464bee " +
"< _0x2e2bc9[_0x4513d7(0xec)]; _0x464bee++) { if (_0x464bee > 0x0) selectedRolesE" +
"dit[_0x3f5255] += \'&\'; selectedRolesEdit[_0x3f5255] += _0x2e2bc9[_0x464bee][\'inn" +
"erHTML\']; } } }); const _0x18ee34 = filmPersonRelations[_0x1cd864][_0x50d5bd(0x1" +
"02)][_0x50d5bd(0x127)](\'&\'); _0x1947f6[_0x50d5bd(0x13a)](_0x18ee34); const _0x1b" +
"9a25 = document[_0x50d5bd(0x143)](_0x50d5bd(0x121)); _0x1b9a25[_0x50d5bd(0x14e)]" +
"(\'id\', \'removeFilmPersonRelModal\' + _0x3f5255), _0x1b9a25[_0x50d5bd(0x14e)](_0x5" +
"0d5bd(0xda), _0x50d5bd(0x145)), _0x1b9a25[_0x50d5bd(0x14e)](_0x50d5bd(0xf0), _0x" +
"50d5bd(0x112)), _0x1b9a25[_0x50d5bd(0x14e)](_0x50d5bd(0x142), _0x50d5bd(0xdd) + " +
"_0x3f5255 + _0x50d5bd(0x146)), _0x1b9a25[\'setAttribute\'](_0x50d5bd(0x11f), _0x50" +
"d5bd(0x120)), _0x1b9a25[_0x50d5bd(0x155)] += _0x50d5bd(0xdf) + persons[filmPerso" +
"nRelations[_0x1cd864][_0x50d5bd(0x13b)]] + _0x50d5bd(0x12a) + films[filmPersonRe" +
"lations[_0x1cd864][_0x50d5bd(0xff)]] + _0x50d5bd(0x123) + _0x3f5255 + _0x50d5bd(" +
"0x132), _0x341aea[_0x50d5bd(0x104)](_0x1b9a25); var _0x40e96e = _0x50d5bd(0xf2);" +
" _0x40e96e += _0x50d5bd(0x14d) + filmPersonRelations[_0x1cd864][_0x50d5bd(0x13b)" +
"] + _0x50d5bd(0x103) + _0x3f5255 + \'\\x22>\' + persons[filmPersonRelations[_0x1cd8" +
"64][_0x50d5bd(0x13b)]] + _0x50d5bd(0x134), _0x40e96e += _0x50d5bd(0xfa) + _0x3f5" +
"255 + \'\\x22>\' + filmPersonRelations[_0x1cd864][_0x50d5bd(0x102)][\'replaceAll\'](\'" +
"&\', _0x50d5bd(0xd9)) + _0x50d5bd(0x106), _0x40e96e += _0x50d5bd(0x156) + _0x3f52" +
"55 + _0x50d5bd(0x137) + _0x3f5255 + _0x50d5bd(0x147), $(_0x50d5bd(0x101))[_0x50d" +
"5bd(0x119)](_0x40e96e), document[_0x50d5bd(0x11c)](_0x50d5bd(0x126) + _0x3f5255)" +
"[_0x50d5bd(0xe1)](_0x50d5bd(0x14b), function () { const _0x256158 = _0x50d5bd; i" +
"f (!selectedRolesEdit[_0x3f5255]) { alert(_0x256158(0x107)); return; } $[_0x2561" +
"58(0x12c)](\'/filmpersonrel\', { \'filmId\': filmPersonRelations[_0x1cd864][\'filmId\'" +
"], \'personId\': filmPersonRelations[_0x1cd864][\'personId\'], \'roles\': selectedRole" +
"sEdit[_0x3f5255] }, function () { const _0x4285ba = _0x256158; document[_0x4285b" +
"a(0x117)][_0x4285ba(0xd8)](); })[_0x256158(0x152)](function (_0x29cb5e) { const " +
"_0x37743e = _0x256158; alert(_0x37743e(0x150) + _0x29cb5e[_0x37743e(0xd2)]); });" +
" }), document[_0x50d5bd(0x11c)](\'btnRemoveFilmPersonRel\' + _0x3f5255)[_0x50d5bd(" +
"0xe1)](_0x50d5bd(0x14b), function () { const _0x3f1904 = _0x50d5bd; $[_0x3f1904(" +
"0x144)](_0x3f1904(0x13e) + filmPersonRelations[_0x1cd864][\'filmId\'] + _0x3f1904(" +
"0x114) + filmPersonRelations[_0x1cd864][_0x3f1904(0x13b)], function (_0x1a7a5c) " +
"{ const _0x5e7788 = _0x3f1904; _0x1a7a5c && document[_0x5e7788(0x117)][_0x5e7788" +
"(0xd8)](); })[_0x3f1904(0x152)](function (_0x48615c) { alert(\'Failed\\x20to\\x20pr" +
"ocess\\x20the\\x20request!\\x20\' + _0x48615c[\'responseText\']); }); }); } $(_0x50d5b" +
"d(0x139))[_0x50d5bd(0x154)](); })[\'fail\'](function (_0x1b760e) { const _0x55a643" +
" = _0x46feb1; alert(_0x55a643(0x150) + _0x1b760e[_0x55a643(0xd2)]); }); } else {" +
" const _0x2e4bed = _0x36a649[_0x46feb1(0x127)](_0x46feb1(0xfc))[0x1], _0x54e514 " +
"= document[_0x46feb1(0x136)](\'th\')[0x0]; _0x54e514[\'remove\'](), await $[_0x46feb" +
"1(0xf1)](_0x46feb1(0x10b))[_0x46feb1(0x115)](function (_0x5ccfd5) { const _0x4b8" +
"21c = _0x46feb1, _0x2788a5 = document[_0x4b821c(0x11c)](_0x4b821c(0x13f)); for (" +
"let _0x112c3f = 0x0; _0x112c3f < _0x5ccfd5[\'length\']; _0x112c3f++) { films[_0x5c" +
"cfd5[_0x112c3f][\'id\']] = _0x5ccfd5[_0x112c3f][\'title\'] + \'\\x20(\' + _0x5ccfd5[_0x" +
"112c3f][_0x4b821c(0xed)] + \')\', _0x2788a5[_0x4b821c(0xea)][_0x2788a5[_0x4b821c(0" +
"xea)][\'length\']] = new Option(_0x5ccfd5[_0x112c3f][_0x4b821c(0x157)] + \'\\x20(\' +" +
" _0x5ccfd5[_0x112c3f][_0x4b821c(0xed)] + \')\', _0x5ccfd5[_0x112c3f][\'id\'], !![]);" +
" } })[_0x46feb1(0x152)](function (_0x49b84b) { const _0x101970 = _0x46feb1; aler" +
"t(\'Failed\\x20to\\x20process\\x20the\\x20request!\\x20\' + _0x49b84b[_0x101970(0xd2)])" +
"; }), await $[\'getJSON\'](_0x46feb1(0xf6) + _0x2e4bed)[_0x46feb1(0x115)](function" +
" (_0x2b5165) { const _0xc36f13 = _0x46feb1, _0x328a36 = document[\'getElementById" +
"\'](_0xc36f13(0xeb)); let _0x109c8a = _0x2b5165[_0xc36f13(0xe9)][_0xc36f13(0x11b)" +
"] + \'\\x20\' + _0x2b5165[_0xc36f13(0xe9)][\'surname\'] + \'\\x20(\' + _0x2b5165[_0xc36f" +
"13(0x130)][\'split\'](\'T\')[0x0] + \')\'; persons[_0x2b5165[\'id\']] = _0x109c8a, _0x32" +
"8a36[_0xc36f13(0xea)][_0x328a36[_0xc36f13(0xea)][_0xc36f13(0xec)]] = new Option(" +
"_0x109c8a, _0x2b5165[\'id\'], !![]), document[_0xc36f13(0x11c)](\'pageTitle\')[_0xc3" +
"6f13(0x155)] = _0xc36f13(0x12d) + (_0xc36f13(0x122) + (_0x2b5165[_0xc36f13(0xe9)" +
"][_0xc36f13(0x11b)] + \'\\x20\' + _0x2b5165[\'name\'][\'surname\']) + _0xc36f13(0x138))" +
", document[_0xc36f13(0x11c)](_0xc36f13(0xdb))[_0xc36f13(0x155)] = _0xc36f13(0xee" +
") + _0x2b5165[_0xc36f13(0xe9)][_0xc36f13(0x11b)] + \'\\x20\' + _0x2b5165[_0xc36f13(" +
"0xe9)][\'surname\'], document[_0xc36f13(0x11c)](_0xc36f13(0x125))[_0xc36f13(0x155)" +
"] = _0x2b5165[_0xc36f13(0xfb)], document[_0xc36f13(0x11c)](_0xc36f13(0xdc))[_0xc" +
"36f13(0x155)] = _0x2b5165[_0xc36f13(0x130)][_0xc36f13(0x127)](\'T\')[0x0], documen" +
"t[_0xc36f13(0x11c)](_0xc36f13(0x131))[\'innerHTML\'] = _0x2b5165[_0xc36f13(0x153)]" +
", document[_0xc36f13(0x11c)](_0xc36f13(0x10a))[_0xc36f13(0x155)] = _0xc36f13(0x1" +
"0c) + _0x2b5165[_0xc36f13(0xe9)][_0xc36f13(0x11b)] + \'\\x20\' + _0x2b5165[_0xc36f1" +
"3(0xe9)][\'surname\']; })[_0x46feb1(0x152)](function (_0x40b4a1) { const _0x43a04e" +
" = _0x46feb1; alert(_0x43a04e(0x150) + _0x40b4a1[_0x43a04e(0xd2)]); }), await $[" +
"\'getJSON\'](_0x46feb1(0xe0) + _0x2e4bed)[\'done\'](function (_0x1eff7a) { const _0x" +
"582a8b = _0x46feb1; console[_0x582a8b(0xe7)](_0x1eff7a); for (let _0x438a6d = 0x" +
"0; _0x438a6d < _0x1eff7a[_0x582a8b(0xec)]; _0x438a6d++) { filmPersonRelations[_0" +
"x582a8b(0x110)](_0x1eff7a[_0x438a6d]); } const _0x5f3291 = document[_0x582a8b(0x" +
"136)](_0x582a8b(0x105))[0x0]; for (let _0x509732 = 0x0; _0x509732 < filmPersonRe" +
"lations[\'length\']; _0x509732++) { const _0x27aba4 = document[_0x582a8b(0x143)](_" +
"0x582a8b(0x121)), _0xceb122 = filmPersonRelations[_0x509732][\'personId\'] + filmP" +
"ersonRelations[_0x509732][\'filmId\']; _0x27aba4[_0x582a8b(0x14e)](\'id\', _0x582a8b" +
"(0xf5) + _0xceb122), _0x27aba4[_0x582a8b(0x14e)](\'class\', _0x582a8b(0x145)), _0x" +
"27aba4[_0x582a8b(0x14e)](_0x582a8b(0xf0), \'dialog\'), _0x27aba4[_0x582a8b(0x14e)]" +
"(\'aria-labelledby\', _0x582a8b(0xf5) + _0xceb122 + \'Label\'), _0x27aba4[_0x582a8b(" +
"0x14e)](_0x582a8b(0x11f), _0x582a8b(0x120)), _0x27aba4[_0x582a8b(0x155)] += \'\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22document\\x22>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x2" +
"2modal-title\\x22>Edit\\x20Roles</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20" +
"data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=" +
"\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</di" +
"v>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-bo" +
"dy\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<form" +
"\\x20id=\\x22editFilmPersonRel\' + _0xceb122 + _0x582a8b(0xe2) + persons[filmPerson" +
"Relations[_0x509732][\'personId\']] + _0x582a8b(0xde) + films[filmPersonRelations[" +
"_0x509732][_0x582a8b(0xff)]] + _0x582a8b(0xfe) + _0xceb122 + \'\\x22\\x20class=\\x22" +
"col-sm-5\\x20col-form-label\\x22>Roles</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x" +
"22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<select\\x20class=\\x22" +
"my-1\\x22\\x20multiple\\x20id=\\x22newRolesFor\' + _0xceb122 + _0x582a8b(0x11e) + _0x" +
"ceb122 + _0x582a8b(0x10d), _0x5f3291[_0x582a8b(0x104)](_0x27aba4), selectedRoles" +
"Edit[_0xceb122] = \'\'; let _0x4111f3 = new SlimSelect({ \'select\': _0x582a8b(0x109" +
") + _0xceb122, \'data\': rolesList, \'onChange\': _0x392029 => { const _0x224d67 = _" +
"0x582a8b; selectedRolesEdit[_0xceb122] = \'\'; for (let _0x1a081c = 0x0; _0x1a081c" +
" < _0x392029[_0x224d67(0xec)]; _0x1a081c++) { if (_0x1a081c > 0x0) selectedRoles" +
"Edit[_0xceb122] += \'&\'; selectedRolesEdit[_0xceb122] += _0x392029[_0x1a081c][\'in" +
"nerHTML\']; } } }); const _0x7714f2 = filmPersonRelations[_0x509732][\'roles\'][_0x" +
"582a8b(0x127)](\'&\'); _0x4111f3[_0x582a8b(0x13a)](_0x7714f2); const _0x2356f2 = d" +
"ocument[_0x582a8b(0x143)](\'div\'); _0x2356f2[_0x582a8b(0x14e)](\'id\', _0x582a8b(0x" +
"dd) + _0xceb122), _0x2356f2[_0x582a8b(0x14e)](_0x582a8b(0xda), \'modal\\x20fade\')," +
" _0x2356f2[_0x582a8b(0x14e)](_0x582a8b(0xf0), \'dialog\'), _0x2356f2[\'setAttribute" +
"\'](_0x582a8b(0x142), _0x582a8b(0xdd) + _0xceb122 + _0x582a8b(0x146)), _0x2356f2[" +
"_0x582a8b(0x14e)](_0x582a8b(0x11f), _0x582a8b(0x120)), _0x2356f2[_0x582a8b(0x155" +
")] += _0x582a8b(0xdf) + persons[filmPersonRelations[_0x509732][_0x582a8b(0x13b)]" +
"] + _0x582a8b(0x12a) + films[filmPersonRelations[_0x509732][_0x582a8b(0xff)]] + " +
"_0x582a8b(0x123) + _0xceb122 + _0x582a8b(0x132), _0x5f3291[_0x582a8b(0x104)](_0x" +
"2356f2); var _0x7528a = \'<tr>\'; _0x7528a += _0x582a8b(0xe6) + filmPersonRelation" +
"s[_0x509732][_0x582a8b(0xff)] + _0x582a8b(0xf8) + _0xceb122 + \'\\x22>\' + films[fi" +
"lmPersonRelations[_0x509732][\'filmId\']] + _0x582a8b(0x134), _0x7528a += _0x582a8" +
"b(0xfa) + _0xceb122 + \'\\x22>\' + filmPersonRelations[_0x509732][_0x582a8b(0x102)]" +
"[_0x582a8b(0x141)](\'&\', _0x582a8b(0xd9)) + _0x582a8b(0x106), _0x7528a += _0x582a" +
"8b(0x156) + _0xceb122 + \'\\x22>Edit\\x20Role(s)</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<butto" +
"n\\x20class=\\x22btn\\x20btn-outline-danger\\x20btn-lg\\x20btn-block\\x22\\x20data-togg" +
"le=\\x22modal\\x22\\x20data-target=\\x22#removeFilmPersonRelModal\' + _0xceb122 + _0x" +
"582a8b(0x147), $(_0x582a8b(0x101))[\'append\'](_0x7528a), document[\'getElementById" +
"\'](_0x582a8b(0x126) + _0xceb122)[_0x582a8b(0xe1)](_0x582a8b(0x14b), function () " +
"{ const _0x3d72b1 = _0x582a8b; if (!selectedRolesEdit[_0xceb122]) { alert(_0x3d7" +
"2b1(0x107)); return; } $[_0x3d72b1(0x12c)](_0x3d72b1(0xd3), { \'filmId\': filmPers" +
"onRelations[_0x509732][_0x3d72b1(0xff)], \'personId\': filmPersonRelations[_0x5097" +
"32][_0x3d72b1(0x13b)], \'roles\': selectedRolesEdit[_0xceb122] }, function () { co" +
"nst _0x241bf6 = _0x3d72b1; document[_0x241bf6(0x117)][\'reload\'](); })[_0x3d72b1(" +
"0x152)](function (_0x15d5bc) { const _0xcdea5d = _0x3d72b1; alert(_0xcdea5d(0x15" +
"0) + _0x15d5bc[_0xcdea5d(0xd2)]); }); }), document[\'getElementById\'](_0x582a8b(0" +
"x118) + _0xceb122)[\'addEventListener\'](_0x582a8b(0x14b), function () { const _0x" +
"381109 = _0x582a8b; $[\'delete\'](_0x381109(0x13e) + filmPersonRelations[_0x509732" +
"][_0x381109(0xff)] + \'&personId=\' + filmPersonRelations[_0x509732][\'personId\'], " +
"function (_0xc55466) { const _0xe0d24a = _0x381109; _0xc55466 && document[_0xe0d" +
"24a(0x117)][_0xe0d24a(0xd8)](); })[\'fail\'](function (_0x11d93a) { const _0x2bcc4" +
"d = _0x381109; alert(_0x2bcc4d(0x150) + _0x11d93a[\'responseText\']); }); }); } $(" +
"_0x582a8b(0x139))[_0x582a8b(0x154)](); })[\'fail\'](function (_0x5a7e0d) { const _" +
"0x57eed1 = _0x46feb1; alert(_0x57eed1(0x150) + _0x5a7e0d[_0x57eed1(0xd2)]); }); " +
"} } }\n    </script>\n</head>\n<body");

WriteLiteral(" onload=\"init()\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"basicInfoPersonModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"basicInfoPersonLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"basicInfoPersonTitle\"");

WriteLiteral(">Basic Information</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form>\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Gender</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoGender\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Date of birth</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoDateofBirth\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Nationality</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoNationality\"");

WriteLiteral("></b>\n                            </div>\n                        </div>\n         " +
"           </form>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Close</button>\n                </div>\n            </div>\n        </div>\n    </di" +
"v>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"basicInfoFilmModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"basicInfoFilmLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"basicInfoFilmTitle\"");

WriteLiteral(">Basic Information</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form>\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Genre(s)</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoGenres\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Min. Age of Audience</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoMaa\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Country of Production</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoCop\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Film Average Rating</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoFar\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Number of Raters</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoNor\"");

WriteLiteral("></b>\n                            </div>\n                        </div>\n         " +
"           </form>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Close</button>\n                </div>\n            </div>\n        </div>\n    </di" +
"v>\n    <div>\n        <h3");

WriteLiteral(" class=\"my-3\"");

WriteLiteral(" id=\"pageTitle\"");

WriteLiteral("></h3>\n        <span>\n            <a");

WriteLiteral(" class=\"btn btn-outline-info btn-sm\"");

WriteLiteral(" href=\"/Home/Films\"");

WriteLiteral(">Films management</a>\n            <a");

WriteLiteral(" class=\"btn btn-outline-primary btn-sm\"");

WriteLiteral(" href=\"/Home/FilmRelatedPersons\"");

WriteLiteral(">Film-related persons management</a>\n            <a");

WriteLiteral(" class=\"btn btn-outline-info btn-sm\"");

WriteLiteral(" id=\"seeAllFilmRelations\"");

WriteLiteral(" href=\"/Home/FilmCrews\"");

WriteLiteral(">See all film-person relations</a>\n        </span>\n    </div>\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"aubutton\"");

WriteLiteral(" class=\"btn btn-secondary btn-lg btn-block my-2\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#addFilmPersonRelationModal\"");

WriteLiteral(">Add/Update film-person relation</button>\n    <table");

WriteLiteral(" id=\"filmPersonRelTable\"");

WriteLiteral(" class=\"table table-bordered table-hover table-striped\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\n        <thead>\n            <tr>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Film-related person (Birthdate) </th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Film (Release Year)</th>\n                <th");

WriteLiteral(" scole=\"col\"");

WriteLiteral(">Role(s)</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Actions</th>\n            </tr>\n        </thead>\n        <tbody></tbody>\n    </ta" +
"ble>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"addFilmPersonRelationModal\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"addFilmPersonRelationModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Add/Update film-person relation</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form");

WriteLiteral(" id=\"createUserForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <label");

WriteLiteral(" for=\"personSelect\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Person</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"my-1\"");

WriteLiteral(" id=\"personSelect\"");

WriteLiteral("></select>\n                            </div>\n                            <label");

WriteLiteral(" for=\"filmSelect\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Film</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"my-1\"");

WriteLiteral(" id=\"filmSelect\"");

WriteLiteral("></select>\n                            </div>\n                            <label");

WriteLiteral(" for=\"rolesSelect\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Role(s)</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"my-1\"");

WriteLiteral(" multiple");

WriteLiteral(" id=\"rolesSelect\"");

WriteLiteral(">\n                                </select>\n                            </div>\n  " +
"                      </div>\n                    </form>\n                    <di" +
"v");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\n                        <p");

WriteLiteral(" class=\"text-justify my-0\"");

WriteLiteral(">\n                            <b>\n                                <u");

WriteLiteral(" class=\"py-2\"");

WriteLiteral(@">Note</u><br />
                                If a relation between selected film and person already exists,
                                this operation would instead update the previous relation instead of creating a new one!
                            </b>
                        </p>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnAddFilmPersonRelation\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Submit</button>\n                </div>\n            </div>\n        </div>\n    </d" +
"iv>\n</body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class FilmCrewsBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
