#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD_Project.Views.Home
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Films : FilmsBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\n<html>\n<head>\n    <style>\n    </style>\n    <script defer>\n       " +
" const _0x4ceeee = _0x1900; function _0x4d24() { const _0xc45436 = [\'DataTable\'," +
" \'<td><b\\x20id=\\x22genres\', \'#countryOfProduction\', \'minAgeOfAudience\', \'all=\', " +
"\'Basic\\x20information\\x20of\\x20\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</bu" +
"tton>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\" +
"x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20</div>\', \'<br>\', \'\\x22>Edit\\x20Basic\\x20Information</button>\\x0a\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20<a\\x20class=\\x22btn\\x20btn-outline-info\\x20btn-lg\\x20btn-block\\x22\\" +
"x20href=\\x22/Home/FilmCrews?filmId=\', \'</button>\', \'length\', \'countryOfProductio" +
"n\', \'Label\', \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<label\\x20for=\\x22editReleaseYear\', \'/films?isRoot=\', \'click\', " +
"\'\\x22\\x20class=\\x22my-2\\x22\\x20multiple></select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22editMinAgeOfAud" +
"ience\', \'createElement\', \'All\\x20films\', \'Failed\\x20to\\x20edit\\x20film!\\x20\', \'i" +
"ncludes\', \'editMinAgeOfAudience\', \'15abztpq\', \'17352dgtvdC\', \'\\x20subordinated\\x" +
"20to\\x20\', \'subordinatedTo=\', \'/nationalities\', \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20<div\\x20class=\\x22modal-dialog\\x20modal-xl\\x22\\x20role=\\x22document\\x22>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content" +
"\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x2" +
"0class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>Edit\\x20<span\\x" +
"20class=\\x22text-danger\\x22>\', \'\\x22\\x20class=\\x22col-sm-4\\x20col-form-label\\x20" +
"my-2\\x22>Genre(s)</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22c" +
"ol-sm-8\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<select\\" +
"x20id=\\x22editGenre\', \'<td><b\\x20id=\\x22filmAverageRating\', \'post\', \'text\', \'set" +
"\', \'#editCountryOfProduction\', \'</span>\', \'split\', \'Invalid\\x20param(s)!\', \'2798" +
"22FfonXo\', \'filmTable\', \')\\x20deleted!\', \'innerHTML\', \')</span></h5>\\x0a\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\" +
"x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20a" +
"ria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&t" +
"imes;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<form\\x20id=\\x22editFilmForm\', \'/fil" +
"ms/\', \'<tr>\', \'\\x22>Remove\\x20Film</button></td>\', \'/films?filmRecTo=\', \'Invalid" +
"\\x20min.\\x20age\\x20of\\x20audience!\\x20It\\x20must\\x20be\\x20an\\x20integer\\x20withi" +
"n\\x201\\x20to\\x2021!\', \'basicInfoCop\', \'releaseYear\', \'Failed\\x20to\\x20edit\\x20fi" +
"lm!\\x20Internal\\x20server\\x20error\\x20...\', \'<td><b\\x20id=\\x22minAgeOfAudience\'," +
" \'Failed\\x20to\\x20get\\x20the\\x20list\\x20of\\x20genres!\\x20\', \'backToRootFilms\', \'" +
"removeFilmModal\', \'numberOfRaters\', \'for\\x20all\\x20ages\', \'genre\', \'isInteger\', " +
"\'put\', \'\\x22\\x20class=\\x22my-2\\x22></select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=" +
"\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x" +
"22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-pri" +
"mary\\x22\\x20id=\\x22btnEditFilm\', \'delete\', \'my-4\', \'aria-labelledby\', \'basicInfo" +
"Genres\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Confirm</button>\\x0a\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div" +
">\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20</div>\', \'\\x22\\x20class=\\x22col-sm-4\\x20col-form-label\\x20m" +
"y-2\\x22>Min.\\x20Age\\x20of\\x20Audience</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0<div\\x20class=\\x22col-sm-8\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20<input\\x20type=\\x22number\\x22\\x20min=\\x221\\x22\\x20max=\\x2221\\x22\\x20" +
"placeholder=\\x22Input\\x20must\\x20be\\x20an\\x20integer\\x20within\\x201\\x20to\\x2021\\" +
"x20or\\x20leave\\x20this\\x20field\\x20empty\\x20in\\x20case\\x20there\\x20is\\x20no\\x20a" +
"ge\\x20restriction\\x22\\x20class=\\x22form-control\\x22\\x20id=\\x22editMinAgeOfAudien" +
"ce\', \'716444mRGdnh\', \'#editSubordinatedTo\', \'role\', \'#filmTable\', \'/Home/Films\'," +
" \'title\', \'modal-title\', \'editReleaseYear\', \')\\x20is\\x20updated!\', \'noFilmSugges" +
"tions\', \'class\', \'selectedIndex\', \'<td><b\\x20id=\\x22title\', \'<td><button\\x20clas" +
"s=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal\\x22" +
"\\x20data-target=\\x22#editFilmModal\', \'#subordinatedTo\', \'/Home/Users\', \'appendCh" +
"ild\', \'editCountryOfProduction\', \'filmRec=\', \'replaceAll\', \'addEventListener\', \'" +
"body\', \'options\', \'editSubordinatedTo\', \'\\x22\\x20class=\\x22my-2\\x22></select>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<labe" +
"l\\x20for=\\x22editSubordinatedTo\', \'btnRemoveFilm\', \'\\x22\\x20value=\\x22\', \'Film\\x" +
"20suggestions\\x20for\\x20<span\\x20class=\\x22text-danger\\x22>\', \'filmTotalRating\'," +
" \'Get\\x20back\\x20to\\x20root\\x20films\\x20list\', \'modal\\x20fade\', \'<td><b\\x20id=\\x" +
"22genre\', \'\\x22\\x20class=\\x22col-sm-4\\x20col-form-label\\x20my-2\\x22>Country\\x20o" +
"f\\x20Production</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col" +
"-sm-8\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<select\\x2" +
"0id=\\x22editCountryOfProduction\', \'getElementById\', \'<td><b\\x20id=\\x22numberOfRa" +
"ter\', \'Go\\x20to\\x20root\\x20films\\x20list\', \'10ntHGdT\', \'selected\', \'editTitle\', " +
"\'Failed\\x20to\\x20get\\x20the\\x20list\\x20of\\x20nationalities!\\x20\', \'push\', \'log\'," +
" \'<td><b\\x20id=\\x22releaseYear\', \'\\x22\\x20class=\\x22col-sm-4\\x20col-form-label\\x" +
"20my-2\\x22>Release\\x20Year</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20cl" +
"ass=\\x22col-sm-8\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0<input\\x20type=\\x22number\\x22\\x20min=\\x221850\\x22\\x20placeholder=\\x22Input\\x20m" +
"ust\\x20be\\x20an\\x20integer\\x20within\\x201888\\x20to\\x202022\\x22\\x20class=\\x22form" +
"-control\\x22\\x20id=\\x22editReleaseYear\', \'#editGenre\', \'1117520KAxnwt\', \'\\x22\\x2" +
"0class=\\x22col-sm-4\\x20col-form-label\\x20my-2\\x22>Title</label>\\x0a\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-8\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<input\\x20type=\\x22text\\x22\\x20class=\\x22form-cont" +
"rol\\x22\\x20id=\\x22editTitle\', \'/Home/FilmCrews?filmId=\', \'Failed\\x20to\\x20delete" +
"\\x20film!\\x20\', \'aubutton\', \'Get\\x20back\\x20to\\x20user\\x20management\\x20page\', \'" +
"#genre\', \'</a></b></td>\', \'N/A\', \'value\', \'10549576VRwfxo\', \'\\x22>\\x0a\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x" +
"22editGenre\', \')</span></h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-di" +
"smiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22tru" +
"e\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\x22>" +
"\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>Are\\x20you\\x2" +
"0sure\\x20you\\x20want\\x20to\\x20delete\\x20this\\x20film?\\x20This\\x20operation\\x20ca" +
"nnot\\x20be\\x20undone!</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</d" +
"iv>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-f" +
"ooter\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b" +
"utton\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismi" +
"ss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-prima" +
"ry\\x22\\x20id=\\x22btnRemoveFilm\', \'append\', \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22editCountryOfPr" +
"oduction\', \'15706566qHcoyn\', \'basicInfoFar\', \'\\x22\\x20role=\\x22button\\x22>Crew\\x" +
"20Members\\x20Management</a>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20class=\\x22btn\\x20btn-o" +
"utline-danger\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-ta" +
"rget=\\x22#removeFilmModal\', \'btnEditFilm\', \'let\\x20this\\x20field\\x20empty\\x20if\\" +
"x20you\\x20want\\x20to\\x20make\\x20it\\x20not\\x20subordinated\\x20to\\x20a\\x20film!\', " +
"\'replace\', \'subordinatedTo\', \'\\x22\\x20>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22for" +
"m-group\\x20row\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22editTit" +
"leE\', \'children\', \'Invalid\\x20release\\x20year!\\x20Release\\x20year\\x20must\\x20be\\" +
"x20an\\x20integer\\x20within\\x201888\\x20to\\x202022!\', \'aria-hidden\', \'?filmRec=\', " +
"\'?subordinatedTo=\', \'/films\', \'Root\\x20films\', \'/Home/Films?all=\', \'/users/\', \'F" +
"ailed\\x20to\\x20create\\x20a\\x20film!\\x20\', \'#filmTable\\x20tbody\', \'3108vHaaXX\', \'" +
"\\x22><a\\x20href=\\x27/Home/Films?subordinatedTo=\', \'editFilmModal\', \'href\', \'loca" +
"tion\', \'/films?subordinatedTo=\', \'fail\', \'</b></td>\', \'editGenre\', \'<td><b\\x20id" +
"=\\x22countryOfProduction\', \'dialog\', \'done\', \'search\', \'setAttribute\', \'5260835X" +
"oyypY\', \'\\x22\\x20class=\\x22col-sm-4\\x20col-form-label\\x20my-2\\x22>Subordinated\\x" +
"20To</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-8\\x20my" +
"-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<select\\x20id=\\x22edi" +
"tSubordinatedTo\', \'toFixed\', \'true\', \'getJSON\', \'pageTitle\', \'\\x0a\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20<div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x2" +
"2>Remove\\x20<span\\x20class=\\x22text-danger\\x22>\', \'remove\', \'basicInfoMaa\', \'get" +
"ElementsByTagName\', \'reload\', \'username\', \'responseText\', \'div\', \'Failed\\x20to\\x" +
"20get\\x20the\\x20list\\x20of\\x20films!\\x20\']; _0x4d24 = function () { return _0xc4" +
"5436; }; return _0x4d24(); } function _0x1900(_0x3aaa68, _0x156b43) { const _0x4" +
"d24ca = _0x4d24(); return _0x1900 = function (_0x1900eb, _0x415557) { _0x1900eb " +
"= _0x1900eb - 0xc0; let _0x51214b = _0x4d24ca[_0x1900eb]; return _0x51214b; }, _" +
"0x1900(_0x3aaa68, _0x156b43); } (function (_0x3e9a4a, _0x3f33e5) { const _0x57a4" +
"44 = _0x1900, _0x1cb4ca = _0x3e9a4a(); while (!![]) { try { const _0x19cc6f = pa" +
"rseInt(_0x57a444(0xc1)) / 0x1 + parseInt(_0x57a444(0x125)) / 0x2 * (-parseInt(_0" +
"x57a444(0x116)) / 0x3) + parseInt(_0x57a444(0x142)) / 0x4 + parseInt(_0x57a444(0" +
"xf1)) / 0x5 + -parseInt(_0x57a444(0x117)) / 0x6 * (parseInt(_0x57a444(0xe3)) / 0" +
"x7) + -parseInt(_0x57a444(0xcb)) / 0x8 + parseInt(_0x57a444(0xd0)) / 0x9 * (pars" +
"eInt(_0x57a444(0x166)) / 0xa); if (_0x19cc6f === _0x3f33e5) break; else _0x1cb4c" +
"a[\'push\'](_0x1cb4ca[\'shift\']()); } catch (_0x48a1ba) { _0x1cb4ca[\'push\'](_0x1cb4" +
"ca[\'shift\']()); } } }(_0x4d24, 0xc1478)); var films = [], nationalitiesList = []" +
", genresList = [], selectedGenre = \'\', selectedGenreE = {}; const cur_location =" +
" window[_0x4ceeee(0xe7)][\'pathname\'] + window[_0x4ceeee(0xe7)][_0x4ceeee(0xef)];" +
" async function init() { const _0x23b185 = _0x4ceeee; $(\'#btnCreateFilm\')[_0x23b" +
"185(0x10f)](function () { const _0x421c48 = _0x23b185; var _0x37a40a = { \'title\'" +
": document[_0x421c48(0x163)](_0x421c48(0x147))[_0x421c48(0xca)], \'releaseYear\': " +
"parseInt(document[_0x421c48(0x163)](_0x421c48(0x130))[\'value\']), \'genre\': select" +
"edGenre, \'minAgeOfAudience\': document[_0x421c48(0x163)](_0x421c48(0x103))[_0x421" +
"c48(0xca)] ? parseInt(document[_0x421c48(0x163)](_0x421c48(0x103))[\'value\']) : n" +
"ull, \'countryOfProduction\': document[_0x421c48(0x163)](_0x421c48(0x10b))[\'value\'" +
"], \'filmTotalRating\': 0x0, \'numberOfRaters\': 0x0 }; cur_location[\'includes\'](_0x" +
"421c48(0xdc)) ? _0x37a40a[\'subordinatedTo\'] = cur_location[_0x421c48(0x123)](_0x" +
"421c48(0xdc))[0x1] : _0x37a40a[_0x421c48(0xd6)] = document[_0x421c48(0x163)](\'su" +
"bordinatedTo\')[_0x421c48(0xca)]; if (!_0x37a40a[\'title\'] || !_0x37a40a[\'releaseY" +
"ear\'] || !_0x37a40a[_0x421c48(0x138)] || !countryOfProduction) { alert(_0x421c48" +
"(0x124)); return; } else { if (!Number[_0x421c48(0x139)](_0x37a40a[_0x421c48(0x1" +
"30)]) || _0x37a40a[_0x421c48(0x130)] < 0x760 || _0x37a40a[\'releaseYear\'] > 0x7e6" +
") { alert(\'Invalid\\x20release\\x20year!\\x20Release\\x20year\\x20must\\x20be\\x20an\\x2" +
"0integer\\x20within\\x201888\\x20to\\x202022!\'); return; } else { if (_0x37a40a[_0x4" +
"21c48(0x103)] != null) { if (!Number[\'isInteger\'](_0x37a40a[_0x421c48(0x103)]) |" +
"| _0x37a40a[_0x421c48(0x103)] < 0x1 || _0x37a40a[_0x421c48(0x103)] > 0x15) { ale" +
"rt(_0x421c48(0x12e)); return; } } } } $[_0x421c48(0x11e)](_0x421c48(0xdd), { \'fi" +
"lm\': _0x37a40a }, function (_0x2968b9) { const _0x333809 = _0x421c48; _0x2968b9 " +
"? document[_0x333809(0xe7)][_0x333809(0xd5)](_0x333809(0xc3) + _0x2968b9[\'id\']) " +
": alert(\'Failed\\x20to\\x20create\\x20a\\x20new\\x20film!\\x20Internal\\x20server\\x20er" +
"ror\\x20...\'); })[_0x421c48(0xe9)](function (_0x5638f3) { const _0x2c02e3 = _0x42" +
"1c48; alert(_0x2c02e3(0xe1) + _0x5638f3[_0x2c02e3(0xfd)]); }); }); var _0x5a9c9c" +
" = new SlimSelect({ \'select\': _0x23b185(0xc7), \'onChange\': _0xd27675 => { const " +
"_0x387bd9 = _0x23b185; selectedGenre = \'\'; for (let _0x3ef511 = 0x0; _0x3ef511 <" +
" _0xd27675[_0x387bd9(0x10a)]; _0x3ef511++) { if (_0x3ef511 > 0x0) selectedGenre " +
"+= \'&\'; selectedGenre += _0xd27675[_0x3ef511][\'innerHTML\']; } } }), _0x2e3277 = " +
"new SlimSelect({ \'select\': _0x23b185(0x102) }), _0x4c9893 = new SlimSelect({ \'se" +
"lect\': _0x23b185(0x150), \'placeholder\': _0x23b185(0xd4), \'allowDeselect\': !![] }" +
"); await $[_0x23b185(0xf5)](_0x23b185(0x11a))[_0x23b185(0xee)](function (_0x436f" +
"bf) { const _0x40d60d = _0x23b185, _0x2621c9 = document[_0x40d60d(0x163)](_0x40d" +
"60d(0x10b)); for (let _0x4b80a0 = 0x0; _0x4b80a0 < _0x436fbf[_0x40d60d(0x10a)]; " +
"_0x4b80a0++) { nationalitiesList[_0x40d60d(0x16a)]({ \'text\': _0x436fbf[_0x4b80a0" +
"], \'value\': _0x436fbf[_0x4b80a0] }), _0x2621c9[\'options\'][_0x2621c9[_0x40d60d(0x" +
"158)][\'length\']] = new Option(_0x436fbf[_0x4b80a0], _0x436fbf[_0x4b80a0], !![]);" +
" } })[_0x23b185(0xe9)](function (_0x4669ff) { const _0xfeb006 = _0x23b185; alert" +
"(_0xfeb006(0x169) + _0x4669ff[\'responseText\']); }), await $[_0x23b185(0xf5)](\'/g" +
"enres\')[_0x23b185(0xee)](function (_0x3f0796) { const _0x4d966d = _0x23b185, _0x" +
"101f37 = document[_0x4d966d(0x163)](\'genre\'); for (let _0x33e64f = 0x0; _0x33e64" +
"f < _0x3f0796[_0x4d966d(0x10a)]; _0x33e64f++) { genresList[_0x4d966d(0x16a)]({ \'" +
"text\': _0x3f0796[_0x33e64f], \'value\': _0x3f0796[_0x33e64f] }), _0x101f37[_0x4d96" +
"6d(0x158)][_0x101f37[\'options\'][\'length\']] = new Option(_0x3f0796[_0x33e64f], _0" +
"x3f0796[_0x33e64f], !![]); } })[_0x23b185(0xe9)](function (_0x5e81ff) { const _0" +
"x48e2d4 = _0x23b185; alert(_0x48e2d4(0x133) + _0x5e81ff[_0x48e2d4(0xfd)]); }); i" +
"f (!cur_location[_0x23b185(0x114)](_0x23b185(0x119)) && !cur_location[_0x23b185(" +
"0x114)](_0x23b185(0x154)) && !cur_location[_0x23b185(0x114)](_0x23b185(0x104))) " +
"document[_0x23b185(0x163)](\'backToRootFilms\')[_0x23b185(0xe6)] = _0x23b185(0xdf)" +
" + !![], document[_0x23b185(0x163)](\'pageTitle\')[\'innerHTML\'] = _0x23b185(0xde)," +
" await $[\'getJSON\'](_0x23b185(0x10e) + !![])[_0x23b185(0xee)](function (_0x32625" +
"8) { const _0x4f4932 = _0x23b185, _0x3a5e2b = document[_0x4f4932(0x163)](_0x4f49" +
"32(0xd6)); for (let _0x2898f2 = 0x0; _0x2898f2 < _0x326258[_0x4f4932(0x10a)]; _0" +
"x2898f2++) { films[_0x4f4932(0x16a)](_0x326258[_0x2898f2]), _0x3a5e2b[_0x4f4932(" +
"0x158)][_0x3a5e2b[\'options\'][_0x4f4932(0x10a)]] = new Option(_0x326258[_0x2898f2" +
"][\'title\'] + \'\\x20(\' + _0x326258[_0x2898f2][_0x4f4932(0x130)] + \')\', _0x326258[_" +
"0x2898f2][\'id\']); } _0x3a5e2b[_0x4f4932(0x14d)] = -0x1; const _0x3e15a4 = docume" +
"nt[\'getElementsByTagName\'](_0x4f4932(0x157))[0x0]; for (let _0x26df83 = 0x0; _0x" +
"26df83 < films[_0x4f4932(0x10a)]; _0x26df83++) { const _0x44e355 = document[_0x4" +
"f4932(0x111)](_0x4f4932(0xfe)); _0x44e355[\'setAttribute\'](\'id\', \'editFilmModal\' " +
"+ films[_0x26df83][\'id\']), _0x44e355[_0x4f4932(0xf0)](_0x4f4932(0x14c), _0x4f493" +
"2(0x160)), _0x44e355[\'setAttribute\'](_0x4f4932(0x144), _0x4f4932(0xed)), _0x44e3" +
"55[_0x4f4932(0xf0)](_0x4f4932(0x13e), \'editFilmModal\' + films[_0x26df83][\'id\'] +" +
" _0x4f4932(0x10c)), _0x44e355[_0x4f4932(0xf0)](_0x4f4932(0xda), _0x4f4932(0xf4))" +
", _0x44e355[_0x4f4932(0x128)] += _0x4f4932(0x11b) + films[_0x26df83][_0x4f4932(0" +
"x147)] + \'\\x20(\' + films[_0x26df83][\'releaseYear\'] + _0x4f4932(0x129) + films[_0" +
"x26df83][\'id\'] + _0x4f4932(0xd7) + films[_0x26df83][\'id\'] + _0x4f4932(0xc2) + fi" +
"lms[_0x26df83][\'id\'] + _0x4f4932(0x15c) + films[_0x26df83][\'title\'] + _0x4f4932(" +
"0x10d) + films[_0x26df83][\'id\'] + _0x4f4932(0x16d) + films[_0x26df83][\'id\'] + _0" +
"x4f4932(0x15c) + films[_0x26df83][_0x4f4932(0x130)] + _0x4f4932(0xcc) + films[_0" +
"x26df83][\'id\'] + _0x4f4932(0x11c) + films[_0x26df83][\'id\'] + _0x4f4932(0x110) + " +
"films[_0x26df83][\'id\'] + _0x4f4932(0x141) + films[_0x26df83][\'id\'] + _0x4f4932(0" +
"x15c) + (films[_0x26df83][_0x4f4932(0x103)] ? films[_0x26df83][_0x4f4932(0x103)]" +
" : \'\') + _0x4f4932(0xcf) + films[_0x26df83][\'id\'] + _0x4f4932(0x162) + films[_0x" +
"26df83][\'id\'] + _0x4f4932(0x15a) + films[_0x26df83][\'id\'] + _0x4f4932(0xf2) + fi" +
"lms[_0x26df83][\'id\'] + \'\\x22\\x20class=\\x22my-2\\x22></select>\\x0a\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dis" +
"miss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x" +
"22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditFilm\' + films[_0x26df83][\'id\'] + _0x4f" +
"4932(0x106), _0x3e15a4[_0x4f4932(0x152)](_0x44e355); const _0x1d13a8 = document[" +
"_0x4f4932(0x163)](\'editCountryOfProduction\' + films[_0x26df83][\'id\']); for (let " +
"_0x328f16 = 0x0; _0x328f16 < nationalitiesList[\'length\']; _0x328f16++) { _0x1d13" +
"a8[_0x4f4932(0x158)][_0x1d13a8[\'options\'][\'length\']] = new Option(nationalitiesL" +
"ist[_0x328f16][_0x4f4932(0x11f)], nationalitiesList[_0x328f16][_0x4f4932(0x11f)]" +
", !![]); } let _0x2582ca = _0x1d13a8[\'children\']; for (let _0x5623a4 = 0x0; _0x5" +
"623a4 < _0x2582ca[_0x4f4932(0x10a)]; _0x5623a4++) { if (_0x2582ca[_0x5623a4][_0x" +
"4f4932(0xca)] == films[_0x26df83][\'countryOfProduction\']) { _0x2582ca[_0x5623a4]" +
"[_0x4f4932(0x167)] = !![]; break; } } const _0x4a08c0 = document[_0x4f4932(0x163" +
")](_0x4f4932(0xeb) + films[_0x26df83][\'id\']), _0x358b78 = films[_0x26df83][_0x4f" +
"4932(0x138)][_0x4f4932(0x123)](\'&\'); for (let _0x54c708 = 0x0; _0x54c708 < genre" +
"sList[_0x4f4932(0x10a)]; _0x54c708++) { _0x4a08c0[_0x4f4932(0x158)][_0x4a08c0[_0" +
"x4f4932(0x158)][_0x4f4932(0x10a)]] = new Option(genresList[_0x54c708][_0x4f4932(" +
"0x11f)], genresList[_0x54c708][\'text\'], !![]); } _0x2582ca = _0x4a08c0[_0x4f4932" +
"(0xd8)]; for (let _0x37dda3 = 0x0; _0x37dda3 < _0x2582ca[_0x4f4932(0x10a)]; _0x3" +
"7dda3++) { _0x358b78[_0x4f4932(0x114)](_0x2582ca[_0x37dda3][_0x4f4932(0xca)]) &&" +
" (_0x2582ca[_0x37dda3][_0x4f4932(0x167)] = !![]); } const _0x4993c2 = document[\'" +
"getElementById\'](_0x4f4932(0x159) + films[_0x26df83][\'id\']); for (let _0x198367 " +
"= 0x0; _0x198367 < films[_0x4f4932(0x10a)]; _0x198367++) { films[_0x26df83][\'id\'" +
"] != films[_0x198367][\'id\'] && (_0x4993c2[_0x4f4932(0x158)][_0x4993c2[_0x4f4932(" +
"0x158)][_0x4f4932(0x10a)]] = new Option(films[_0x198367][_0x4f4932(0x147)] + \'\\x" +
"20(\' + films[_0x198367][_0x4f4932(0x130)] + \')\', films[_0x198367][\'id\'])); } var" +
" _0x896606 = new SlimSelect({ \'select\': _0x4f4932(0x143) + films[_0x26df83][\'id\'" +
"], \'placeholder\': \'let\\x20this\\x20field\\x20empty\\x20if\\x20you\\x20want\\x20to\\x20m" +
"ake\\x20it\\x20not\\x20subordinated\\x20to\\x20a\\x20film!\', \'allowDeselect\': !![] });" +
" _0x2582ca = _0x4993c2[_0x4f4932(0xd8)]; for (let _0xc466b4 = 0x0; _0xc466b4 < _" +
"0x2582ca[_0x4f4932(0x10a)]; _0xc466b4++) { if (_0x2582ca[_0xc466b4][_0x4f4932(0x" +
"ca)] == films[_0x26df83][_0x4f4932(0xd6)]) { _0x2582ca[_0xc466b4][_0x4f4932(0x16" +
"7)] = !![]; break; } if (_0xc466b4 == _0x2582ca[\'length\'] - 0x1) _0x4993c2[_0x4f" +
"4932(0x14d)] = -0x1; } selectedGenreE[films[_0x26df83][\'id\']] = films[_0x26df83]" +
"[_0x4f4932(0x138)]; var _0x556db2 = new SlimSelect({ \'select\': \'#editGenre\' + fi" +
"lms[_0x26df83][\'id\'], \'onChange\': _0x3aefd4 => { const _0xa5726c = _0x4f4932; se" +
"lectedGenreE[films[_0x26df83][\'id\']] = \'\'; for (let _0x2779ae = 0x0; _0x2779ae <" +
" _0x3aefd4[_0xa5726c(0x10a)]; _0x2779ae++) { if (_0x2779ae > 0x0) selectedGenreE" +
"[films[_0x26df83][\'id\']] += \'&\'; selectedGenreE[films[_0x26df83][\'id\']] += _0x3a" +
"efd4[_0x2779ae][_0xa5726c(0x128)]; } } }), _0x3b6d79 = new SlimSelect({ \'select\'" +
": _0x4f4932(0x121) + films[_0x26df83][\'id\'] }); if (_0x4993c2[_0x4f4932(0x14d)] " +
"== -0x1) _0x896606[_0x4f4932(0x120)](); const _0xb993cc = document[_0x4f4932(0x1" +
"11)](\'div\'); _0xb993cc[_0x4f4932(0xf0)](\'id\', _0x4f4932(0x135) + films[_0x26df83" +
"][\'id\']), _0xb993cc[_0x4f4932(0xf0)](_0x4f4932(0x14c), _0x4f4932(0x160)), _0xb99" +
"3cc[_0x4f4932(0xf0)](_0x4f4932(0x144), _0x4f4932(0xed)), _0xb993cc[_0x4f4932(0xf" +
"0)](_0x4f4932(0x13e), _0x4f4932(0x135) + films[_0x26df83][\'id\'] + \'Label\'), _0xb" +
"993cc[_0x4f4932(0xf0)](_0x4f4932(0xda), _0x4f4932(0xf4)), _0xb993cc[_0x4f4932(0x" +
"128)] += _0x4f4932(0xf7) + films[_0x26df83][_0x4f4932(0x147)] + \'\\x20(\' + films[" +
"_0x26df83][\'releaseYear\'] + _0x4f4932(0xcd) + films[_0x26df83][\'id\'] + \'\\x22\\x20" +
"data-dismiss=\\x22modal\\x22>Confirm</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20</div>\', _0x3e15a4[_0x4f4932(0x152)](_0xb993cc); var _0x376ace = \'<tr>\'; _0x3" +
"76ace += _0x4f4932(0x14e) + films[_0x26df83][\'id\'] + \'\\x22><a\\x20href=\\x27/Home/" +
"Films?subordinatedTo=\' + films[_0x26df83][\'id\'] + \'\\x27>\' + films[_0x26df83][_0x" +
"4f4932(0x147)] + _0x4f4932(0xc8), _0x376ace += _0x4f4932(0x16c) + films[_0x26df8" +
"3][\'id\'] + \'\\x22>\' + films[_0x26df83][_0x4f4932(0x130)] + _0x4f4932(0xea), _0x37" +
"6ace += _0x4f4932(0x161) + films[_0x26df83][\'id\'] + \'\\x22>\' + films[_0x26df83][_" +
"0x4f4932(0x138)][_0x4f4932(0x155)](\'&\', _0x4f4932(0x107)) + _0x4f4932(0xea), _0x" +
"376ace += _0x4f4932(0x132) + films[_0x26df83][\'id\'] + \'\\x22>\' + (films[_0x26df83" +
"][_0x4f4932(0x103)] ? films[_0x26df83][_0x4f4932(0x103)] : _0x4f4932(0x137)) + _" +
"0x4f4932(0xea), _0x376ace += _0x4f4932(0xec) + films[_0x26df83][\'id\'] + \'\\x22>\' " +
"+ films[_0x26df83][_0x4f4932(0x10b)] + _0x4f4932(0xea), _0x376ace += _0x4f4932(0" +
"x11d) + films[_0x26df83][\'id\'] + \'\\x22>\' + (films[_0x26df83][_0x4f4932(0x15e)] /" +
" films[_0x26df83][_0x4f4932(0x136)] ? (films[_0x26df83][_0x4f4932(0x15e)] / film" +
"s[_0x26df83][\'numberOfRaters\'])[_0x4f4932(0xf3)](0x2) : _0x4f4932(0xc9)) + _0x4f" +
"4932(0xea), _0x376ace += _0x4f4932(0x164) + films[_0x26df83][\'id\'] + \'\\x22>\' + f" +
"ilms[_0x26df83][_0x4f4932(0x136)] + \'</b></td>\', _0x376ace += \'<td><button\\x20cl" +
"ass=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal\\x" +
"22\\x20data-target=\\x22#editFilmModal\' + films[_0x26df83][\'id\'] + \'\\x22>Edit\\x20B" +
"asic\\x20Information</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<a\\x20class=\\x22btn\\x20btn-outli" +
"ne-info\\x20btn-lg\\x20btn-block\\x22\\x20href=\\x22/Home/FilmCrews?filmId=\' + films[" +
"_0x26df83][\'id\'] + _0x4f4932(0xd2) + films[_0x26df83][\'id\'] + _0x4f4932(0x12c), " +
"$(_0x4f4932(0xe2))[\'append\'](_0x376ace); const _0x53e048 = films[_0x26df83][\'id\'" +
"]; document[\'getElementById\'](_0x4f4932(0xd3) + _0x53e048)[_0x4f4932(0x156)](_0x" +
"4f4932(0x10f), function () { const _0x4fded4 = _0x4f4932; var _0xbbcc73 = { \'id\'" +
": _0x53e048, \'title\': document[_0x4fded4(0x163)](_0x4fded4(0x168) + _0x53e048)[\'" +
"value\'], \'releaseYear\': parseInt(document[\'getElementById\'](\'editReleaseYear\' + " +
"_0x53e048)[_0x4fded4(0xca)]), \'genre\': selectedGenreE[films[_0x26df83][\'id\']], \'" +
"minAgeOfAudience\': document[\'getElementById\'](\'editMinAgeOfAudience\' + _0x53e048" +
")[_0x4fded4(0xca)] ? parseInt(document[\'getElementById\'](_0x4fded4(0x115) + _0x5" +
"3e048)[_0x4fded4(0xca)]) : null, \'countryOfProduction\': document[_0x4fded4(0x163" +
")](\'editCountryOfProduction\' + _0x53e048)[\'value\'], \'subordinatedTo\': document[_" +
"0x4fded4(0x163)](_0x4fded4(0x159) + _0x53e048)[\'value\'] ? document[_0x4fded4(0x1" +
"63)](_0x4fded4(0x159) + _0x53e048)[\'value\'] : null }; if (!_0xbbcc73[_0x4fded4(0" +
"x147)] || !_0xbbcc73[_0x4fded4(0x130)] || !_0xbbcc73[_0x4fded4(0x138)] || !_0xbb" +
"cc73[_0x4fded4(0x10b)]) { console[_0x4fded4(0x16b)](_0xbbcc73), alert(\'Invalid\\x" +
"20param(s)!\'); return; } else { if (!Number[_0x4fded4(0x139)](_0xbbcc73[_0x4fded" +
"4(0x130)]) || _0xbbcc73[_0x4fded4(0x130)] < 0x760 || _0xbbcc73[_0x4fded4(0x130)]" +
" > 0x7e6) { alert(\'Invalid\\x20release\\x20year!\\x20Release\\x20year\\x20must\\x20be\\" +
"x20an\\x20integer\\x20within\\x201888\\x20to\\x202022!\'); return; } else { if (_0xbbc" +
"c73[\'minAgeOfAudience\'] != null) { if (!Number[\'isInteger\'](_0xbbcc73[_0x4fded4(" +
"0x103)]) || _0xbbcc73[_0x4fded4(0x103)] < 0x1 || _0xbbcc73[_0x4fded4(0x103)] > 0" +
"x15) { console[\'log\'](_0xbbcc73[_0x4fded4(0x103)]), alert(\'Invalid\\x20min.\\x20ag" +
"e\\x20of\\x20audience!\\x20It\\x20must\\x20be\\x20an\\x20integer\\x20within\\x201\\x20to\\x" +
"2021!\'); return; } } } } $[_0x4fded4(0x13a)](_0x4fded4(0x12a) + _0x53e048, { \'fi" +
"lm\': _0xbbcc73 }, function (_0x2db6f1) { const _0x28727e = _0x4fded4; _0x2db6f1 " +
"? (alert(_0x2db6f1[_0x28727e(0x147)] + \'\\x20(\' + _0x2db6f1[_0x28727e(0x130)] + \'" +
")\\x20is\\x20updated!\'), document[_0x28727e(0xe7)][_0x28727e(0xfb)]()) : alert(_0x" +
"28727e(0x131)); })[\'fail\'](function (_0x527a13) { const _0x223b21 = _0x4fded4; a" +
"lert(_0x223b21(0x113) + _0x527a13[_0x223b21(0xfd)]); }); }), document[_0x4f4932(" +
"0x163)](_0x4f4932(0x15b) + _0x53e048)[_0x4f4932(0x156)](_0x4f4932(0x10f), functi" +
"on () { const _0x5b365b = _0x4f4932; $[_0x5b365b(0x13c)](\'/films/\' + _0x53e048, " +
"function (_0x314084) { const _0x1e1f88 = _0x5b365b; _0x314084 && (alert(films[_0" +
"x26df83][_0x1e1f88(0x147)] + \'\\x20{\' + films[_0x26df83][_0x1e1f88(0x130)] + _0x1" +
"e1f88(0x127)), document[_0x1e1f88(0xe7)][_0x1e1f88(0xfb)]()); })[_0x5b365b(0xe9)" +
"](function (_0x1f8b42) { const _0x359793 = _0x5b365b; alert(_0x359793(0xc4) + _0" +
"x1f8b42[_0x359793(0xfd)]); }); }); } $(_0x4f4932(0x145))[\'DataTable\'](); })[_0x2" +
"3b185(0xe9)](function (_0x3f31c3) { const _0x10e5e5 = _0x23b185; alert(_0x10e5e5" +
"(0xff) + _0x3f31c3[_0x10e5e5(0xfd)]); }); else { if (cur_location[_0x23b185(0x11" +
"4)](_0x23b185(0x119))) { document[_0x23b185(0x163)](_0x23b185(0x134))[_0x23b185(" +
"0x128)] = _0x23b185(0x15f); const _0x208773 = cur_location[\'split\'](\'?subordinat" +
"edTo=\')[0x1]; await $[_0x23b185(0xf5)](_0x23b185(0x12a) + _0x208773)[\'done\'](fun" +
"ction (_0xb49083) { const _0x1ab5c0 = _0x23b185; films[\'push\'](_0xb49083); const" +
" _0x19e628 = _0xb49083[_0x1ab5c0(0x147)] + \'\\x20(\' + _0xb49083[_0x1ab5c0(0x130)]" +
" + \')\'; document[_0x1ab5c0(0x163)](\'pageTitle\')[_0x1ab5c0(0x128)] = \'Film(s)\\x20" +
"subordinated\\x20to\\x20\' + (\'<button\\x20type=\\x22button\\x22\\x20class=\\x22btn-ligh" +
"t\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-target=\\x22#basicInfoFilmModal\\x22>\' " +
"+ _0x19e628 + _0x1ab5c0(0x109)), document[\'getElementById\'](\'basicInfoFilmTitle\'" +
")[_0x1ab5c0(0x128)] = _0x1ab5c0(0x105) + _0x19e628, document[_0x1ab5c0(0x163)](_" +
"0x1ab5c0(0x13f))[_0x1ab5c0(0x128)] = _0xb49083[\'genre\'][_0x1ab5c0(0x155)](\'&\', \'" +
",\\x20\'), document[_0x1ab5c0(0x163)](_0x1ab5c0(0xf9))[_0x1ab5c0(0x128)] = _0xb490" +
"83[_0x1ab5c0(0x103)], document[_0x1ab5c0(0x163)](_0x1ab5c0(0x12f))[_0x1ab5c0(0x1" +
"28)] = _0xb49083[_0x1ab5c0(0x10b)], document[_0x1ab5c0(0x163)](_0x1ab5c0(0xd1))[" +
"_0x1ab5c0(0x128)] = _0xb49083[_0x1ab5c0(0x15e)] / _0xb49083[\'numberOfRaters\'] ? " +
"(_0xb49083[_0x1ab5c0(0x15e)] / _0xb49083[_0x1ab5c0(0x136)])[_0x1ab5c0(0xf3)](0x2" +
") : _0x1ab5c0(0xc9), document[_0x1ab5c0(0x163)](\'basicInfoNor\')[_0x1ab5c0(0x128)" +
"] = _0xb49083[\'numberOfRaters\'], document[_0x1ab5c0(0x163)](_0x1ab5c0(0xc5))[_0x" +
"1ab5c0(0x128)] += _0x1ab5c0(0x118) + _0x19e628, document[\'getElementsByClassName" +
"\'](_0x1ab5c0(0x148))[0x0][_0x1ab5c0(0x128)] += \'\\x20subordinated\\x20to\\x20\' + _0" +
"x19e628; }), await $[_0x23b185(0xf5)](_0x23b185(0xe8) + _0x208773)[_0x23b185(0xe" +
"e)](function (_0x2bef9c) { const _0x529393 = _0x23b185; document[\'getElementById" +
"\'](\'labelSubordinatedTo\')[_0x529393(0xf8)](), document[_0x529393(0x163)](\'divSub" +
"ordinatedTo\')[_0x529393(0xf8)](); for (let _0x3ee14b = 0x0; _0x3ee14b < _0x2bef9" +
"c[_0x529393(0x10a)]; _0x3ee14b++) { films[_0x529393(0x16a)](_0x2bef9c[_0x3ee14b]" +
"); } const _0x1da3aa = document[\'getElementsByTagName\'](_0x529393(0x157))[0x0]; " +
"for (let _0x79af83 = 0x0; _0x79af83 < films[_0x529393(0x10a)]; _0x79af83++) { if" +
" (films[_0x79af83][\'id\'] == _0x208773) continue; const _0x1ba643 = document[_0x5" +
"29393(0x111)](_0x529393(0xfe)); _0x1ba643[\'setAttribute\'](\'id\', _0x529393(0xe5) " +
"+ films[_0x79af83][\'id\']), _0x1ba643[_0x529393(0xf0)](_0x529393(0x14c), \'modal\\x" +
"20fade\'), _0x1ba643[_0x529393(0xf0)](\'role\', \'dialog\'), _0x1ba643[\'setAttribute\'" +
"](_0x529393(0x13e), _0x529393(0xe5) + films[_0x79af83][\'id\'] + \'Label\'), _0x1ba6" +
"43[_0x529393(0xf0)](_0x529393(0xda), \'true\'), _0x1ba643[_0x529393(0x128)] += \'\\x" +
"0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x20modal-xl\\x22" +
"\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<d" +
"iv\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22mo" +
"dal-title\\x22>Edit\\x20<span\\x20class=\\x22text-danger\\x22>\' + films[_0x79af83][_0" +
"x529393(0x147)] + \'\\x20(\' + films[_0x79af83][_0x529393(0x130)] + _0x529393(0x129" +
") + films[_0x79af83][\'id\'] + _0x529393(0xd7) + films[_0x79af83][\'id\'] + _0x52939" +
"3(0xc2) + films[_0x79af83][\'id\'] + _0x529393(0x15c) + films[_0x79af83][_0x529393" +
"(0x147)] + _0x529393(0x10d) + films[_0x79af83][\'id\'] + _0x529393(0x16d) + films[" +
"_0x79af83][\'id\'] + _0x529393(0x15c) + films[_0x79af83][_0x529393(0x130)] + _0x52" +
"9393(0xcc) + films[_0x79af83][\'id\'] + \'\\x22\\x20class=\\x22col-sm-4\\x20col-form-la" +
"bel\\x20my-2\\x22>Genre(s)</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20clas" +
"s=\\x22col-sm-8\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"select\\x20id=\\x22editGenre\' + films[_0x79af83][\'id\'] + _0x529393(0x110) + films[" +
"_0x79af83][\'id\'] + _0x529393(0x141) + films[_0x79af83][\'id\'] + \'\\x22\\x20value=\\x" +
"22\' + (films[_0x79af83][_0x529393(0x103)] ? films[_0x79af83][\'minAgeOfAudience\']" +
" : \'\') + _0x529393(0xcf) + films[_0x79af83][\'id\'] + _0x529393(0x162) + films[_0x" +
"79af83][\'id\'] + _0x529393(0x15a) + films[_0x79af83][\'id\'] + _0x529393(0xf2) + fi" +
"lms[_0x79af83][\'id\'] + _0x529393(0x13b) + films[_0x79af83][\'id\'] + _0x529393(0x1" +
"06), _0x1da3aa[_0x529393(0x152)](_0x1ba643); const _0x4f9be1 = document[_0x52939" +
"3(0x163)](_0x529393(0x153) + films[_0x79af83][\'id\']); for (let _0x418265 = 0x0; " +
"_0x418265 < nationalitiesList[_0x529393(0x10a)]; _0x418265++) { _0x4f9be1[_0x529" +
"393(0x158)][_0x4f9be1[\'options\'][_0x529393(0x10a)]] = new Option(nationalitiesLi" +
"st[_0x418265][_0x529393(0x11f)], nationalitiesList[_0x418265][\'text\'], !![]); } " +
"let _0x7e4b5 = _0x4f9be1[\'children\']; for (let _0x59140e = 0x0; _0x59140e < _0x7" +
"e4b5[\'length\']; _0x59140e++) { if (_0x7e4b5[_0x59140e][_0x529393(0xca)] == films" +
"[_0x79af83][_0x529393(0x10b)]) { _0x7e4b5[_0x59140e][_0x529393(0x167)] = !![]; b" +
"reak; } } const _0x3017f6 = document[_0x529393(0x163)](_0x529393(0xeb) + films[_" +
"0x79af83][\'id\']), _0x22188c = films[_0x79af83][_0x529393(0x138)][_0x529393(0x123" +
")](\'&\'); for (let _0x545ea9 = 0x0; _0x545ea9 < genresList[\'length\']; _0x545ea9++" +
") { _0x3017f6[\'options\'][_0x3017f6[_0x529393(0x158)][_0x529393(0x10a)]] = new Op" +
"tion(genresList[_0x545ea9][\'text\'], genresList[_0x545ea9][\'text\'], !![]); } _0x7" +
"e4b5 = _0x3017f6[_0x529393(0xd8)]; for (let _0x473ea3 = 0x0; _0x473ea3 < _0x7e4b" +
"5[_0x529393(0x10a)]; _0x473ea3++) { _0x22188c[_0x529393(0x114)](_0x7e4b5[_0x473e" +
"a3][_0x529393(0xca)]) && (_0x7e4b5[_0x473ea3][_0x529393(0x167)] = !![]); } const" +
" _0x3d3df8 = document[\'getElementById\'](_0x529393(0x159) + films[_0x79af83][\'id\'" +
"]); for (let _0x45cc57 = 0x0; _0x45cc57 < films[_0x529393(0x10a)]; _0x45cc57++) " +
"{ if (films[_0x79af83][\'id\'] != films[_0x45cc57][\'id\']) _0x3d3df8[_0x529393(0x15" +
"8)][_0x3d3df8[_0x529393(0x158)][\'length\']] = new Option(films[_0x45cc57][_0x5293" +
"93(0x147)] + \'\\x20(\' + films[_0x45cc57][_0x529393(0x130)] + \')\', films[_0x45cc57" +
"][\'id\']); } var _0x582ea4 = new SlimSelect({ \'select\': _0x529393(0x143) + films[" +
"_0x79af83][\'id\'], \'placeholder\': _0x529393(0xd4), \'allowDeselect\': !![] }); _0x7" +
"e4b5 = _0x3d3df8[_0x529393(0xd8)]; for (let _0x570d0c = 0x0; _0x570d0c < _0x7e4b" +
"5[_0x529393(0x10a)]; _0x570d0c++) { if (_0x7e4b5[_0x570d0c][_0x529393(0xca)] == " +
"films[_0x79af83][\'subordinatedTo\']) { _0x7e4b5[_0x570d0c][_0x529393(0x167)] = !!" +
"[]; break; } if (_0x570d0c == _0x7e4b5[_0x529393(0x10a)] - 0x1) _0x3d3df8[_0x529" +
"393(0x14d)] = -0x1; } selectedGenreE[films[_0x79af83][\'id\']] = films[_0x79af83][" +
"_0x529393(0x138)]; var _0x42ca65 = new SlimSelect({ \'select\': _0x529393(0xc0) + " +
"films[_0x79af83][\'id\'], \'onChange\': _0x2d1faf => { const _0x2a710e = _0x529393; " +
"selectedGenreE[films[_0x79af83][\'id\']] = \'\'; for (let _0x1ec122 = 0x0; _0x1ec122" +
" < _0x2d1faf[_0x2a710e(0x10a)]; _0x1ec122++) { if (_0x1ec122 > 0x0) selectedGenr" +
"eE[films[_0x79af83][\'id\']] += \'&\'; selectedGenreE[films[_0x79af83][\'id\']] += _0x" +
"2d1faf[_0x1ec122][_0x2a710e(0x128)]; } } }), _0xd6f82b = new SlimSelect({ \'selec" +
"t\': _0x529393(0x121) + films[_0x79af83][\'id\'] }); if (_0x3d3df8[_0x529393(0x14d)" +
"] == -0x1) _0x582ea4[_0x529393(0x120)](); const _0x4294b7 = document[_0x529393(0" +
"x111)](_0x529393(0xfe)); _0x4294b7[_0x529393(0xf0)](\'id\', _0x529393(0x135) + fil" +
"ms[_0x79af83][\'id\']), _0x4294b7[_0x529393(0xf0)](_0x529393(0x14c), \'modal\\x20fad" +
"e\'), _0x4294b7[\'setAttribute\'](\'role\', \'dialog\'), _0x4294b7[_0x529393(0xf0)](_0x" +
"529393(0x13e), _0x529393(0x135) + films[_0x79af83][\'id\'] + _0x529393(0x10c)), _0" +
"x4294b7[\'setAttribute\'](_0x529393(0xda), _0x529393(0xf4)), _0x4294b7[\'innerHTML\'" +
"] += _0x529393(0xf7) + films[_0x79af83][\'title\'] + \'\\x20(\' + films[_0x79af83][_0" +
"x529393(0x130)] + \')</span></h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20dat" +
"a-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x2" +
"2true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\" +
"x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\" +
"x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>Are\\x20yo" +
"u\\x20sure\\x20you\\x20want\\x20to\\x20delete\\x20this\\x20film?\\x20This\\x20operation\\x" +
"20cannot\\x20be\\x20undone!</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22mod" +
"al-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-d" +
"ismiss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-p" +
"rimary\\x22\\x20id=\\x22btnRemoveFilm\' + films[_0x79af83][\'id\'] + _0x529393(0x140)," +
" _0x1da3aa[_0x529393(0x152)](_0x4294b7); var _0x2a0ede = \'<tr>\'; _0x2a0ede += _0" +
"x529393(0x14e) + films[_0x79af83][\'id\'] + _0x529393(0xe4) + films[_0x79af83][\'id" +
"\'] + \'\\x27>\' + films[_0x79af83][_0x529393(0x147)] + _0x529393(0xc8), _0x2a0ede +" +
"= _0x529393(0x16c) + films[_0x79af83][\'id\'] + \'\\x22>\' + films[_0x79af83][\'releas" +
"eYear\'] + \'</b></td>\', _0x2a0ede += _0x529393(0x161) + films[_0x79af83][\'id\'] + " +
"\'\\x22>\' + films[_0x79af83][\'genre\'][\'replaceAll\'](\'&\', \'<br>\') + _0x529393(0xea)" +
", _0x2a0ede += _0x529393(0x132) + films[_0x79af83][\'id\'] + \'\\x22>\' + (films[_0x7" +
"9af83][_0x529393(0x103)] ? films[_0x79af83][_0x529393(0x103)] : _0x529393(0x137)" +
") + \'</b></td>\', _0x2a0ede += _0x529393(0xec) + films[_0x79af83][\'id\'] + \'\\x22>\'" +
" + films[_0x79af83][\'countryOfProduction\'] + _0x529393(0xea), _0x2a0ede += _0x52" +
"9393(0x11d) + films[_0x79af83][\'id\'] + \'\\x22>\' + (films[_0x79af83][\'filmTotalRat" +
"ing\'] / films[_0x79af83][_0x529393(0x136)] ? (films[_0x79af83][_0x529393(0x15e)]" +
" / films[_0x79af83][_0x529393(0x136)])[_0x529393(0xf3)](0x2) : _0x529393(0xc9)) " +
"+ \'</b></td>\', _0x2a0ede += \'<td><b\\x20id=\\x22numberOfRater\' + films[_0x79af83][" +
"\'id\'] + \'\\x22>\' + films[_0x79af83][\'numberOfRaters\'] + _0x529393(0xea), _0x2a0ed" +
"e += _0x529393(0x14f) + films[_0x79af83][\'id\'] + _0x529393(0x108) + films[_0x79a" +
"f83][\'id\'] + _0x529393(0xd2) + films[_0x79af83][\'id\'] + _0x529393(0x12c), $(_0x5" +
"29393(0xe2))[_0x529393(0xce)](_0x2a0ede); const _0x3037a0 = films[_0x79af83][\'id" +
"\']; document[_0x529393(0x163)](_0x529393(0xd3) + _0x3037a0)[_0x529393(0x156)](_0" +
"x529393(0x10f), function () { const _0x51eb42 = _0x529393; var _0x62e358 = { \'id" +
"\': _0x3037a0, \'title\': document[_0x51eb42(0x163)](_0x51eb42(0x168) + _0x3037a0)[" +
"_0x51eb42(0xca)], \'releaseYear\': parseInt(document[_0x51eb42(0x163)](_0x51eb42(0" +
"x149) + _0x3037a0)[\'value\']), \'genre\': selectedGenreE[films[_0x79af83][\'id\']], \'" +
"minAgeOfAudience\': document[_0x51eb42(0x163)](\'editMinAgeOfAudience\' + _0x3037a0" +
")[_0x51eb42(0xca)] ? parseInt(document[_0x51eb42(0x163)](_0x51eb42(0x115) + _0x3" +
"037a0)[_0x51eb42(0xca)]) : null, \'countryOfProduction\': document[_0x51eb42(0x163" +
")](_0x51eb42(0x153) + _0x3037a0)[\'value\'], \'subordinatedTo\': document[_0x51eb42(" +
"0x163)](_0x51eb42(0x159) + _0x3037a0)[_0x51eb42(0xca)] ? document[_0x51eb42(0x16" +
"3)](\'editSubordinatedTo\' + _0x3037a0)[_0x51eb42(0xca)] : null }; if (!_0x62e358[" +
"_0x51eb42(0x147)] || !_0x62e358[_0x51eb42(0x130)] || !_0x62e358[_0x51eb42(0x138)" +
"] || !_0x62e358[_0x51eb42(0x10b)]) { console[\'log\'](_0x62e358), alert(_0x51eb42(" +
"0x124)); return; } else { if (!Number[_0x51eb42(0x139)](_0x62e358[_0x51eb42(0x13" +
"0)]) || _0x62e358[_0x51eb42(0x130)] < 0x760 || _0x62e358[_0x51eb42(0x130)] > 0x7" +
"e6) { alert(\'Invalid\\x20release\\x20year!\\x20Release\\x20year\\x20must\\x20be\\x20an\\" +
"x20integer\\x20within\\x201888\\x20to\\x202022!\'); return; } else { if (_0x62e358[_0" +
"x51eb42(0x103)] != null) { if (!Number[_0x51eb42(0x139)](_0x62e358[_0x51eb42(0x1" +
"03)]) || _0x62e358[\'minAgeOfAudience\'] < 0x1 || _0x62e358[_0x51eb42(0x103)] > 0x" +
"15) { console[_0x51eb42(0x16b)](_0x62e358[_0x51eb42(0x103)]), alert(_0x51eb42(0x" +
"12e)); return; } } } } $[\'put\'](_0x51eb42(0x12a) + _0x3037a0, { \'film\': _0x62e35" +
"8 }, function (_0x1d167a) { const _0xeff33a = _0x51eb42; _0x1d167a ? (alert(_0x1" +
"d167a[\'title\'] + \'\\x20(\' + _0x1d167a[\'releaseYear\'] + _0xeff33a(0x14a)), documen" +
"t[\'location\'][_0xeff33a(0xfb)]()) : alert(_0xeff33a(0x131)); })[_0x51eb42(0xe9)]" +
"(function (_0x3ff420) { const _0x1133fd = _0x51eb42; alert(_0x1133fd(0x113) + _0" +
"x3ff420[_0x1133fd(0xfd)]); }); }), document[_0x529393(0x163)](_0x529393(0x15b) +" +
" _0x3037a0)[_0x529393(0x156)](_0x529393(0x10f), function () { const _0x21485c = " +
"_0x529393; $[_0x21485c(0x13c)](\'/films/\' + _0x3037a0, function (_0x25037e) { con" +
"st _0x42d05f = _0x21485c; _0x25037e && (alert(films[_0x79af83][_0x42d05f(0x147)]" +
" + \'\\x20{\' + films[_0x79af83][_0x42d05f(0x130)] + _0x42d05f(0x127)), document[_0" +
"x42d05f(0xe7)][_0x42d05f(0xfb)]()); })[\'fail\'](function (_0x590c41) { const _0x4" +
"b693a = _0x21485c; alert(_0x4b693a(0xc4) + _0x590c41[_0x4b693a(0xfd)]); }); }); " +
"} $(_0x529393(0x145))[_0x529393(0x100)](); })[_0x23b185(0xe9)](function (_0x5288" +
"d2) { const _0x4df0b5 = _0x23b185; alert(_0x4df0b5(0xff) + _0x5288d2[_0x4df0b5(0" +
"xfd)]); }); } else { if (cur_location[_0x23b185(0x114)](_0x23b185(0xdb))) { cons" +
"t _0x125dd7 = cur_location[_0x23b185(0x123)](_0x23b185(0xdb))[0x1], _0x91f26d = " +
"document[\'getElementById\'](\'backToRootFilms\'); _0x91f26d[\'innerHTML\'] = _0x23b18" +
"5(0xc6), _0x91f26d[_0x23b185(0xe6)] = _0x23b185(0x151), document[_0x23b185(0x163" +
")](_0x23b185(0xc5))[_0x23b185(0xf8)](), document[_0x23b185(0x163)](\'filmTable\')[" +
"\'classList\'][\'add\'](_0x23b185(0x13d)); let _0x57db13; await $[_0x23b185(0xf5)](_" +
"0x23b185(0xe0) + _0x125dd7)[_0x23b185(0xee)](function (_0x39c5f4) { const _0x19f" +
"78b = _0x23b185; document[\'getElementById\'](\'pageTitle\')[_0x19f78b(0x128)] = _0x" +
"19f78b(0x15d) + _0x39c5f4[_0x19f78b(0xfc)] + _0x19f78b(0x122), _0x57db13 = _0x39" +
"c5f4[_0x19f78b(0xfc)]; }), await $[_0x23b185(0xf5)](_0x23b185(0x12d) + _0x125dd7" +
")[_0x23b185(0xee)](function (_0x38d321) { const _0x51faa6 = _0x23b185, _0x208538" +
" = document[_0x51faa6(0xfa)](\'th\')[0x7]; _0x208538[\'remove\'](); const _0x1effe1 " +
"= document[_0x51faa6(0x163)](_0x51faa6(0xd6)); for (let _0x44d04f = 0x0; _0x44d0" +
"4f < _0x38d321[_0x51faa6(0x10a)]; _0x44d04f++) { films[\'push\'](_0x38d321[_0x44d0" +
"4f]), _0x1effe1[_0x51faa6(0x158)][_0x1effe1[_0x51faa6(0x158)][_0x51faa6(0x10a)]]" +
" = new Option(_0x38d321[_0x44d04f][_0x51faa6(0x147)] + \'\\x20(\' + _0x38d321[_0x44" +
"d04f][\'releaseYear\'] + \')\', _0x38d321[_0x44d04f][\'id\']); } _0x1effe1[\'selectedIn" +
"dex\'] = -0x1; for (let _0x3618f6 = 0x0; _0x3618f6 < films[_0x51faa6(0x10a)]; _0x" +
"3618f6++) { var _0x5d87ba = _0x51faa6(0x12b); _0x5d87ba += _0x51faa6(0x14e) + fi" +
"lms[_0x3618f6][\'id\'] + _0x51faa6(0xe4) + films[_0x3618f6][\'id\'] + \'\\x27>\' + film" +
"s[_0x3618f6][_0x51faa6(0x147)] + \'</a></b></td>\', _0x5d87ba += _0x51faa6(0x16c) " +
"+ films[_0x3618f6][\'id\'] + \'\\x22>\' + films[_0x3618f6][_0x51faa6(0x130)] + \'</b><" +
"/td>\', _0x5d87ba += _0x51faa6(0x101) + films[_0x3618f6][\'id\'] + \'\\x22>\' + films[" +
"_0x3618f6][\'genre\'][_0x51faa6(0x155)](\'&\', \'<br>\') + _0x51faa6(0xea), _0x5d87ba " +
"+= _0x51faa6(0x132) + films[_0x3618f6][\'id\'] + \'\\x22>\' + (films[_0x3618f6][_0x51" +
"faa6(0x103)] ? films[_0x3618f6][\'minAgeOfAudience\'] : _0x51faa6(0x137)) + _0x51f" +
"aa6(0xea), _0x5d87ba += _0x51faa6(0xec) + films[_0x3618f6][\'id\'] + \'\\x22>\' + fil" +
"ms[_0x3618f6][_0x51faa6(0x10b)] + _0x51faa6(0xea), _0x5d87ba += \'<td><b\\x20id=\\x" +
"22filmAverageRating\' + films[_0x3618f6][\'id\'] + \'\\x22>\' + (films[_0x3618f6][_0x5" +
"1faa6(0x15e)] / films[_0x3618f6][_0x51faa6(0x136)] ? (films[_0x3618f6][\'filmTota" +
"lRating\'] / films[_0x3618f6][_0x51faa6(0x136)])[_0x51faa6(0xf3)](0x2) : _0x51faa" +
"6(0xc9)) + _0x51faa6(0xea), _0x5d87ba += _0x51faa6(0x164) + films[_0x3618f6][\'id" +
"\'] + \'\\x22>\' + films[_0x3618f6][_0x51faa6(0x136)] + _0x51faa6(0xea), $(_0x51faa6" +
"(0xe2))[_0x51faa6(0xce)](_0x5d87ba); } films[\'length\'] > 0x0 ? $(_0x51faa6(0x145" +
"))[_0x51faa6(0x100)]() : (document[\'getElementById\'](_0x51faa6(0x126))[_0x51faa6" +
"(0xf8)](), document[_0x51faa6(0x163)](_0x51faa6(0x14b))[_0x51faa6(0x128)] = \'The" +
"re\\x20is\\x20no\\x20suitable\\x20film\\x20suggestion\\x20for\\x20\' + _0x57db13 + \'!\');" +
" })[_0x23b185(0xe9)](function (_0x24657f) { alert(\'Failed\\x20to\\x20get\\x20the\\x2" +
"0list\\x20of\\x20films!\\x20\' + _0x24657f[\'responseText\']); }); } else { document[_" +
"0x23b185(0x163)](\'backToRootFilms\')[_0x23b185(0x128)] = _0x23b185(0x165), docume" +
"nt[_0x23b185(0x163)](\'backToRootFilms\')[_0x23b185(0xe6)] = _0x23b185(0x146), doc" +
"ument[\'getElementById\'](_0x23b185(0xf6))[_0x23b185(0x128)] = _0x23b185(0x112), a" +
"wait $[_0x23b185(0xf5)](_0x23b185(0xdd))[_0x23b185(0xee)](function (_0x13e402) {" +
" const _0x330d65 = _0x23b185, _0x609738 = document[_0x330d65(0x163)](_0x330d65(0" +
"xd6)); for (let _0x3a6ee5 = 0x0; _0x3a6ee5 < _0x13e402[_0x330d65(0x10a)]; _0x3a6" +
"ee5++) { films[\'push\'](_0x13e402[_0x3a6ee5]), _0x609738[\'options\'][_0x609738[\'op" +
"tions\'][\'length\']] = new Option(_0x13e402[_0x3a6ee5][_0x330d65(0x147)] + \'\\x20(\'" +
" + _0x13e402[_0x3a6ee5][_0x330d65(0x130)] + \')\', _0x13e402[_0x3a6ee5][\'id\']); } " +
"_0x609738[_0x330d65(0x14d)] = -0x1; const _0x5678f4 = document[_0x330d65(0xfa)](" +
"\'body\')[0x0]; for (let _0x1dc49d = 0x0; _0x1dc49d < films[_0x330d65(0x10a)]; _0x" +
"1dc49d++) { const _0x43e9a4 = document[_0x330d65(0x111)](_0x330d65(0xfe)); _0x43" +
"e9a4[_0x330d65(0xf0)](\'id\', _0x330d65(0xe5) + films[_0x1dc49d][\'id\']), _0x43e9a4" +
"[_0x330d65(0xf0)](_0x330d65(0x14c), \'modal\\x20fade\'), _0x43e9a4[_0x330d65(0xf0)]" +
"(_0x330d65(0x144), \'dialog\'), _0x43e9a4[_0x330d65(0xf0)](\'aria-labelledby\', _0x3" +
"30d65(0xe5) + films[_0x1dc49d][\'id\'] + _0x330d65(0x10c)), _0x43e9a4[_0x330d65(0x" +
"f0)](_0x330d65(0xda), _0x330d65(0xf4)), _0x43e9a4[\'innerHTML\'] += \'\\x0a\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x20modal-xl\\x22\\x20role=\\x" +
"22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class" +
"=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x" +
"22>Edit\\x20<span\\x20class=\\x22text-danger\\x22>\' + films[_0x1dc49d][_0x330d65(0x1" +
"47)] + \'\\x20(\' + films[_0x1dc49d][\'releaseYear\'] + \')</span></h5>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20" +
"type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20aria" +
"-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&time" +
"s;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<form\\x20id=\\x22editFilmForm\' + films[_" +
"0x1dc49d][\'id\'] + _0x330d65(0xd7) + films[_0x1dc49d][\'id\'] + _0x330d65(0xc2) + f" +
"ilms[_0x1dc49d][\'id\'] + _0x330d65(0x15c) + films[_0x1dc49d][_0x330d65(0x147)] + " +
"\'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20<label\\x20for=\\x22editReleaseYear\' + films[_0x1dc49d][\'id\'] + _0x330d65(0x16" +
"d) + films[_0x1dc49d][\'id\'] + _0x330d65(0x15c) + films[_0x1dc49d][_0x330d65(0x13" +
"0)] + _0x330d65(0xcc) + films[_0x1dc49d][\'id\'] + _0x330d65(0x11c) + films[_0x1dc" +
"49d][\'id\'] + _0x330d65(0x110) + films[_0x1dc49d][\'id\'] + _0x330d65(0x141) + film" +
"s[_0x1dc49d][\'id\'] + \'\\x22\\x20value=\\x22\' + (films[_0x1dc49d][\'minAgeOfAudience\'" +
"] ? films[_0x1dc49d][_0x330d65(0x103)] : \'\') + \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22editCountry" +
"OfProduction\' + films[_0x1dc49d][\'id\'] + _0x330d65(0x162) + films[_0x1dc49d][\'id" +
"\'] + _0x330d65(0x15a) + films[_0x1dc49d][\'id\'] + _0x330d65(0xf2) + films[_0x1dc4" +
"9d][\'id\'] + _0x330d65(0x13b) + films[_0x1dc49d][\'id\'] + _0x330d65(0x106), _0x567" +
"8f4[_0x330d65(0x152)](_0x43e9a4); const _0x1d4905 = document[\'getElementById\'](_" +
"0x330d65(0x153) + films[_0x1dc49d][\'id\']); for (let _0x40ccce = 0x0; _0x40ccce <" +
" nationalitiesList[_0x330d65(0x10a)]; _0x40ccce++) { _0x1d4905[_0x330d65(0x158)]" +
"[_0x1d4905[_0x330d65(0x158)][_0x330d65(0x10a)]] = new Option(nationalitiesList[_" +
"0x40ccce][\'text\'], nationalitiesList[_0x40ccce][_0x330d65(0x11f)], !![]); } let " +
"_0xf653fb = _0x1d4905[\'children\']; for (let _0x4f30fa = 0x0; _0x4f30fa < _0xf653" +
"fb[_0x330d65(0x10a)]; _0x4f30fa++) { if (_0xf653fb[_0x4f30fa][_0x330d65(0xca)] =" +
"= films[_0x1dc49d][_0x330d65(0x10b)]) { _0xf653fb[_0x4f30fa][_0x330d65(0x167)] =" +
" !![]; break; } } const _0x5017d8 = document[_0x330d65(0x163)](_0x330d65(0xeb) +" +
" films[_0x1dc49d][\'id\']), _0xc0ffd4 = films[_0x1dc49d][_0x330d65(0x138)][_0x330d" +
"65(0x123)](\'&\'); for (let _0x23ff95 = 0x0; _0x23ff95 < genresList[_0x330d65(0x10" +
"a)]; _0x23ff95++) { _0x5017d8[\'options\'][_0x5017d8[_0x330d65(0x158)][_0x330d65(0" +
"x10a)]] = new Option(genresList[_0x23ff95][_0x330d65(0x11f)], genresList[_0x23ff" +
"95][_0x330d65(0x11f)], !![]); } _0xf653fb = _0x5017d8[_0x330d65(0xd8)]; for (let" +
" _0x5b4986 = 0x0; _0x5b4986 < _0xf653fb[_0x330d65(0x10a)]; _0x5b4986++) { _0xc0f" +
"fd4[_0x330d65(0x114)](_0xf653fb[_0x5b4986][\'value\']) && (_0xf653fb[_0x5b4986][_0" +
"x330d65(0x167)] = !![]); } const _0x2cca8d = document[_0x330d65(0x163)](_0x330d6" +
"5(0x159) + films[_0x1dc49d][\'id\']); for (let _0x93fde = 0x0; _0x93fde < films[\'l" +
"ength\']; _0x93fde++) { if (films[_0x1dc49d][\'id\'] != films[_0x93fde][\'id\']) _0x2" +
"cca8d[_0x330d65(0x158)][_0x2cca8d[_0x330d65(0x158)][\'length\']] = new Option(film" +
"s[_0x93fde][_0x330d65(0x147)] + \'\\x20(\' + films[_0x93fde][\'releaseYear\'] + \')\', " +
"films[_0x93fde][\'id\']); } _0xf653fb = _0x2cca8d[\'children\']; for (let _0x2796d9 " +
"= 0x0; _0x2796d9 < _0xf653fb[_0x330d65(0x10a)]; _0x2796d9++) { if (_0xf653fb[_0x" +
"2796d9][\'value\'] == films[_0x1dc49d][_0x330d65(0xd6)]) { _0xf653fb[_0x2796d9][_0" +
"x330d65(0x167)] = !![], console[\'log\'](_0xf653fb[_0x2796d9]); break; } if (_0x27" +
"96d9 == _0xf653fb[_0x330d65(0x10a)] - 0x1) _0x2cca8d[_0x330d65(0x14d)] = -0x1; }" +
" var _0x42e126 = new SlimSelect({ \'select\': _0x330d65(0x143) + films[_0x1dc49d][" +
"\'id\'], \'placeholder\': _0x330d65(0xd4), \'allowDeselect\': !![] }); selectedGenreE[" +
"films[_0x1dc49d][\'id\']] = films[_0x1dc49d][_0x330d65(0x138)]; var _0x403ac8 = ne" +
"w SlimSelect({ \'select\': _0x330d65(0xc0) + films[_0x1dc49d][\'id\'], \'onChange\': _" +
"0x260afd => { const _0xa9ff8a = _0x330d65; selectedGenreE[films[_0x1dc49d][\'id\']" +
"] = \'\'; for (let _0xc89dae = 0x0; _0xc89dae < _0x260afd[_0xa9ff8a(0x10a)]; _0xc8" +
"9dae++) { if (_0xc89dae > 0x0) selectedGenreE[films[_0x1dc49d][\'id\']] += \'&\'; se" +
"lectedGenreE[films[_0x1dc49d][\'id\']] += _0x260afd[_0xc89dae][_0xa9ff8a(0x128)]; " +
"} } }), _0x62b766 = new SlimSelect({ \'select\': \'#editCountryOfProduction\' + film" +
"s[_0x1dc49d][\'id\'] }); if (_0x2cca8d[_0x330d65(0x14d)] == -0x1) _0x42e126[_0x330" +
"d65(0x120)](); const _0x26f9b3 = document[\'createElement\'](_0x330d65(0xfe)); _0x" +
"26f9b3[_0x330d65(0xf0)](\'id\', _0x330d65(0x135) + films[_0x1dc49d][\'id\']), _0x26f" +
"9b3[\'setAttribute\'](_0x330d65(0x14c), \'modal\\x20fade\'), _0x26f9b3[_0x330d65(0xf0" +
")](_0x330d65(0x144), _0x330d65(0xed)), _0x26f9b3[_0x330d65(0xf0)](_0x330d65(0x13" +
"e), _0x330d65(0x135) + films[_0x1dc49d][\'id\'] + _0x330d65(0x10c)), _0x26f9b3[\'se" +
"tAttribute\'](\'aria-hidden\', _0x330d65(0xf4)), _0x26f9b3[_0x330d65(0x128)] += _0x" +
"330d65(0xf7) + films[_0x1dc49d][_0x330d65(0x147)] + \'\\x20(\' + films[_0x1dc49d][_" +
"0x330d65(0x130)] + _0x330d65(0xcd) + films[_0x1dc49d][\'id\'] + _0x330d65(0x140), " +
"_0x5678f4[_0x330d65(0x152)](_0x26f9b3); var _0x4f830b = _0x330d65(0x12b); _0x4f8" +
"30b += _0x330d65(0x14e) + films[_0x1dc49d][\'id\'] + \'\\x22><a\\x20href=\\x27/Home/Fi" +
"lms?subordinatedTo=\' + films[_0x1dc49d][\'id\'] + \'\\x27>\' + films[_0x1dc49d][_0x33" +
"0d65(0x147)] + _0x330d65(0xc8), _0x4f830b += _0x330d65(0x16c) + films[_0x1dc49d]" +
"[\'id\'] + \'\\x22>\' + films[_0x1dc49d][_0x330d65(0x130)] + _0x330d65(0xea), _0x4f83" +
"0b += _0x330d65(0x161) + films[_0x1dc49d][\'id\'] + \'\\x22>\' + films[_0x1dc49d][\'ge" +
"nre\'][_0x330d65(0x155)](\'&\', _0x330d65(0x107)) + _0x330d65(0xea), _0x4f830b += \'" +
"<td><b\\x20id=\\x22minAgeOfAudience\' + films[_0x1dc49d][\'id\'] + \'\\x22>\' + (films[_" +
"0x1dc49d][\'minAgeOfAudience\'] ? films[_0x1dc49d][_0x330d65(0x103)] : _0x330d65(0" +
"x137)) + \'</b></td>\', _0x4f830b += _0x330d65(0xec) + films[_0x1dc49d][\'id\'] + \'\\" +
"x22>\' + films[_0x1dc49d][_0x330d65(0x10b)] + \'</b></td>\', _0x4f830b += _0x330d65" +
"(0x11d) + films[_0x1dc49d][\'id\'] + \'\\x22>\' + (films[_0x1dc49d][_0x330d65(0x15e)]" +
" / films[_0x1dc49d][\'numberOfRaters\'] ? (films[_0x1dc49d][_0x330d65(0x15e)] / fi" +
"lms[_0x1dc49d][\'numberOfRaters\'])[_0x330d65(0xf3)](0x2) : \'N/A\') + \'</b></td>\', " +
"_0x4f830b += \'<td><b\\x20id=\\x22numberOfRater\' + films[_0x1dc49d][\'id\'] + \'\\x22>\'" +
" + films[_0x1dc49d][_0x330d65(0x136)] + _0x330d65(0xea), _0x4f830b += _0x330d65(" +
"0x14f) + films[_0x1dc49d][\'id\'] + \'\\x22>Edit\\x20Basic\\x20Information</button>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<a\\x20class=\\x22btn\\x20btn-outline-info\\x20btn-lg\\x20btn-block\\" +
"x22\\x20href=\\x22/Home/FilmCrews?filmId=\' + films[_0x1dc49d][\'id\'] + \'\\x22\\x20rol" +
"e=\\x22button\\x22>Crew\\x20Members\\x20Management</a>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x2" +
"0class=\\x22btn\\x20btn-outline-danger\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\" +
"x22modal\\x22\\x20data-target=\\x22#removeFilmModal\' + films[_0x1dc49d][\'id\'] + _0x" +
"330d65(0x12c), $(_0x330d65(0xe2))[\'append\'](_0x4f830b); const _0x266c70 = films[" +
"_0x1dc49d][\'id\']; document[_0x330d65(0x163)](_0x330d65(0xd3) + _0x266c70)[\'addEv" +
"entListener\'](_0x330d65(0x10f), function () { const _0x3459e7 = _0x330d65; var _" +
"0x2c9c90 = { \'id\': _0x266c70, \'title\': document[_0x3459e7(0x163)](_0x3459e7(0x16" +
"8) + _0x266c70)[\'value\'], \'releaseYear\': parseInt(document[_0x3459e7(0x163)](_0x" +
"3459e7(0x149) + _0x266c70)[_0x3459e7(0xca)]), \'genre\': selectedGenreE[films[_0x1" +
"dc49d][\'id\']], \'minAgeOfAudience\': document[_0x3459e7(0x163)](\'editMinAgeOfAudie" +
"nce\' + _0x266c70)[_0x3459e7(0xca)] ? parseInt(document[_0x3459e7(0x163)](\'editMi" +
"nAgeOfAudience\' + _0x266c70)[\'value\']) : null, \'countryOfProduction\': document[_" +
"0x3459e7(0x163)](\'editCountryOfProduction\' + _0x266c70)[_0x3459e7(0xca)], \'subor" +
"dinatedTo\': document[\'getElementById\'](_0x3459e7(0x159) + _0x266c70)[\'value\'] ? " +
"document[_0x3459e7(0x163)](_0x3459e7(0x159) + _0x266c70)[_0x3459e7(0xca)] : null" +
" }; if (!_0x2c9c90[_0x3459e7(0x147)] || !_0x2c9c90[_0x3459e7(0x130)] || !_0x2c9c" +
"90[_0x3459e7(0x138)] || !_0x2c9c90[_0x3459e7(0x10b)]) { console[\'log\'](_0x2c9c90" +
"), alert(\'Invalid\\x20param(s)!\'); return; } else { if (!Number[_0x3459e7(0x139)]" +
"(_0x2c9c90[_0x3459e7(0x130)]) || _0x2c9c90[\'releaseYear\'] < 0x760 || _0x2c9c90[\'" +
"releaseYear\'] > 0x7e6) { alert(_0x3459e7(0xd9)); return; } else { if (_0x2c9c90[" +
"_0x3459e7(0x103)] != null) { if (!Number[_0x3459e7(0x139)](_0x2c9c90[\'minAgeOfAu" +
"dience\']) || _0x2c9c90[_0x3459e7(0x103)] < 0x1 || _0x2c9c90[_0x3459e7(0x103)] > " +
"0x15) { console[_0x3459e7(0x16b)](_0x2c9c90[\'minAgeOfAudience\']), alert(_0x3459e" +
"7(0x12e)); return; } } } } $[_0x3459e7(0x13a)](_0x3459e7(0x12a) + _0x266c70, { \'" +
"film\': _0x2c9c90 }, function (_0x588342) { const _0x34d1c2 = _0x3459e7; _0x58834" +
"2 ? (alert(_0x588342[_0x34d1c2(0x147)] + \'\\x20(\' + _0x588342[_0x34d1c2(0x130)] +" +
" _0x34d1c2(0x14a)), document[\'location\'][_0x34d1c2(0xfb)]()) : alert(_0x34d1c2(0" +
"x131)); })[_0x3459e7(0xe9)](function (_0x43264d) { const _0x38d66b = _0x3459e7; " +
"alert(_0x38d66b(0x113) + _0x43264d[_0x38d66b(0xfd)]); }); }), document[\'getEleme" +
"ntById\'](_0x330d65(0x15b) + _0x266c70)[_0x330d65(0x156)](_0x330d65(0x10f), funct" +
"ion () { const _0x568bb9 = _0x330d65; $[_0x568bb9(0x13c)](_0x568bb9(0x12a) + _0x" +
"266c70, function (_0xa3faed) { const _0x57a129 = _0x568bb9; _0xa3faed && (alert(" +
"films[_0x1dc49d][_0x57a129(0x147)] + \'\\x20{\' + films[_0x1dc49d][_0x57a129(0x130)" +
"] + _0x57a129(0x127)), document[_0x57a129(0xe7)][\'reload\']()); })[\'fail\'](functi" +
"on (_0x5d067d) { const _0x16cd0e = _0x568bb9; alert(_0x16cd0e(0xc4) + _0x5d067d[" +
"_0x16cd0e(0xfd)]); }); }); } $(_0x330d65(0x145))[_0x330d65(0x100)](); })[_0x23b1" +
"85(0xe9)](function (_0x4db28c) { const _0x1d0031 = _0x23b185; alert(_0x1d0031(0x" +
"ff) + _0x4db28c[_0x1d0031(0xfd)]); });; } } } }\n    </script>\n</head>\n<body");

WriteLiteral(" onload=\"init()\"");

WriteLiteral(">\n    <div>\n        <h3");

WriteLiteral(" id=\"pageTitle\"");

WriteLiteral(" class=\"my-3\"");

WriteLiteral("></h3>\n        <a");

WriteLiteral(" class=\"btn btn-outline-primary btn-sm my-2\"");

WriteLiteral(" id=\"backToRootFilms\"");

WriteLiteral(" href=\"/Home/Films\"");

WriteLiteral(">See all films</a>\n    </div>\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"aubutton\"");

WriteLiteral(" class=\"btn btn-secondary btn-lg btn-block my-2\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#createFilmModal\"");

WriteLiteral(">Add new film</button>\n    <table");

WriteLiteral(" id=\"filmTable\"");

WriteLiteral(" class=\"table table-bordered table-hover table-striped\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\n        <thead>\n            <tr>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Title</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Release Year</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Genre</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Min. Age of Audience</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Country of Production</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Film Average Rating</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Number of Raters</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Actions</th>\n            </tr>\n        </thead>\n        <tbody></tbody>\n    </ta" +
"ble>\n    <b");

WriteLiteral(" id=\"noFilmSuggestions\"");

WriteLiteral(" class=\"my-2\"");

WriteLiteral("></b>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"createFilmModal\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"createFilmModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog modal-xl\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Add a film</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form");

WriteLiteral(" id=\"createFilmForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <label");

WriteLiteral(" for=\"title\"");

WriteLiteral(" class=\"col-sm-4 col-form-label my-2\"");

WriteLiteral(">Title</label>\n                            <div");

WriteLiteral(" class=\"col-sm-8 my-2\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"title\"");

WriteLiteral(">\n                            </div>\n                            <label");

WriteLiteral(" for=\"releaseYear\"");

WriteLiteral(" class=\"col-sm-4 col-form-label my-2\"");

WriteLiteral(">Release Year</label>\n                            <div");

WriteLiteral(" class=\"col-sm-8 my-2\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" min=\"1850\"");

WriteLiteral(" placeholder=\"Input must be an integer within 1888 to 2022\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"releaseYear\"");

WriteLiteral(">\n                            </div>\n                            <label");

WriteLiteral(" for=\"genre\"");

WriteLiteral(" class=\"col-sm-4 col-form-label my-2\"");

WriteLiteral(">Genre(s)</label>\n                            <div");

WriteLiteral(" class=\"col-sm-8 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" id=\"genre\"");

WriteLiteral(" class=\"my-2\"");

WriteLiteral(" multiple></select>\n                            </div>\n                          " +
"  <label");

WriteLiteral(" for=\"minAgeOfAudience\"");

WriteLiteral(" class=\"col-sm-4 col-form-label my-2\"");

WriteLiteral(">Min. Age of Audience</label>\n                            <div");

WriteLiteral(" class=\"col-sm-8 my-2\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" min=\"1\"");

WriteLiteral(" max=\"21\"");

WriteLiteral(" placeholder=\"Input must be an integer within 1 to 21 or leave this field empty i" +
"n case there is no age restriction\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"minAgeOfAudience\"");

WriteLiteral(">\n                            </div>\n                            <label");

WriteLiteral(" for=\"countryOfProduction\"");

WriteLiteral(" class=\"col-sm-4 col-form-label my-2\"");

WriteLiteral(">Country of Production</label>\n                            <div");

WriteLiteral(" class=\"col-sm-8 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" id=\"countryOfProduction\"");

WriteLiteral(" class=\"my-2\"");

WriteLiteral("></select>\n                            </div>\n                            <label");

WriteLiteral(" for=\"subordinatedTo\"");

WriteLiteral(" class=\"col-sm-4 col-form-label my-2\"");

WriteLiteral(" id=\"labelSubordinatedTo\"");

WriteLiteral(">Subordinated To</label>\n                            <div");

WriteLiteral(" class=\"col-sm-8 my-2\"");

WriteLiteral(" id=\"divSubordinatedTo\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" id=\"subordinatedTo\"");

WriteLiteral(" class=\"my-2\"");

WriteLiteral("></select>\n                            </div>\n                        </div>\n    " +
"                </form>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnCreateFilm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Submit</button>\n                </div>\n            </div>\n        </div>\n    </d" +
"iv>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"basicInfoFilmModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"basicInfoFilmLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"basicInfoFilmTitle\"");

WriteLiteral(">Basic Information</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form>\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Genre(s)</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoGenres\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Min. Age of Audience</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoMaa\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Country of Production</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoCop\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Film Average Rating</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoFar\"");

WriteLiteral("></b>\n                            </div>\n                            <div");

WriteLiteral(" class=\"col-sm-5 col-form-label\"");

WriteLiteral(">Number of Raters</div>\n                            <div");

WriteLiteral(" class=\"col-sm-7 my-2\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" id=\"basicInfoNor\"");

WriteLiteral("></b>\n                            </div>\n                        </div>\n         " +
"           </form>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Close</button>\n                </div>\n            </div>\n        </div>\n    </di" +
"v>\n</body>\n</html>\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class FilmsBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
