#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD_Project.Views.Home
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class FilmRatings : FilmRatingsBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\n<html>\n<head>\n    <script defer>\n        (function (_0x2cdac0, _0" +
"x19b412) { const _0x547041 = _0x124c, _0x3d7007 = _0x2cdac0(); while (!![]) { tr" +
"y { const _0x4dfabf = -parseInt(_0x547041(0x19e)) / 0x1 * (parseInt(_0x547041(0x" +
"1d3)) / 0x2) + -parseInt(_0x547041(0x1bf)) / 0x3 + parseInt(_0x547041(0x178)) / " +
"0x4 * (-parseInt(_0x547041(0x18e)) / 0x5) + parseInt(_0x547041(0x1a7)) / 0x6 + p" +
"arseInt(_0x547041(0x196)) / 0x7 * (-parseInt(_0x547041(0x183)) / 0x8) + -parseIn" +
"t(_0x547041(0x1ac)) / 0x9 + parseInt(_0x547041(0x1c6)) / 0xa; if (_0x4dfabf === " +
"_0x19b412) break; else _0x3d7007[\'push\'](_0x3d7007[\'shift\']()); } catch (_0x5e49" +
"cc) { _0x3d7007[\'push\'](_0x3d7007[\'shift\']()); } } }(_0x2e44, 0xa61cd)); var fil" +
"mUserRatings = [], films = {}, users = {}; function _0x2e44() { const _0x27d426 " +
"= [\'</b>\\x20will\\x20be\\x20removed!</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22b" +
"utton\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Ca" +
"ncel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-primary\\" +
"x22\\x20id=\\x22btnRemoveUserRating\', \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal" +
"-dialog\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x2" +
"0class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>Edit\\x20Rating</h5>\\x0a" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=" +
"\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20aria-labe" +
"l=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<form\\x20id=\\x22editUserRating\', \'aria-hidde" +
"n\', \'modal\\x20fade\', \'5915982KsddVr\', \'getElementsByTagName\', \'/films\', \'title\'," +
" \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-5\\x" +
"20col-form-label\\x22>Film</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x2" +
"0my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>\', \'457911ZHAEdr\', \'createEleme" +
"nt\', \'filmId\', \'/users/filmRatings\', \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20<option>1</option><option>2</option><option>3</option><option>4</opti" +
"on>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<option>5</option><option>6</" +
"option><option>7</option><option>8</option>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20<option>9</option><option>10</option>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20</select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x" +
"20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondar" +
"y\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\" +
"x22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditUserRating\', \'includes\', \'#userSelect" +
"\', \'?userId=\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</button>\\x0a\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\', \'#filmRatingTable\\x20tbody\', \'seeAllFilmRatin" +
"gs\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</button>\\x0a\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\', \'\\x22><" +
"b\\x20id=\\x22userId\', \'/users/filmRatings?userId=\', \'<tr>\', \'<td><a\\x20href=\\x22/" +
"Home/FilmRatings?userId=\', \'options\', \'reload\', \'btnAddUserFilmRating\', \'3215757" +
"ohQieo\', \'children\', \'btnRemoveUserRating\', \'Failed\\x20to\\x20process\\x20the\\x20r" +
"equest!\\x20\', \'length\', \'some\', \'class\', \'34489810ygNDIY\', \'innerHTML\', \'fail\', " +
"\'aubutton\', \'post\', \'aria-labelledby\', \'remove\', \'<td><b\\x20id=\\x22filmRating\', " +
"\'Label\', \'setAttribute\', \'userSelect\', \'pageTitle\', \'removeUserRatingModal\', \'69" +
"98nmAYit\', \'\\x22\\x20class=\\x22col-sm-5\\x20col-form-label\\x22>Rating</label>\\x0a\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20<select\\x20class=\\x22form-control\\x20form-control-sm\\x22\\x20id=\\x22new" +
"UserRatingFor\', \'userId\', \'Film\\x20Ratings\\x20for\\x20<span><a\\x20class=\\x22text-" +
"info\\x22\\x20href=\\x22/Home/FilmCrews?filmId=\', \'releaseYear\', \'\\x22><b\\x20id=\\x2" +
"2filmId\', \'\\x22>Edit\\x20Rating</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20class=\\x22" +
"btn\\x20btn-outline-danger\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal\\x2" +
"2\\x20data-target=\\x22#removeUserRatingModal\', \'done\', \'#filmRatingTable\', \'All\\x" +
"20film\\x20ratings\', \'</b>\\x20for\\x20film\\x20<b>\', \'\\x20from\\x20\', \'\\x22>Remove\\x" +
"20Rating</button></td></tr>\', \'dialog\', \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<di" +
"v\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-hea" +
"der\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22>Remove\\x20Rating</h5>\\x0a\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x2" +
"0type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20ari" +
"a-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&tim" +
"es;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20Are\\x20you\\x20sure?\\x20Rating\\x20f" +
"rom\\x20user\\x20<b>\', \'addEventListener\', \'<td><a\\x20href=\\x22/Home/FilmRatings?f" +
"ilmId=\', \'pathname\', \'editUserRatingModal\', \'appendChild\', \'value\', \'</a></span>" +
"\', \'12FMfoeH\', \'&filmId=\', \'</b></a></td>\', \'getElementById\', \'click\', \'hidden\'," +
" \'filmRatingSelect\', \'filmRating\', \'div\', \'search\', \'userId=\', \'8mwRJcL\', \'</b>\\" +
"x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22newUserRatingFor\'" +
", \'\\x22\\x20>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20<div\\x20class=\\x22form-group\\x20row\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div" +
"\\x20class=\\x22col-sm-5\\x20col-form-label\\x22>Username</div>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"div\\x20class=\\x22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>\', " +
"\'responseText\', \'true\', \'selected\', \'DataTable\', \'username\', \'newUserRatingFor\'," +
" \'<td><button\\x20class=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\x20data" +
"-toggle=\\x22modal\\x22\\x20data-target=\\x22#editUserRatingModal\', \'</span>\', \'1784" +
"170iMyMux\', \'split\', \'Failed\\x20to\\x20remove\\x20this\\x20rating!\', \'/users\', \'</b" +
"></td>\', \'/films/\', \'btnEditUserRating\', \'/user/userRating?userId=\', \'1425683MMq" +
"VAd\', \'role\', \'#filmSelect\', \'filmId=\', \'/users/\', \'append\', \'delete\', \'push\', \'" +
"388rwtRQb\', \'filmSelect\', \'location\', \'body\', \'getJSON\']; _0x2e44 = function () " +
"{ return _0x27d426; }; return _0x2e44(); } async function init() { const _0x3e2d" +
"03 = _0x124c; let _0x4ff4b4 = new SlimSelect({ \'select\': _0x3e2d03(0x1b2) }), _0" +
"x3fa103 = new SlimSelect({ \'select\': _0x3e2d03(0x198) }); initAddUserFilmRatingB" +
"tn(); const _0x3098d5 = window[_0x3e2d03(0x1a0)][_0x3e2d03(0x173)] + window[_0x3" +
"e2d03(0x1a0)][_0x3e2d03(0x181)]; if (!_0x3098d5[\'includes\'](_0x3e2d03(0x182)) &&" +
" !_0x3098d5[_0x3e2d03(0x1b1)](_0x3e2d03(0x199))) document[_0x3e2d03(0x17b)](_0x3" +
"e2d03(0x1d1))[_0x3e2d03(0x1c7)] = _0x3e2d03(0x1dc), document[_0x3e2d03(0x17b)](_" +
"0x3e2d03(0x1b6))[_0x3e2d03(0x17d)] = !![], await $[_0x3e2d03(0x1a2)](_0x3e2d03(0" +
"x1a9))[_0x3e2d03(0x1da)](function (_0x330bcb) { const _0x49c267 = _0x3e2d03, _0x" +
"ee4b9d = document[\'getElementById\'](_0x49c267(0x19f)); for (let _0x6033fc = 0x0;" +
" _0x6033fc < _0x330bcb[\'length\']; _0x6033fc++) { films[_0x330bcb[_0x6033fc][\'id\'" +
"]] = _0x330bcb[_0x6033fc][\'title\'] + \'\\x20(\' + _0x330bcb[_0x6033fc][_0x49c267(0x" +
"1d7)] + \')\', _0xee4b9d[_0x49c267(0x1bc)][_0xee4b9d[_0x49c267(0x1bc)][_0x49c267(0" +
"x1c3)]] = new Option(_0x330bcb[_0x6033fc][\'title\'] + \'\\x20(\' + _0x330bcb[_0x6033" +
"fc][_0x49c267(0x1d7)] + \')\', _0x330bcb[_0x6033fc][\'id\'], !![]); } }), await $[_0" +
"x3e2d03(0x1a2)](_0x3e2d03(0x191))[_0x3e2d03(0x1da)](function (_0x8f0365) { const" +
" _0x49a672 = _0x3e2d03, _0x248535 = document[_0x49a672(0x17b)](_0x49a672(0x1d0))" +
"; for (let _0x2d727c = 0x0; _0x2d727c < _0x8f0365[_0x49a672(0x1c3)]; _0x2d727c++" +
") { users[_0x8f0365[_0x2d727c][\'id\']] = _0x8f0365[_0x2d727c][_0x49a672(0x18a)], " +
"_0x248535[_0x49a672(0x1bc)][_0x248535[_0x49a672(0x1bc)][_0x49a672(0x1c3)]] = new" +
" Option(_0x8f0365[_0x2d727c][_0x49a672(0x18a)], _0x8f0365[_0x2d727c][\'id\'], !![]" +
"); } }), await $[_0x3e2d03(0x1a2)](_0x3e2d03(0x1af))[\'done\'](function (_0x54634e" +
") { const _0x712d9c = _0x3e2d03; for (let _0x4930fd = 0x0; _0x4930fd < _0x54634e" +
"[_0x712d9c(0x1c3)]; _0x4930fd++) { filmUserRatings[\'push\'](_0x54634e[_0x4930fd])" +
"; } const _0x266372 = document[\'getElementsByTagName\'](_0x712d9c(0x1a1))[0x0]; f" +
"or (let _0x5ddad2 = 0x0; _0x5ddad2 < filmUserRatings[\'length\']; _0x5ddad2++) { c" +
"onst _0x3bf174 = document[\'createElement\'](_0x712d9c(0x180)), _0x22405e = filmUs" +
"erRatings[_0x5ddad2][_0x712d9c(0x1d5)] + filmUserRatings[_0x5ddad2][_0x712d9c(0x" +
"1ae)]; _0x3bf174[_0x712d9c(0x1cf)](\'id\', _0x712d9c(0x174) + _0x22405e), _0x3bf17" +
"4[_0x712d9c(0x1cf)](_0x712d9c(0x1c5), _0x712d9c(0x1a6)), _0x3bf174[\'setAttribute" +
"\'](_0x712d9c(0x197), _0x712d9c(0x1e0)), _0x3bf174[_0x712d9c(0x1cf)](\'aria-labell" +
"edby\', _0x712d9c(0x174) + _0x22405e + \'Label\'), _0x3bf174[_0x712d9c(0x1cf)](_0x7" +
"12d9c(0x1a5), _0x712d9c(0x187)), _0x3bf174[_0x712d9c(0x1c7)] += _0x712d9c(0x1a4)" +
" + _0x22405e + _0x712d9c(0x185) + users[filmUserRatings[_0x5ddad2][_0x712d9c(0x1" +
"d5)]] + _0x712d9c(0x1ab) + films[filmUserRatings[_0x5ddad2][_0x712d9c(0x1ae)]] +" +
" \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22newUserRat" +
"ingFor\' + _0x22405e + _0x712d9c(0x1d4) + _0x22405e + _0x712d9c(0x1b0) + _0x22405" +
"e + \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20</div>\', _0x266372[_0x712d9c(0x175)](_0x3bf174); const _0x745c72 " +
"= document[_0x712d9c(0x17b)](_0x712d9c(0x18b) + _0x22405e), _0x39f840 = _0x745c7" +
"2[_0x712d9c(0x1c0)]; for (var _0x1a0af2 = 0x0; _0x1a0af2 < 0xa; _0x1a0af2++) { i" +
"f (_0x39f840[_0x1a0af2][_0x712d9c(0x1c7)] == filmUserRatings[_0x5ddad2][_0x712d9" +
"c(0x17f)]) { _0x39f840[_0x1a0af2][_0x712d9c(0x188)] = !![]; break; } } const _0x" +
"4f6afc = document[_0x712d9c(0x1ad)](_0x712d9c(0x180)); _0x4f6afc[\'setAttribute\']" +
"(\'id\', _0x712d9c(0x1d2) + _0x22405e), _0x4f6afc[_0x712d9c(0x1cf)](_0x712d9c(0x1c" +
"5), _0x712d9c(0x1a6)), _0x4f6afc[_0x712d9c(0x1cf)](_0x712d9c(0x197), \'dialog\'), " +
"_0x4f6afc[_0x712d9c(0x1cf)](\'aria-labelledby\', _0x712d9c(0x1d2) + _0x22405e + _0" +
"x712d9c(0x1ce)), _0x4f6afc[_0x712d9c(0x1cf)](_0x712d9c(0x1a5), \'true\'), _0x4f6af" +
"c[_0x712d9c(0x1c7)] += \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22mo" +
"dal-dialog\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x" +
"20class=\\x22modal-title\\x22>Remove\\x20Rating</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\" +
"x22\\x20class=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close" +
"\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x22>&times;</span>\\x0a\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</b" +
"utton>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>" +
"\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20clas" +
"s=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20Are\\x20you\\x20sure?\\x20Rating\\x20from\\x20user\\x20<b" +
">\' + users[filmUserRatings[_0x5ddad2][\'userId\']] + _0x712d9c(0x1dd) + films[film" +
"UserRatings[_0x5ddad2][_0x712d9c(0x1ae)]] + _0x712d9c(0x1a3) + _0x22405e + _0x71" +
"2d9c(0x1b7), _0x266372[_0x712d9c(0x175)](_0x4f6afc); var _0x258ff4 = _0x712d9c(0" +
"x1ba); _0x258ff4 += _0x712d9c(0x1bb) + filmUserRatings[_0x5ddad2][_0x712d9c(0x1d" +
"5)] + \'\\x22><b\\x20id=\\x22userId\' + _0x22405e + \'\\x22>\' + users[filmUserRatings[_" +
"0x5ddad2][_0x712d9c(0x1d5)]] + _0x712d9c(0x17a), _0x258ff4 += \'<td><a\\x20href=\\x" +
"22/Home/FilmRatings?filmId=\' + filmUserRatings[_0x5ddad2][_0x712d9c(0x1ae)] + _0" +
"x712d9c(0x1d8) + _0x22405e + \'\\x22>\' + films[filmUserRatings[_0x5ddad2][_0x712d9" +
"c(0x1ae)]] + _0x712d9c(0x17a), _0x258ff4 += _0x712d9c(0x1cd) + _0x22405e + \'\\x22" +
">\' + filmUserRatings[_0x5ddad2][\'filmRating\'] + _0x712d9c(0x192), _0x258ff4 += \'" +
"<td><button\\x20class=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\x20data-t" +
"oggle=\\x22modal\\x22\\x20data-target=\\x22#editUserRatingModal\' + _0x22405e + _0x71" +
"2d9c(0x1d9) + _0x22405e + _0x712d9c(0x1df), $(_0x712d9c(0x1b5))[_0x712d9c(0x19b)" +
"](_0x258ff4), document[\'getElementById\'](\'btnEditUserRating\' + _0x22405e)[\'addEv" +
"entListener\'](_0x712d9c(0x17c), function () { const _0x1a3a82 = _0x712d9c; $[_0x" +
"1a3a82(0x1ca)](_0x1a3a82(0x195) + filmUserRatings[_0x5ddad2][_0x1a3a82(0x1d5)] +" +
" _0x1a3a82(0x179) + filmUserRatings[_0x5ddad2][_0x1a3a82(0x1ae)], { \'rating\': do" +
"cument[_0x1a3a82(0x17b)](\'newUserRatingFor\' + _0x22405e)[_0x1a3a82(0x176)] }, fu" +
"nction (_0xc80f73) { const _0x46db65 = _0x1a3a82; filmUserRatings[_0x5ddad2][_0x" +
"46db65(0x17f)] = _0xc80f73[_0x46db65(0x17f)], document[_0x46db65(0x17b)](_0x46db" +
"65(0x17f) + _0x22405e)[\'innerHTML\'] = _0xc80f73[_0x46db65(0x17f)]; })[_0x1a3a82(" +
"0x1c8)](function (_0x40ab11) { const _0x320afe = _0x1a3a82; alert(_0x320afe(0x1c" +
"2) + _0x40ab11[_0x320afe(0x186)]); }); }), document[_0x712d9c(0x17b)](_0x712d9c(" +
"0x1c1) + _0x22405e)[_0x712d9c(0x171)](_0x712d9c(0x17c), function () { const _0x3" +
"74ad4 = _0x712d9c; $[_0x374ad4(0x19c)](\'/user/userRating?userId=\' + filmUserRati" +
"ngs[_0x5ddad2][_0x374ad4(0x1d5)] + _0x374ad4(0x179) + filmUserRatings[_0x5ddad2]" +
"[\'filmId\'], function (_0x191ce0) { const _0x250413 = _0x374ad4; _0x191ce0 ? docu" +
"ment[_0x250413(0x1a0)][_0x250413(0x1bd)]() : alert(_0x250413(0x190)); }); }); } " +
"$(\'#filmRatingTable\')[_0x712d9c(0x189)](); }); else { if (_0x3098d5[_0x3e2d03(0x" +
"1b1)](\'userId=\')) { const _0x525545 = _0x3098d5[_0x3e2d03(0x18f)](_0x3e2d03(0x1b" +
"3))[0x1]; await $[\'getJSON\'](_0x3e2d03(0x19a) + _0x525545)[_0x3e2d03(0x1da)](fun" +
"ction (_0x329247) { const _0x320e75 = _0x3e2d03, _0x3807b4 = document[_0x320e75(" +
"0x17b)](_0x320e75(0x1d0)); users[_0x329247[\'id\']] = _0x329247[_0x320e75(0x18a)]," +
" _0x3807b4[_0x320e75(0x1bc)][_0x3807b4[_0x320e75(0x1bc)][\'length\']] = new Option" +
"(_0x329247[_0x320e75(0x18a)], _0x329247[\'id\'], !![]), document[_0x320e75(0x17b)]" +
"(_0x320e75(0x1c9))[_0x320e75(0x1c7)] += _0x320e75(0x1de) + _0x329247[_0x320e75(0" +
"x18a)]; }), await $[_0x3e2d03(0x1a2)](_0x3e2d03(0x1a9))[\'done\'](function (_0x38e" +
"c94) { const _0x236a30 = _0x3e2d03, _0x53f6dd = document[\'getElementById\'](_0x23" +
"6a30(0x19f)); for (let _0xbf9739 = 0x0; _0xbf9739 < _0x38ec94[_0x236a30(0x1c3)];" +
" _0xbf9739++) { films[_0x38ec94[_0xbf9739][\'id\']] = _0x38ec94[_0xbf9739][_0x236a" +
"30(0x1aa)] + \'\\x20(\' + _0x38ec94[_0xbf9739][_0x236a30(0x1d7)] + \')\', _0x53f6dd[\'" +
"options\'][_0x53f6dd[_0x236a30(0x1bc)][\'length\']] = new Option(_0x38ec94[_0xbf973" +
"9][_0x236a30(0x1aa)] + \'\\x20(\' + _0x38ec94[_0xbf9739][_0x236a30(0x1d7)] + \')\', _" +
"0x38ec94[_0xbf9739][\'id\'], !![]); } }); const _0x3789d0 = document[_0x3e2d03(0x1" +
"a8)](\'th\')[0x0]; _0x3789d0[_0x3e2d03(0x1cc)](), await $[\'getJSON\'](_0x3e2d03(0x1" +
"b9) + _0x525545)[\'done\'](function (_0x205075) { const _0x597c79 = _0x3e2d03; for" +
" (let _0x87ddde = 0x0; _0x87ddde < _0x205075[_0x597c79(0x1c3)]; _0x87ddde++) { f" +
"ilmUserRatings[_0x597c79(0x19d)](_0x205075[_0x87ddde]); } const _0x466c18 = docu" +
"ment[\'getElementsByTagName\'](\'body\')[0x0]; for (let _0x2379f3 = 0x0; _0x2379f3 <" +
" filmUserRatings[_0x597c79(0x1c3)]; _0x2379f3++) { const _0x304a70 = document[_0" +
"x597c79(0x1ad)](_0x597c79(0x180)), _0x4b8e27 = filmUserRatings[_0x2379f3][_0x597" +
"c79(0x1d5)] + filmUserRatings[_0x2379f3][\'filmId\']; _0x304a70[_0x597c79(0x1cf)](" +
"\'id\', _0x597c79(0x174) + _0x4b8e27), _0x304a70[_0x597c79(0x1cf)](_0x597c79(0x1c5" +
"), _0x597c79(0x1a6)), _0x304a70[_0x597c79(0x1cf)](_0x597c79(0x197), _0x597c79(0x" +
"1e0)), _0x304a70[_0x597c79(0x1cf)](_0x597c79(0x1cb), _0x597c79(0x174) + _0x4b8e2" +
"7 + _0x597c79(0x1ce)), _0x304a70[_0x597c79(0x1cf)](\'aria-hidden\', _0x597c79(0x18" +
"7)), _0x304a70[\'innerHTML\'] += _0x597c79(0x1a4) + _0x4b8e27 + _0x597c79(0x185) +" +
" users[filmUserRatings[_0x2379f3][\'userId\']] + \'</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x" +
"0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-5\\x20col-form-label\\x22>Film</div>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<div\\x20class=\\x22col-sm-7\\x20my-2\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20<b>\' + films[filmUserRatings[_0x2379f3][_0x597c79(0x1ae)]] + _0x597c" +
"79(0x184) + _0x4b8e27 + _0x597c79(0x1d4) + _0x4b8e27 + _0x597c79(0x1b0) + _0x4b8" +
"e27 + _0x597c79(0x1b4), _0x466c18[_0x597c79(0x175)](_0x304a70); const _0x3e535a " +
"= document[_0x597c79(0x17b)](_0x597c79(0x18b) + _0x4b8e27), _0x43caee = _0x3e535" +
"a[_0x597c79(0x1c0)]; for (var _0x54bb5d = 0x0; _0x54bb5d < 0xa; _0x54bb5d++) { i" +
"f (_0x43caee[_0x54bb5d][_0x597c79(0x1c7)] == filmUserRatings[_0x2379f3][_0x597c7" +
"9(0x17f)]) { _0x43caee[_0x54bb5d][\'selected\'] = !![]; break; } } const _0x5cde1b" +
" = document[_0x597c79(0x1ad)](_0x597c79(0x180)); _0x5cde1b[\'setAttribute\'](\'id\'," +
" _0x597c79(0x1d2) + _0x4b8e27), _0x5cde1b[_0x597c79(0x1cf)](\'class\', _0x597c79(0" +
"x1a6)), _0x5cde1b[_0x597c79(0x1cf)](\'role\', _0x597c79(0x1e0)), _0x5cde1b[_0x597c" +
"79(0x1cf)](_0x597c79(0x1cb), _0x597c79(0x1d2) + _0x4b8e27 + \'Label\'), _0x5cde1b[" +
"_0x597c79(0x1cf)](_0x597c79(0x1a5), \'true\'), _0x5cde1b[_0x597c79(0x1c7)] += \'\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22" +
"document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\" +
"x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title\\x22" +
">Remove\\x20Rating</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\" +
"x20data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<s" +
"pan\\x20aria-hidden=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20Are\\x20you\\x20sure?\\x20Rating\\x20from\\x20user\\x20<b>\' + users[filmUserRatings[" +
"_0x2379f3][_0x597c79(0x1d5)]] + _0x597c79(0x1dd) + films[filmUserRatings[_0x2379" +
"f3][\'filmId\']] + \'</b>\\x20will\\x20be\\x20removed!</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button" +
"\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x" +
"22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x" +
"20btn-primary\\x22\\x20id=\\x22btnRemoveUserRating\' + _0x4b8e27 + \'\\x22\\x20data-dis" +
"miss=\\x22modal\\x22>Submit</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\', _0x466c18[_0x597c79(0x175)](_" +
"0x5cde1b); var _0x3b617d = \'<tr>\'; _0x3b617d += _0x597c79(0x172) + filmUserRatin" +
"gs[_0x2379f3][_0x597c79(0x1ae)] + \'\\x22><b\\x20id=\\x22filmId\' + _0x4b8e27 + \'\\x22" +
">\' + films[filmUserRatings[_0x2379f3][_0x597c79(0x1ae)]] + \'</b></a></td>\', _0x3" +
"b617d += \'<td><b\\x20id=\\x22filmRating\' + _0x4b8e27 + \'\\x22>\' + filmUserRatings[_" +
"0x2379f3][_0x597c79(0x17f)] + \'</b></td>\', _0x3b617d += _0x597c79(0x18c) + _0x4b" +
"8e27 + _0x597c79(0x1d9) + _0x4b8e27 + \'\\x22>Remove\\x20Rating</button></td></tr>\'" +
", $(_0x597c79(0x1b5))[_0x597c79(0x19b)](_0x3b617d), document[_0x597c79(0x17b)](\'" +
"btnEditUserRating\' + _0x4b8e27)[_0x597c79(0x171)](_0x597c79(0x17c), function () " +
"{ const _0x3462e1 = _0x597c79; $[_0x3462e1(0x1ca)](\'/user/userRating?userId=\' + " +
"filmUserRatings[_0x2379f3][_0x3462e1(0x1d5)] + _0x3462e1(0x179) + filmUserRating" +
"s[_0x2379f3][\'filmId\'], { \'rating\': document[\'getElementById\'](_0x3462e1(0x18b) " +
"+ _0x4b8e27)[_0x3462e1(0x176)] }, function (_0x264204) { const _0x741c63 = _0x34" +
"62e1; filmUserRatings[_0x2379f3][_0x741c63(0x17f)] = _0x264204[_0x741c63(0x17f)]" +
", document[_0x741c63(0x17b)](_0x741c63(0x17f) + _0x4b8e27)[\'innerHTML\'] = _0x264" +
"204[_0x741c63(0x17f)]; })[_0x3462e1(0x1c8)](function (_0x574789) { const _0x4b7a" +
"e7 = _0x3462e1; alert(_0x4b7ae7(0x1c2) + _0x574789[_0x4b7ae7(0x186)]); }); }), d" +
"ocument[_0x597c79(0x17b)](\'btnRemoveUserRating\' + _0x4b8e27)[_0x597c79(0x171)](_" +
"0x597c79(0x17c), function () { const _0x220542 = _0x597c79; $[_0x220542(0x19c)](" +
"_0x220542(0x195) + filmUserRatings[_0x2379f3][_0x220542(0x1d5)] + _0x220542(0x17" +
"9) + filmUserRatings[_0x2379f3][_0x220542(0x1ae)], function (_0x50dc01) { const " +
"_0xb90fef = _0x220542; _0x50dc01 ? document[_0xb90fef(0x1a0)][\'reload\']() : aler" +
"t(_0xb90fef(0x190)); }); }); } $(_0x597c79(0x1db))[_0x597c79(0x189)](); }), docu" +
"ment[_0x3e2d03(0x17b)](\'pageTitle\')[_0x3e2d03(0x1c7)] = \'Film\\x20Ratings\\x20by\\x" +
"20<span\\x20class=\\x22text-danger\\x22>\' + users[_0x525545] + _0x3e2d03(0x18d); } " +
"else { const _0x4107c7 = _0x3098d5[_0x3e2d03(0x18f)](\'?filmId=\')[0x1]; await $[_" +
"0x3e2d03(0x1a2)](\'/users\')[_0x3e2d03(0x1da)](function (_0x33c52d) { const _0x52e" +
"35f = _0x3e2d03, _0x59d996 = document[_0x52e35f(0x17b)](_0x52e35f(0x1d0)); for (" +
"let _0x5a189f = 0x0; _0x5a189f < _0x33c52d[_0x52e35f(0x1c3)]; _0x5a189f++) { use" +
"rs[_0x33c52d[_0x5a189f][\'id\']] = _0x33c52d[_0x5a189f][_0x52e35f(0x18a)], _0x59d9" +
"96[_0x52e35f(0x1bc)][_0x59d996[_0x52e35f(0x1bc)][_0x52e35f(0x1c3)]] = new Option" +
"(_0x33c52d[_0x5a189f][_0x52e35f(0x18a)], _0x33c52d[_0x5a189f][\'id\'], !![]); } })" +
", await $[_0x3e2d03(0x1a2)](_0x3e2d03(0x193) + _0x4107c7)[_0x3e2d03(0x1da)](func" +
"tion (_0x54d2ae) { const _0x11ddc7 = _0x3e2d03, _0x4e42e4 = document[_0x11ddc7(0" +
"x17b)](\'filmSelect\'); films[_0x54d2ae[\'id\']] = _0x54d2ae[_0x11ddc7(0x1aa)] + \'\\x" +
"20(\' + _0x54d2ae[_0x11ddc7(0x1d7)] + \')\', _0x4e42e4[_0x11ddc7(0x1bc)][_0x4e42e4[" +
"_0x11ddc7(0x1bc)][\'length\']] = new Option(_0x54d2ae[\'title\'] + \'\\x20(\' + _0x54d2" +
"ae[\'releaseYear\'] + \')\', _0x54d2ae[\'id\'], !![]), document[_0x11ddc7(0x17b)](\'aub" +
"utton\')[_0x11ddc7(0x1c7)] += \'\\x20for\\x20\' + films[_0x54d2ae[\'id\']], document[_0" +
"x11ddc7(0x17b)](_0x11ddc7(0x1d1))[_0x11ddc7(0x1c7)] = _0x11ddc7(0x1d6) + _0x54d2" +
"ae[\'id\'] + \'\\x22>\' + films[_0x4107c7] + _0x11ddc7(0x177); }); const _0x326536 = " +
"document[\'getElementsByTagName\'](\'th\')[0x1]; _0x326536[\'remove\'](), await $[_0x3" +
"e2d03(0x1a2)](\'/users/filmRatings?filmId=\' + _0x4107c7)[_0x3e2d03(0x1da)](functi" +
"on (_0x2553ab) { const _0x369826 = _0x3e2d03; for (let _0x5c38ec = 0x0; _0x5c38e" +
"c < _0x2553ab[_0x369826(0x1c3)]; _0x5c38ec++) { filmUserRatings[_0x369826(0x19d)" +
"](_0x2553ab[_0x5c38ec]); } const _0x4f37a2 = document[\'getElementsByTagName\'](\'b" +
"ody\')[0x0]; for (let _0x4fe5a1 = 0x0; _0x4fe5a1 < filmUserRatings[_0x369826(0x1c" +
"3)]; _0x4fe5a1++) { const _0xae60f1 = document[_0x369826(0x1ad)](_0x369826(0x180" +
")), _0x1e0b2c = filmUserRatings[_0x4fe5a1][\'userId\'] + filmUserRatings[_0x4fe5a1" +
"][\'filmId\']; _0xae60f1[_0x369826(0x1cf)](\'id\', _0x369826(0x174) + _0x1e0b2c), _0" +
"xae60f1[_0x369826(0x1cf)](_0x369826(0x1c5), _0x369826(0x1a6)), _0xae60f1[_0x3698" +
"26(0x1cf)](\'role\', _0x369826(0x1e0)), _0xae60f1[_0x369826(0x1cf)](_0x369826(0x1c" +
"b), \'editUserRatingModal\' + _0x1e0b2c + _0x369826(0x1ce)), _0xae60f1[_0x369826(0" +
"x1cf)](_0x369826(0x1a5), _0x369826(0x187)), _0xae60f1[_0x369826(0x1c7)] += _0x36" +
"9826(0x1a4) + _0x1e0b2c + _0x369826(0x185) + users[filmUserRatings[_0x4fe5a1][\'u" +
"serId\']] + _0x369826(0x1ab) + films[filmUserRatings[_0x4fe5a1][_0x369826(0x1ae)]" +
"] + _0x369826(0x184) + _0x1e0b2c + _0x369826(0x1d4) + _0x1e0b2c + \'\\x22>\\x0a\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<option>1</option><option>2</option><opt" +
"ion>3</option><option>4</option>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"<option>5</option><option>6</option><option>7</option><option>8</option>\\x0a\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<option>9</option><option>10</option>\\x0" +
"a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</select>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x" +
"0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20" +
"class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>" +
"\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20t" +
"ype=\\x22button\\x22\\x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditUserRati" +
"ng\' + _0x1e0b2c + _0x369826(0x1b4), _0x4f37a2[_0x369826(0x175)](_0xae60f1); cons" +
"t _0x4892cc = document[_0x369826(0x17b)](\'newUserRatingFor\' + _0x1e0b2c), _0x620" +
"832 = _0x4892cc[_0x369826(0x1c0)]; for (var _0x3e72e3 = 0x0; _0x3e72e3 < 0xa; _0" +
"x3e72e3++) { if (_0x620832[_0x3e72e3][_0x369826(0x1c7)] == filmUserRatings[_0x4f" +
"e5a1][_0x369826(0x17f)]) { _0x620832[_0x3e72e3][_0x369826(0x188)] = !![]; break;" +
" } } const _0x3613bf = document[\'createElement\'](_0x369826(0x180)); _0x3613bf[_0" +
"x369826(0x1cf)](\'id\', _0x369826(0x1d2) + _0x1e0b2c), _0x3613bf[\'setAttribute\'](\'" +
"class\', _0x369826(0x1a6)), _0x3613bf[_0x369826(0x1cf)](_0x369826(0x197), _0x3698" +
"26(0x1e0)), _0x3613bf[_0x369826(0x1cf)](_0x369826(0x1cb), _0x369826(0x1d2) + _0x" +
"1e0b2c + \'Label\'), _0x3613bf[\'setAttribute\'](\'aria-hidden\', \'true\'), _0x3613bf[_" +
"0x369826(0x1c7)] += _0x369826(0x170) + users[filmUserRatings[_0x4fe5a1][\'userId\'" +
"]] + _0x369826(0x1dd) + films[filmUserRatings[_0x4fe5a1][\'filmId\']] + _0x369826(" +
"0x1a3) + _0x1e0b2c + _0x369826(0x1b7), _0x4f37a2[_0x369826(0x175)](_0x3613bf); v" +
"ar _0x2bb3d6 = _0x369826(0x1ba); _0x2bb3d6 += _0x369826(0x1bb) + filmUserRatings" +
"[_0x4fe5a1][_0x369826(0x1d5)] + _0x369826(0x1b8) + _0x1e0b2c + \'\\x22>\' + users[f" +
"ilmUserRatings[_0x4fe5a1][_0x369826(0x1d5)]] + _0x369826(0x17a), _0x2bb3d6 += \'<" +
"td><b\\x20id=\\x22filmRating\' + _0x1e0b2c + \'\\x22>\' + filmUserRatings[_0x4fe5a1][_" +
"0x369826(0x17f)] + _0x369826(0x192), _0x2bb3d6 += \'<td><button\\x20class=\\x22btn\\" +
"x20btn-primary\\x20btn-lg\\x20btn-block\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-t" +
"arget=\\x22#editUserRatingModal\' + _0x1e0b2c + _0x369826(0x1d9) + _0x1e0b2c + _0x" +
"369826(0x1df), $(_0x369826(0x1b5))[\'append\'](_0x2bb3d6), document[_0x369826(0x17" +
"b)](_0x369826(0x194) + _0x1e0b2c)[_0x369826(0x171)](_0x369826(0x17c), function (" +
") { const _0x21347a = _0x369826; $[_0x21347a(0x1ca)](_0x21347a(0x195) + filmUser" +
"Ratings[_0x4fe5a1][_0x21347a(0x1d5)] + _0x21347a(0x179) + filmUserRatings[_0x4fe" +
"5a1][_0x21347a(0x1ae)], { \'rating\': document[\'getElementById\'](_0x21347a(0x18b) " +
"+ _0x1e0b2c)[_0x21347a(0x176)] }, function (_0xa9e334) { const _0x1134d5 = _0x21" +
"347a; filmUserRatings[_0x4fe5a1][_0x1134d5(0x17f)] = _0xa9e334[_0x1134d5(0x17f)]" +
", document[_0x1134d5(0x17b)](_0x1134d5(0x17f) + _0x1e0b2c)[_0x1134d5(0x1c7)] = _" +
"0xa9e334[_0x1134d5(0x17f)]; })[_0x21347a(0x1c8)](function (_0x5da8f0) { const _0" +
"x397e15 = _0x21347a; alert(\'Failed\\x20to\\x20process\\x20the\\x20request!\\x20\' + _0" +
"x5da8f0[_0x397e15(0x186)]); }); }), document[\'getElementById\'](_0x369826(0x1c1) " +
"+ _0x1e0b2c)[_0x369826(0x171)](_0x369826(0x17c), function () { const _0x5da6ad =" +
" _0x369826; $[\'delete\'](\'/user/userRating?userId=\' + filmUserRatings[_0x4fe5a1][" +
"_0x5da6ad(0x1d5)] + _0x5da6ad(0x179) + filmUserRatings[_0x4fe5a1][_0x5da6ad(0x1a" +
"e)], function (_0x48f332) { const _0xefd7b0 = _0x5da6ad; _0x48f332 ? document[\'l" +
"ocation\'][_0xefd7b0(0x1bd)]() : alert(_0xefd7b0(0x190)); })[\'fail\'](function (_0" +
"x5c4844) { const _0x2f9f70 = _0x5da6ad; alert(_0x2f9f70(0x1c2) + _0x5c4844[_0x2f" +
"9f70(0x186)]); }); }); } $(\'#filmRatingTable\')[_0x369826(0x189)](); }); } } } fu" +
"nction _0x124c(_0x50e713, _0x10c1aa) { const _0x2e4406 = _0x2e44(); return _0x12" +
"4c = function (_0x124c45, _0x3cee3b) { _0x124c45 = _0x124c45 - 0x170; let _0x265" +
"d02 = _0x2e4406[_0x124c45]; return _0x265d02; }, _0x124c(_0x50e713, _0x10c1aa); " +
"} function initAddUserFilmRatingBtn() { const _0x1e8d08 = _0x124c; document[_0x1" +
"e8d08(0x17b)](_0x1e8d08(0x1be))[_0x1e8d08(0x171)](\'click\', function () { const _" +
"0x39d9d0 = _0x1e8d08, _0x206520 = document[_0x39d9d0(0x17b)](_0x39d9d0(0x1d0))[_" +
"0x39d9d0(0x176)], _0x473668 = document[_0x39d9d0(0x17b)](_0x39d9d0(0x19f))[_0x39" +
"d9d0(0x176)]; $[_0x39d9d0(0x1ca)](\'/user/userRating?userId=\' + _0x206520 + _0x39" +
"d9d0(0x179) + _0x473668, { \'rating\': document[\'getElementById\'](_0x39d9d0(0x17e)" +
")[\'value\'] }, function (_0x199d6e) { const _0x12a1b2 = _0x39d9d0, _0x2bd887 = fi" +
"lmUserRatings[_0x12a1b2(0x1c4)](_0x4b5bba => _0x4b5bba[_0x12a1b2(0x1d5)] === _0x" +
"206520 && _0x4b5bba[\'filmId\'] === _0x473668); _0x2bd887 ? (filmUserRatings[filmU" +
"serRatings[\'findIndex\'](_0x5e45d8 => _0x5e45d8[_0x12a1b2(0x1d5)] === _0x206520 &" +
"& _0x5e45d8[\'filmId\'] === _0x473668)][_0x12a1b2(0x17f)] = _0x199d6e[\'filmRating\'" +
"], document[_0x12a1b2(0x17b)](_0x12a1b2(0x17f) + _0x206520 + _0x473668)[\'innerHT" +
"ML\'] = _0x199d6e[\'filmRating\']) : document[\'location\'][_0x12a1b2(0x1bd)](); })[_" +
"0x39d9d0(0x1c8)](function (_0x300fa8) { const _0x408e71 = _0x39d9d0; alert(\'Fail" +
"ed\\x20to\\x20process\\x20the\\x20request!\\x20\' + _0x300fa8[_0x408e71(0x186)]); }); " +
"}); }\n    </script>\n</head>\n<body");

WriteLiteral(" onload=\"init()\"");

WriteLiteral(">\n    <div>\n        <h3");

WriteLiteral(" class=\"my-3\"");

WriteLiteral(" id=\"pageTitle\"");

WriteLiteral("></h3>\n        <a");

WriteLiteral(" class=\"btn btn-outline-primary btn-sm\"");

WriteLiteral(" id=\"seeAllFilmRatings\"");

WriteLiteral(" href=\"/Home/FilmRatings\"");

WriteLiteral(">See all film ratings</a>\n    </div>\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"aubutton\"");

WriteLiteral(" class=\"btn btn-secondary btn-lg btn-block my-2\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#addUserRatingModal\"");

WriteLiteral(">Add/Update film rating</button>\n    <table");

WriteLiteral(" id=\"filmRatingTable\"");

WriteLiteral(" class=\"table table-bordered table-hover table-striped\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\n        <thead>\n            <tr>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Username</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Film (Release Year)</th>\n                <th");

WriteLiteral(" scole=\"col\"");

WriteLiteral(">Film Rating</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Actions</th>\n            </tr>\n        </thead>\n        <tbody></tbody>\n    </ta" +
"ble>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"addUserRatingModal\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"addUserRatingModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Add Film Rating</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form");

WriteLiteral(" id=\"createUserForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <label");

WriteLiteral(" for=\"userSelect\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">User</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"my-1\"");

WriteLiteral(" id=\"userSelect\"");

WriteLiteral("></select>\n                            </div>\n                            <label");

WriteLiteral(" for=\"filmSelect\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Film</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"my-1\"");

WriteLiteral(" id=\"filmSelect\"");

WriteLiteral("></select>\n                            </div>\n                            <label");

WriteLiteral(" for=\"filmRatingSelect\"");

WriteLiteral(" class=\"col-sm-2 col-form-label my-2\"");

WriteLiteral(">Rating</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10 my-2\"");

WriteLiteral(">\n                                <select");

WriteLiteral(" class=\"custom-select\"");

WriteLiteral(" id=\"filmRatingSelect\"");

WriteLiteral(">\n                                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">1</option>\n                                    <option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">2</option>\n                                    <option");

WriteLiteral(" value=\"3\"");

WriteLiteral(">3</option>\n                                    <option");

WriteLiteral(" value=\"4\"");

WriteLiteral(">4</option>\n                                    <option");

WriteLiteral(" value=\"5\"");

WriteLiteral(">5</option>\n                                    <option");

WriteLiteral(" value=\"6\"");

WriteLiteral(" selected>6</option> <!-- default select -->\n                                    " +
"<option");

WriteLiteral(" value=\"7\"");

WriteLiteral(">7</option>\n                                    <option");

WriteLiteral(" value=\"8\"");

WriteLiteral(">8</option>\n                                    <option");

WriteLiteral(" value=\"9\"");

WriteLiteral(">9</option>\n                                    <option");

WriteLiteral(" value=\"10\"");

WriteLiteral(">10</option>\n                                </select>\n                          " +
"  </div>\n                        </div>\n                    </form>\n            " +
"        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\n                        <p");

WriteLiteral(" class=\"text-justify my-0\"");

WriteLiteral(">\n                            <b>\n                                <u");

WriteLiteral(" class=\"py-2\"");

WriteLiteral(@">Note</u><br />
                                If a film rating already exists for the selected user-film pair,
                                this operation would instead update the previous rating instead of creating a new one!
                            </b>
                        </p>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnAddUserFilmRating\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Submit</button>\n                </div>\n            </div>\n        </div>\n    </d" +
"iv>\n</body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class FilmRatingsBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
