#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD_Project.Views.Home
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Users : UsersBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\n<html>\n<head>\n    <script defer>\n        const _0xd430ae = _0x530" +
"a; function _0x530a(_0x257a79, _0x2b1a9b) { const _0x4deb12 = _0x4deb(); return " +
"_0x530a = function (_0x530a73, _0x529aeb) { _0x530a73 = _0x530a73 - 0x157; let _" +
"0x1a7f85 = _0x4deb12[_0x530a73]; return _0x1a7f85; }, _0x530a(_0x257a79, _0x2b1a" +
"9b); } function _0x4deb() { const _0x2c9e3c = [\'value\', \'9ZUgLks\', \'\\x22>Remove\\" +
"x20User</button></td></tr>\', \'Label\', \'\\x22\\x20data-dismiss=\\x22modal\\x22>Submit" +
"</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\', \'DataTable\', \'reload\'," +
" \'appendChild\', \'btnEditUser\', \'createElement\', \'body\', \'div\', \'modal\\x20fade\', " +
"\'/users\', \'dialog\', \'#btnCreateUser\', \'#userTable\', \'1kjhOiL\', \'1263448EjOzVD\', " +
"\'119840ZiUkrq\', \'aria-hidden\', \'120arhMha\', \'4263624oKGzKR\', \'742230SsLHsk\', \'us" +
"ername\', \'length\', \'class\', \'setAttribute\', \'append\', \'220332seiQGE\', \'/user/\', " +
"\'location\', \'put\', \'<tr>\', \'editUsernameModal\', \'682538YKsIyu\', \'\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20<div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22document\\x22>\\x0a\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content\\x22>\\x0a\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-header\\x22>\\x0a\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<h5\\x20class=\\x22modal-title" +
"\\x22>Remove\\x20User</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22close\\x22\\x20data-dismis" +
"s=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<span\\x20aria-hidden=\\x22true\\x2" +
"2>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-body\\x22>\\x0a" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<b>Are\\x20you\\x20sur" +
"e\\x20you\\x20want\\x20to\\x20delete\\x20this\\x20user?\\x20This\\x20operation\\x20cannot" +
"\\x20be\\x20undone!</b>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\" +
"x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-foote" +
"r\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<butto" +
"n\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\" +
"x22modal\\x22>Cancel</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20class=\\x22btn\\x20btn-primary\\x" +
"22\\x20id=\\x22btnRemoveUser\', \'role\', \'Username\\x20cannot\\x20be\\x20an\\x20empty\\x2" +
"0string!\', \'<td><b\\x20id=\\x22username\', \'removeUserModal\', \'\\x22\\x20class=\\x22co" +
"l-sm-2\\x20col-form-label\\x22>Username</label>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\" +
"x22col-sm-10\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<input\\x20type=\\x22text\\x22" +
"\\x20class=\\x22form-control\\x22\\x20id=\\x22newUsernameFor\', \'ready\', \'\\x22\\x20data" +
"-dismiss=\\x22modal\\x22>Confirm</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<" +
"/div>\', \'getElementById\', \'btnRemoveUser\', \'getJSON\', \'\\x22>Edit\\x20Username</bu" +
"tton>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20<a\\x20class=\\x22btn\\x20btn-outline-primary\\x20btn-lg\\x20btn-block\\x22\\x" +
"20href=\\x22/Home/FilmRatings?userId=\', \'1397OcVuxl\', \'\\x22\\x20value=\\x22\', \'1022" +
"154MexJdl\', \'aria-labelledby\', \'getElementsByTagName\', \'addEventListener\', \'\\x22" +
"\\x20role=\\x22button\\x22>Film\\x20Rating\\x20Management</a>\\x0a\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<a\\x20class=\\x22btn\\" +
"x20btn-outline-info\\x20btn-lg\\x20btn-block\\x22\\x20href=\\x22/Home/Films?filmRec=\'" +
", \'delete\', \'\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-dialog\\x22\\x20role=\\x22" +
"document\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-content" +
"\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal" +
"-header\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"<h5\\x20class=\\x22modal-title\\x22>Edit\\x20Username</h5>\\x0a\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20clas" +
"s=\\x22close\\x22\\x20data-dismiss=\\x22modal\\x22\\x20aria-label=\\x22Close\\x22>\\x0a\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<s" +
"pan\\x20aria-hidden=\\x22true\\x22>&times;</span>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</button>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x2" +
"0class=\\x22modal-body\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20<form\\x20id=\\x22editUsername\', \'Failed\\x20to\\x20remove\\x20this\\x20" +
"user!\', \'push\', \'newUsername\', \'innerHTML\', \'click\', \'true\']; _0x4deb = function" +
" () { return _0x2c9e3c; }; return _0x4deb(); } (function (_0x2b4615, _0x371ca9) " +
"{ const _0x104571 = _0x530a, _0x140468 = _0x2b4615(); while (!![]) { try { const" +
" _0xc61691 = -parseInt(_0x104571(0x16b)) / 0x1 * (-parseInt(_0x104571(0x17d)) / " +
"0x2) + parseInt(_0x104571(0x18c)) / 0x3 + parseInt(_0x104571(0x170)) / 0x4 + -pa" +
"rseInt(_0x104571(0x171)) / 0x5 + -parseInt(_0x104571(0x16f)) / 0x6 * (-parseInt(" +
"_0x104571(0x177)) / 0x7) + parseInt(_0x104571(0x16c)) / 0x8 * (-parseInt(_0x1045" +
"71(0x15b)) / 0x9) + parseInt(_0x104571(0x16d)) / 0xa * (-parseInt(_0x104571(0x18" +
"a)) / 0xb); if (_0xc61691 === _0x371ca9) break; else _0x140468[\'push\'](_0x140468" +
"[\'shift\']()); } catch (_0x3e764d) { _0x140468[\'push\'](_0x140468[\'shift\']()); } }" +
" }(_0x4deb, 0x860cc), $(document)[_0xd430ae(0x184)](function () { const _0x4227f" +
"4 = _0xd430ae; $(_0x4227f4(0x169))[_0x4227f4(0x158)](function () { const _0x4c1f" +
"ca = _0x4227f4; $[\'post\'](\'/user\', { \'username\': document[_0x4c1fca(0x186)](_0x4" +
"c1fca(0x195))[_0x4c1fca(0x15a)] }, function (_0xc00c3) { const _0x48d60f = _0x4c" +
"1fca; document[_0x48d60f(0x179)][\'reload\'](); }); }); })); var users = []; funct" +
"ion init() { const _0x3fdf3a = _0xd430ae; $[_0x3fdf3a(0x188)](_0x3fdf3a(0x167))[" +
"\'done\'](function (_0x2067a4) { const _0x60c4eb = _0x3fdf3a; for (let _0x400aaf =" +
" 0x0; _0x400aaf < _0x2067a4[_0x60c4eb(0x173)]; _0x400aaf++) { users[_0x60c4eb(0x" +
"194)](_0x2067a4[_0x400aaf]); } const _0x18da15 = document[_0x60c4eb(0x18e)](_0x6" +
"0c4eb(0x164))[0x0]; for (let _0x26e10f = 0x0; _0x26e10f < users[_0x60c4eb(0x173)" +
"]; _0x26e10f++) { const _0x40f4ae = document[_0x60c4eb(0x163)](_0x60c4eb(0x165))" +
"; _0x40f4ae[_0x60c4eb(0x175)](\'id\', \'editUsernameModal\' + users[_0x26e10f][\'id\']" +
"), _0x40f4ae[_0x60c4eb(0x175)](_0x60c4eb(0x174), _0x60c4eb(0x166)), _0x40f4ae[_0" +
"x60c4eb(0x175)](\'role\', \'dialog\'), _0x40f4ae[_0x60c4eb(0x175)](_0x60c4eb(0x18d)," +
" _0x60c4eb(0x17c) + users[_0x26e10f][\'id\'] + _0x60c4eb(0x15d)), _0x40f4ae[_0x60c" +
"4eb(0x175)](\'aria-hidden\', _0x60c4eb(0x159)), _0x40f4ae[_0x60c4eb(0x157)] += _0x" +
"60c4eb(0x192) + users[_0x26e10f][\'id\'] + \'\\x22\\x20>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22form-gr" +
"oup\\x20row\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<label\\x20for=\\x22newUsernameFor\' + users[_0x" +
"26e10f][\'id\'] + _0x60c4eb(0x183) + users[_0x26e10f][\'id\'] + _0x60c4eb(0x18b) + u" +
"sers[_0x26e10f][_0x60c4eb(0x172)] + \'\\x22>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x" +
"0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</form>\\x0a\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20</div>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\" +
"x20\\x20\\x20\\x20\\x20\\x20<div\\x20class=\\x22modal-footer\\x22>\\x0a\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x" +
"20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20type=\\x22button\\x22\\x20" +
"class=\\x22btn\\x20btn-secondary\\x22\\x20data-dismiss=\\x22modal\\x22>Cancel</button>" +
"\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20" +
"\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20<button\\x20t" +
"ype=\\x22button\\x22\\x20class=\\x22btn\\x20btn-primary\\x22\\x20id=\\x22btnEditUser\' + " +
"users[_0x26e10f][\'id\'] + _0x60c4eb(0x15e), _0x18da15[_0x60c4eb(0x161)](_0x40f4ae" +
"); const _0x366db1 = document[\'createElement\'](_0x60c4eb(0x165)); _0x366db1[_0x6" +
"0c4eb(0x175)](\'id\', \'removeUserModal\' + users[_0x26e10f][\'id\']), _0x366db1[\'setA" +
"ttribute\'](_0x60c4eb(0x174), _0x60c4eb(0x166)), _0x366db1[_0x60c4eb(0x175)](_0x6" +
"0c4eb(0x17f), _0x60c4eb(0x168)), _0x366db1[_0x60c4eb(0x175)](\'aria-labelledby\', " +
"_0x60c4eb(0x182) + users[_0x26e10f][\'id\'] + _0x60c4eb(0x15d)), _0x366db1[_0x60c4" +
"eb(0x175)](_0x60c4eb(0x16e), _0x60c4eb(0x159)), _0x366db1[_0x60c4eb(0x157)] += _" +
"0x60c4eb(0x17e) + users[_0x26e10f][\'id\'] + _0x60c4eb(0x185), _0x18da15[_0x60c4eb" +
"(0x161)](_0x366db1); var _0x237a31 = _0x60c4eb(0x17b); _0x237a31 += _0x60c4eb(0x" +
"181) + users[_0x26e10f][\'id\'] + \'\\x22>\' + users[_0x26e10f][\'username\'] + \'</b></" +
"td>\', _0x237a31 += \'<td><button\\x20class=\\x22btn\\x20btn-primary\\x20btn-lg\\x20btn" +
"-block\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-target=\\x22#editUsernameModal\' +" +
" users[_0x26e10f][\'id\'] + _0x60c4eb(0x189) + users[_0x26e10f][\'id\'] + _0x60c4eb(" +
"0x190) + users[_0x26e10f][\'id\'] + \'\\x22\\x20role=\\x22button\\x22>Get\\x20Film\\x20Su" +
"ggestions</a>\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x2" +
"0\\x20\\x20\\x20\\x20<button\\x20class=\\x22btn\\x20btn-outline-danger\\x20btn-lg\\x20btn" +
"-block\\x22\\x20data-toggle=\\x22modal\\x22\\x20data-target=\\x22#removeUserModal\' + u" +
"sers[_0x26e10f][\'id\'] + _0x60c4eb(0x15c), $(\'#userTable\\x20tbody\')[_0x60c4eb(0x1" +
"76)](_0x237a31), document[_0x60c4eb(0x186)](_0x60c4eb(0x162) + users[_0x26e10f][" +
"\'id\'])[\'addEventListener\'](_0x60c4eb(0x158), function () { const _0x18fd39 = _0x" +
"60c4eb; document[_0x18fd39(0x186)](\'newUsernameFor\' + users[_0x26e10f][\'id\'])[_0" +
"x18fd39(0x15a)] ? $[_0x18fd39(0x17a)](_0x18fd39(0x178) + users[_0x26e10f][\'id\']," +
" { \'username\': document[_0x18fd39(0x186)](\'newUsernameFor\' + users[_0x26e10f][\'i" +
"d\'])[\'value\'] }, function (_0x7d226e) { const _0x4213ee = _0x18fd39; users[_0x26" +
"e10f][_0x4213ee(0x172)] = _0x7d226e[_0x4213ee(0x172)], document[_0x4213ee(0x186)" +
"](\'username\' + users[_0x26e10f][\'id\'])[\'innerHTML\'] = _0x7d226e[_0x4213ee(0x172)" +
"]; }) : alert(_0x18fd39(0x180)); }), document[_0x60c4eb(0x186)](_0x60c4eb(0x187)" +
" + users[_0x26e10f][\'id\'])[_0x60c4eb(0x18f)](_0x60c4eb(0x158), function () { con" +
"st _0x52d785 = _0x60c4eb; $[_0x52d785(0x191)](_0x52d785(0x178) + users[_0x26e10f" +
"][\'id\'], function (_0x318a42) { const _0x578cb0 = _0x52d785; _0x318a42 ? documen" +
"t[\'location\'][_0x578cb0(0x160)]() : alert(_0x578cb0(0x193)); }); }); } $(_0x60c4" +
"eb(0x16a))[_0x60c4eb(0x15f)](); }); }\n    </script>\n</head>\n<body");

WriteLiteral(" onload=\"init()\"");

WriteLiteral(">\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary btn-lg btn-block my-2\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#createUserModal\"");

WriteLiteral(">Add new user</button>\n    <table");

WriteLiteral(" id=\"userTable\"");

WriteLiteral(" class=\"table table-bordered table-hover table-striped\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\n        <thead>\n            <tr>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Username</th>\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Actions</th>\n            </tr>\n        </thead>\n        <tbody></tbody>\n    </ta" +
"ble>\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"createUserModal\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"createUserModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Create User</h5>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\n                    </button>\n                </div>\n            " +
"    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <form");

WriteLiteral(" id=\"createUserForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\n                            <label");

WriteLiteral(" for=\"newUsername\"");

WriteLiteral(" class=\"col-sm-2 col-form-label\"");

WriteLiteral(">Username</label>\n                            <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"newUsername\"");

WriteLiteral(">\n                            </div>\n                        </div>\n             " +
"       </form>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancel</button>\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnCreateUser\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Submit</button>\n                </div>\n            </div>\n        </div>\n    </d" +
"iv>\n</body>\n</html>\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class UsersBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
